### ISSUE TITLE
setup script Error when build egg

### ISSUE THREAD

**Issue by hiranoaya** [dmlc/tvm#1032]
```
$ python setup.py bdist_egg
Compiling tvm/_ffi/_cython/core.pyx because it changed.
Cythonizing tvm/_ffi/_cython/core.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    void* resource_handle)

ctypedef void (*TVMPackedCFuncFinalizer)(void* resource_handle)

cdef extern from "tvm/runtime/c_runtime_api.h":
    void TVMAPISetLastError(const char* msg);
                                           ^
------------------------------------------------------------

tvm/_ffi/_cython/./base.pxi:67:44: Syntax error in C variable declaration
Traceback (most recent call last):
  File "setup.py", line 122, in <module>
    ext_modules=config_cython(),
  File "setup.py", line 80, in config_cython
    return cythonize(ret)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 798, in cythonize
    cythonize_one(*args[1:])
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 915, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: tvm/_ffi/_cython/core.pyx

```

**Comment by PariksheetPinjari909** [comment]
Try make clean, then make and install again.

**Comment by hiranoaya** [comment]
pure dir  here , it seems to no ';' 
void TVMAPISetLastError(const char* msg);

**Comment by tqchen** [comment]
please upgrade your cython and try again

**Comment by tqchen** [comment]
see https://github.com/dmlc/tvm/issues/964

**Comment by tqchen** [comment]
This being said, the semicolon should be preferably fixed. Feel free to send a PR to fix this:)

**Comment by eyecod-toppick** [comment]
I recently encountered a similar issue and found that uninstalling Cython before installing tvm solved this problem

**Comment by coco-alen** [comment]
I recently encountered a similar issue and found that uninstalling Cython before installing tvm will solve this problem
