### ISSUE TITLE
Vulkan compile support required

### ISSUE THREAD

**Issue by PariksheetPinjari909** [dmlc/tvm#1099]
Am trying to compile model and facing vulkan target is not enable error, need help on same

target = 'vulkan'
target_host = "llvm -target=%s-linux-android" % "arm64"
with nnvm.compiler.build_config(opt_level=opt_level, add_pass=None):
    graph, lib, params = nnvm.compiler.build(sym, target, shape, params=params, target_host=target_host)

error : 
`tvm._ffi.base.TVMError: [17:51:39] src/codegen/codegen.cc:27: Check failed: bf != nullptr Target vulkan is not enabled
`
Installed Vulkan SDK and setup path environment successfully, still facing the above compile issue.

**Comment by tqchen** [comment]
could due to trivial errors like USE_VULKAN=1 not enabled, or did not make clean and make

**Comment by tqchen** [comment]
see https://github.com/dmlc/tvm/blob/master/src/codegen/spirv/build_vulkan.cc#L6

**Comment by PariksheetPinjari909** [comment]
After compile TVM with Vulkan enable(USE_VULKAN=1), am facing Driver incompatible error. Followed install vulkan sdk [here](https://github.com/dmlc/tvm/blob/master/tests/ci_build/install/ubuntu_install_vulkan.sh)

`Build Graph...
Traceback (most recent call last):
  File "run_mobile.py", line 62, in <module>
    graph, lib, params = nnvm.compiler.build(sym, target, shape, params=params, target_host=target_host)
  File "/home/d00248762/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/build_module.py", line 251, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/home/d00248762/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/home/d00248762/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/home/d00248762/.local/lib/python3.6/site-packages/tvm-0.2.0-py3.6-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/d00248762/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/build_module.py", line 119, in _build
    return tvm.build(funcs, target=target, target_host=target_host)
  File "/home/d00248762/.local/lib/python3.6/site-packages/tvm-0.2.0-py3.6-linux-x86_64.egg/tvm/build_module.py", line 478, in build
    mdev = codegen.build_module(fdevice, str(target_device))
  File "/home/d00248762/.local/lib/python3.6/site-packages/tvm-0.2.0-py3.6-linux-x86_64.egg/tvm/codegen.py", line 20, in build_module
    return _Build(lowered_func, target)
  File "/home/d00248762/.local/lib/python3.6/site-packages/tvm-0.2.0-py3.6-linux-x86_64.egg/tvm/_ffi/function.py", line 280, in my_api_func
    return flocal(*args)
  File "/home/d00248762/.local/lib/python3.6/site-packages/tvm-0.2.0-py3.6-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/d00248762/.local/lib/python3.6/site-packages/tvm-0.2.0-py3.6-linux-x86_64.egg/tvm/_ffi/base.py", line 66, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [11:36:03] src/runtime/vulkan/vulkan_device_api.cc:504: Check failed: __e == VK_SUCCESS Vulan Error, code=-9: VK_ERROR_INCOMPATIBLE_DRIVER`

**Comment by tqchen** [comment]
please see if https://github.com/dmlc/tvm/pull/1107 fixed the problem.

We still need vulkan SDK to validate the SPIRV tools etc, but we do not need to have vulkan enabled devices to be available
