### ISSUE TITLE
unmatch type int64 vs. uint64  when call tvm.const(2 ** 64 - 1, "uint64")

### ISSUE THREAD

**Issue by hiranoaya** [dmlc/tvm#1101]
python setup.py bdist_egg
easy_install --user tvm-0.2.0-py2.7-linux-x86_64.egg

```
$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tvm
TVM: Initializing cython mode...
>>> tvm.const(2 ** 64 - 1, "uint64")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python2.7/site-packages/tvm-0.2.0-py2.7-linux-x86_64.egg/tvm/api.py", line 45, in const
    return _api_internal._const(value, dtype)
  File "~/.local/lib/python2.7/site-packages/tvm-0.2.0-py2.7-linux-x86_64.egg/tvm/_ffi/function.py", line 280, in my_api_func
    return flocal(*args)
  File "tvm/_ffi/_cython/./function.pxi", line 265, in tvm._ffi._cy2.core.FunctionBase.__call__
  File "tvm/_ffi/_cython/./function.pxi", line 214, in tvm._ffi._cy2.core.FuncCall
  File "tvm/_ffi/_cython/./function.pxi", line 205, in tvm._ffi._cy2.core.FuncCall3
  File "tvm/_ffi/_cython/./function.pxi", line 94, in tvm._ffi._cy2.core.make_arg
OverflowError: Python int too large to convert to C long
>>>

```

without egg file install, export PYTHONPATH to nnvm/tvm/python
it run ok
```
>>> import tvm
>>> tvm.const(2 ** 64 - 1, "uint64")
(uint64)18446744073709551615
```

Any difference between core.so  or core.pxy/*.pxi ?

**Comment by tqchen** [comment]
This is mainly because the value of integer is indeed too large to fit into int64_t. To make the API simple, we are only passing the value of range int64 integers around the API.

The error raised in cython interface is correct that this is the case which we did not handle well.

**Comment by tqchen** [comment]
in the future, please redirect the general question to https://discuss.tvmlang.org/
