### ISSUE TITLE
[TOPI] Support deconvolution in opengl 

### ISSUE THREAD

**Issue by dtmoodie** [dmlc/tvm#1133]
When trying to deploy a model of mine that uses deconvolution for upsampling of feature maps, I get the following error when trying to target opengl.

`NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tvm-0.2.0-py2.7-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/usr/local/lib/python2.7/dist-packages/nnvm-0.8.0-py2.7.egg/nnvm/top/nn.py", line 138, in schedule_conv2d_transpose
    return topi.generic.schedule_conv2d_transpose_nchw(outs)
  File "<decorator-gen-164>", line 2, in schedule_conv2d_transpose_nchw
  File "/usr/local/lib/python2.7/dist-packages/tvm-0.2.0-py2.7-linux-x86_64.egg/tvm/target.py", line 343, in dispatch_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/topi-0.2.0-py2.7.egg/topi/generic/nn.py", line 71, in schedule_conv2d_transpose_nchw
    return _default_schedule(outs, False)
  File "/usr/local/lib/python2.7/dist-packages/topi-0.2.0-py2.7.egg/topi/generic/nn.py", line 11, in _default_schedule
    raise RuntimeError("schedule not registered for '%s'" % target)
RuntimeError: schedule not registered for 'opengl'`

**Comment by dtmoodie** [comment]
I'm currently trying to target a raspberry pi's GPU.

**Comment by tqchen** [comment]
I see, although it is possible to program QPU via OpenGL. My guess is that it won't yield desired performance. A better way might be build a direct QPU asm backend for TVM. In the meanwhile, the peak flops you can get from ARM core is already as good as QPU(if we optimize for 8bit) so we there is no official effort on this.

**Comment by dtmoodie** [comment]
Thank you, I'll try deploying to the raspberry pi CPU to see if it is sufficient.
