### ISSUE TITLE
Tutorial example "How to optimize GEMM on CPU" not running

### ISSUE THREAD

**Issue by xiaolin-cheng** [dmlc/tvm#1148]
I was trying to run the example script from "How to optimize GEMM on CPU" **opt_gemm.py**, but got the following error on both  server **Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz** and laptop **Intel i-7 5600U @ 2.6GHz**:

Numpy running time: 0.007843
Traceback (most recent call last):
  File "opt_gemm.py", line 89, in <module>
    func = tvm.build(s, [A, B, C], target=target, name='mmult')
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.2.0-py3.5-linux-x86_64.egg/tvm/build_module.py", line 492, in build
    mhost = codegen.build_module(fhost, str(target_host))
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.2.0-py3.5-linux-x86_64.egg/tvm/codegen.py", line 20, in build_module
    return _Build(lowered_func, target)
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.2.0-py3.5-linux-x86_64.egg/tvm/_ffi/function.py", line 280, in my_api_func
    return flocal(*args)
  File "tvm/_ffi/_cython/function.pxi", line 264, in core.FunctionBase.__call__ (tvm/_ffi/_cython/core.cpp:6954)
  File "tvm/_ffi/_cython/function.pxi", line 213, in core.FuncCall (tvm/_ffi/_cython/core.cpp:6176)
  File "tvm/_ffi/_cython/function.pxi", line 205, in core.FuncCall3 (tvm/_ffi/_cython/core.cpp:6078)
  File "tvm/_ffi/_cython/base.pxi", line 131, in core.CALL (tvm/_ffi/_cython/core.cpp:1831)
**tvm._ffi.base.TVMError: [17:09:14] src/codegen/codegen.cc:27: Check failed: bf != nullptr Target llvm is not enabled**

Anything missed?

Thank you

**Comment by tqchen** [comment]
please ask the general discussion question at https://discuss.tvmlang.org/

In your case, as the error message indicated, you need to build tvm with llvm support http://docs.tvmlang.org/how_to/install.html#customized-building
