### ISSUE TITLE
to_mxnet_func on Raspberry Pi

### ISSUE THREAD

**Issue by jwfromm** [dmlc/tvm#1195]
It looks like to_mxnet_func hits an error when run on raspberry pi. I've tried a few schedules and always run into the same error, maybe it has to do with some arm types having different identifiers? TVM and mxnet are both up to date and build from source, they work without issue.

Here's a quick snippet that can replicate the issue
```
import os
import numpy as np
import tvm
import topi
import topi.testing
from tvm.contrib.pickle_memoize import memoize
from topi.util import get_const_tuple
from tvm.contrib.mxnet import to_mxnet_func
import mxnet as mx
from mxnet import nd, autograd, gluon

in_height = in_width = 56
in_channel = 64
num_filter = 64
kernel = 3
stride = 1
padding = 1
batch=1
input_type = 'float32'
out_dtype='float32'

def generate_quantized_np(shape, bits, out_dtype):
    np.random.seed(0)
    min_val = 0
    max_val = 1 << bits
    return np.random.randint(min_val, max_val, size=shape).astype(out_dtype)

target = 'llvm -target=armv7l-none-linux-gnueabihf -mcpu=cortex-a53 -mattr=+neon'
ctx = tvm.cpu(0)
with tvm.target.rasp():
    A = tvm.placeholder((batch, in_channel, in_height, in_width), dtype=input_type, name='A')
    W = tvm.placeholder((num_filter, in_channel, kernel, kernel), dtype=input_type, name='W')
    B = topi.nn.conv2d(A, W, stride, padding, out_dtype=out_dtype, layout="NCHW")
    s = topi.generic.schedule_conv2d_nchw([B])

a_shape = get_const_tuple(A.shape)
w_shape = get_const_tuple(W.shape)
dtype = A.dtype

a_np = generate_quantized_np(get_const_tuple(A.shape), activation_bits, input_type)
w_np = generate_quantized_np(get_const_tuple(W.shape), weight_bits, input_type)

a = tvm.nd.array(a_np, ctx)
w = tvm.nd.array(w_np, ctx)
b = tvm.nd.array(np.zeros(get_const_tuple(B.shape), dtype=B.dtype), ctx)
func = tvm.build(s, [A, W, B], target)

func(a, w, b) # works fine
mx_func = to_mxnet_func(func) # crashes
```

The error I'm encountering is
```
terminate called after throwing an instance of 'dmlc::Error'
  what():  TVMCall CFunc Error:
Traceback (most recent call last):
  File "/home/pi/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/pi/tvm/python/tvm/_ffi/_ctypes/function.py", line 51, in <genexpr>
    pyargs = (C_TO_PY_ARG_SWITCH[type_codes[i]](args[i]) for i in range(num_args))
KeyError: 14999744
```

**Comment by tqchen** [comment]
can you do a bit debug here? The error seems to indicate the the ```type_codes[i]``` being passed was not the right one (14999744 )

**Comment by jwfromm** [comment]
I'm having a hard time tracing exactly what's going on as parsing to_mxnet_func source code is very difficult, but it looks like a pointer is being sent to to_tvm_func instead of a type. Maybe there's a condition check somewhere thats defaulting?

**Comment by tqchen** [comment]
discussed with @jwfromm offline, could due to different compilers, closing for now
