### ISSUE TITLE
TypeError: shape value must be int iterator

### ISSUE THREAD

**Issue by XiaSunny** [dmlc/tvm#1507]
When i  run deploy_ssd.py,i meet this problem:
Traceback (most recent call last):
  File "deploy_ssd.py", line 78, in <module>
    graph, lib, params = compiler.build(net, target, {"data": dshape}, params=params)
  File "/home/pi/tvm/nnvm/python/nnvm/compiler/build_module.py", line 279, in build
    graph, params = precompute_prune(graph, params)
  File "/home/pi/tvm/nnvm/python/nnvm/compiler/build_module.py", line 396, in precompute_prune
    out_arrs = _run_graph(pre_graph, params)
  File "/home/pi/tvm/nnvm/python/nnvm/compiler/build_module.py", line 345, in _run_graph
    graph, libmod, _ = build(graph, target, shape, dtype)
  File "/home/pi/tvm/nnvm/python/nnvm/compiler/build_module.py", line 246, in build
    raise TypeError("shape value must be int iterator")
TypeError: shape value must be int iterator

Thank you. @tqchen

**Comment by srkreddy1238** [comment]
@XiaSunny 

The error basically tell that there are non int values in the shape dictionary argument to build.
Can you share the code snippet ?

Also suggest to raise this general discussion @ https://discuss.tvm.ai/

**Comment by XiaSunny** [comment]
Thanks for your reply.My code snippnet is:
[deploy_ssd.txt](https://github.com/dmlc/tvm/files/2241313/deploy_ssd.txt)

**Comment by tqchen** [comment]
let us move general discussion to https://discuss.tvm.ai/
