### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 0)

### ISSUE THREAD

**Issue by huanglishan6** [dmlc/tvm#1675]
Traceback (most recent call last):
  File "onnx_test_hls.py", line 57, in <module>
    shape = shape_dict, params=params)
  File "/home/hls/Documents/MyWorkplace/sofeware/tvm/nnvm/python/nnvm/compiler/build_module.py", line 305, in build
    graph = graph.apply("GraphCompile")
  File "/home/hls/Documents/MyWorkplace/sofeware/tvm/nnvm/python/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/home/hls/Documents/MyWorkplace/sofeware/tvm/nnvm/python/nnvm/_base.py", line 75, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/home/hls/Documents/MyWorkplace/sofeware/tvm/python/tvm/_ffi/_ctypes/function.py", line 55, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/hls/Documents/MyWorkplace/sofeware/tvm/nnvm/python/nnvm/top/nn.py", line 106, in compute_conv2d
    inputs[0], kernel, strides, padding, layout, out_dtype=out_dtype)
  File "<decorator-gen-36>", line 2, in conv2d
  File "/home/hls/Documents/MyWorkplace/sofeware/tvm/python/tvm/target.py", line 349, in dispatch_func
    return dispatch_dict[k](*args, **kwargs)
  File "/home/hls/Documents/MyWorkplace/sofeware/tvm/topi/python/topi/x86/conv2d.py", line 119, in _declaration_conv
    wkl = _get_workload(data, kernel, stride, padding, out_dtype)
  File "/home/hls/Documents/MyWorkplace/sofeware/tvm/topi/python/topi/nn/conv2d.py", line 79, in _get_workload
    _, CI, IH, IW = [x.value for x in data.shape]
ValueError: not enough values to unpack (expected 4, got 0)

**Comment by yzhliu** [comment]
Could you move this to [TVM Forum](https://discuss.tvm.ai) ? We are trying to make issue an actionable item and move general questions, discussions, RFC to the forum.

Also would you mind provide your test script? thanks.

**Comment by huanglishan6** [comment]
I had published first in TVM Forum, but nobody reply me.

**Comment by merrymercy** [comment]
You need to add more information rather just a trace back

**Comment by huanglishan6** [comment]
I had posted my code in [TVM Forum](https://discuss.tvm.ai/t/valueerror-not-enough-values-to-unpack-expected-4-got-0/744/3).
