### ISSUE TITLE
Got an error with from_tensorflow.py in the tutorials

### ISSUE THREAD

**Issue by hungbui-io** [dmlc/tvm#1971]
Hi all,
I have just started using TVM. However, after installing TVM, I got an error in running the script from_tensorflow.py in the tutorials :

Traceback (most recent call last):
  File "from_tensorflow.py", line 112, in <module>
    sym, params = nnvm.frontend.from_tensorflow(graph_def, layout=layout)
  File "/home/hung/projects/tvm/nnvm/python/nnvm/frontend/tensorflow.py", line 1371, in from_tensorflow
    sym, params = g.from_tensorflow(graph, layout)
  File "/home/hung/projects/tvm/nnvm/python/nnvm/frontend/tensorflow.py", line 1145, in from_tensorflow
    op = self._convert_operator(node.op, inputs, attr, graph)
  File "/home/hung/projects/tvm/nnvm/python/nnvm/frontend/tensorflow.py", line 1332, in _convert_operator
    sym = convert_map[op_name](inputs, attrs, self._params)
  File "/home/hung/projects/tvm/nnvm/python/nnvm/frontend/tensorflow.py", line 309, in _impl
    return AttrCvt(op_name='cast', transforms={'DstT': 'dtype'}, ignores=['SrcT'])(inputs, attr)
  File "/home/hung/projects/tvm/nnvm/python/nnvm/frontend/tensorflow.py", line 46, in __call__
    self._custom_check)(inputs, attrs, *args)
  File "/home/hung/projects/tvm/nnvm/python/nnvm/frontend/common.py", line 107, in __call__
    return get_nnvm_op(op_name)(*inputs, **new_attrs)
  File "/home/hung/projects/tvm/nnvm/python/nnvm/_ctypes/symbol.py", line 181, in creator
    ctypes.byref(sym_handle)))
  File "/home/hung/projects/tvm/nnvm/python/nnvm/_base.py", line 75, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: Cannot find argument 'Truncate', Possible Arguments:
----------------
dtype : {'float16', 'float32', 'float64', 'int16', 'int32', 'int64', 'int8', 'uint16', 'uint32', 'uint64', 'uint8'}, required
    Output data type.
, in operator cast(name="", dtype="float32", Truncate="False")

I am using Ubuntu 16.04, Tensorflow 1.11.0 with cpu. Any idea to fix this bug would be greatly appreciated!
Best,
Hung

**Comment by srkreddy1238** [comment]
https://github.com/dmlc/tvm/pull/1923

This should fix it.

**Comment by hungbui-io** [comment]
Hi @srkreddy1238 , thanks a lot for quick reply. However, I am able to run the same code (from_tensorflow.py) in a different PC. The only difference between 2 PCs is that the one that got the error, runs with cpu while the other runs with gpu.

**Comment by srkreddy1238** [comment]
Primary diff here is with the ```Truncate``` option for Cast operator which is added in recent versions.
I came across it recently, hence the above patch.

**Comment by tqchen** [comment]
Thanks for the healthy discussions, @hungbui-io please use https://discuss.tvm.ai/ for future questions
