### ISSUE TITLE
Can you please support Split and Slice as well? 

### ISSUE THREAD

**Issue by daweili1226** [dmlc/tvm#2099]
I mean our tensorflow frontend now doesn't support Gather now.

I see "take" operator is added to tvm already and nnvm operator for the same is pending.
We could use this to support Gather.

_Originally posted by @srkreddy1238 in https://github.com/dmlc/tvm/pull/1188#issuecomment-395296872_

**Comment by daweili1226** [comment]
Traceback (most recent call last):
  File "x.py", line 125, in <module>
    sym, params = nnvm.frontend.from_tensorflow(graph_def, layout=layout)
  File "/homed/lidw/tvm/nnvm/python/nnvm/frontend/tensorflow.py", line 1411, in from_tensorflow
    sym, params = g.from_tensorflow(graph, layout)
  File "/homed/lidw/tvm/nnvm/python/nnvm/frontend/tensorflow.py", line 1096, in from_tensorflow
    "The following operators are not implemented: {}".format(missing_operators))
NotImplementedError: The following operators are not implemented: set([u'Slice', u'Split'])
