### ISSUE TITLE
RPC socket received error

### ISSUE THREAD

**Issue by sqlin** [dmlc/tvm#2151]
Hi,
I try to run cross_compilation_and_rpc.py sample on arm device, but the RPC error happens, do someone meet this issue?

python3 cross_compilation_and_rpc.py
[03:55:56] /home/shiqin.lsq/tvm/src/runtime/opencl/opencl_device_api.cc:257: Initialize OpenCL platform 'NVIDIA CUDA'
[03:55:56] /home/shiqin.lsq/tvm/src/runtime/opencl/opencl_device_api.cc:288: opencl(0)='GeForce GTX 1080' cl_device_id=0x27b4a20
Traceback (most recent call last):
  File "cross_compilation_and_rpc.py", line 253, in <module>
    run_opencl()
  File "cross_compilation_and_rpc.py", line 223, in run_opencl
    remote = rpc.connect(opencl_device_host, opencl_device_port, key)
  File "/home/tvm/python/tvm/rpc/client.py", line 366, in connect
    sess = base._Connect(url, port, key)
  File "/home/tvm/python/tvm/_ffi/function.py", line 280, in my_api_func
    return flocal(*args)
  File "/home/tvm/python/tvm/_ffi/_ctypes/function.py", line 184, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/tvm/python/tvm/_ffi/base.py", line 66, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [03:55:56] /home/tvm/src/runtime/rpc/rpc_socket_impl.cc:58: Check failed: sock.RecvAll(&code, sizeof(code)) == sizeof(code) (0 vs. 4)

**Comment by tqchen** [comment]
Thanks for reporting this, please open a new thread at https://discuss.tvm.ai/
