### ISSUE TITLE
failed to run fpga example

### ISSUE THREAD

**Issue by hozen** [dmlc/tvm#2205]
ubuntu14.04_64
Python 3.6.2 :: Continuum Analytics, Inc.
LLVM version is clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-14.04/

Error happened while  I execute the demo: 
python <tvm root>/vta/tests/python/integration/test_benchmark_topi_conv2d.py

(notebooks) user@user:~/dmlc$ python tvm/vta/tests/python/integration/test_benchmark_topi_con
v2d.py
key=resnet-cfg[1]
Conv2DWorkload(batch=1, height=56, width=56, in_filter=64, out_filter=64, hkernel=3, wkernel=3, hpad=1, wpad=1, hstride=1, wstride=1)
----- CONV2D CPU End-to-End Test-------
Traceback (most recent call last):
  File "tvm/vta/tests/python/integration/test_benchmark_topi_conv2d.py", line 268, in <module>
    test_cpu_conv2d()
  File "tvm/vta/tests/python/integration/test_benchmark_topi_conv2d.py", line 134, in test_cpu_conv2d
    vta.testing.run(_run)
  File "/home/user/dmlc/tvm/vta/python/vta/testing/util.py", line 36, in run
    run_func(env, rpc.LocalSession())
  File "tvm/vta/tests/python/integration/test_benchmark_topi_conv2d.py", line 129, in _run
    run_cpu_conv2d(env, remote, key, batch_size, wl)
  File "tvm/vta/tests/python/integration/test_benchmark_topi_conv2d.py", line 103, in run_cpu_conv2d
    conv_normal(False)
  File "tvm/vta/tests/python/integration/test_benchmark_topi_conv2d.py", line 99, in conv_normal
    cost = verify(s, True)
  File "tvm/vta/tests/python/integration/test_benchmark_topi_conv2d.py", line 72, in verify
    f = remote.load_module("conv2d.o")
  File "/home/user/anaconda2/envs/notebooks/lib/python3.6/site-packages/tvm-0.5.dev0-py3.6-linux-x86_64.egg/tvm/rpc/client.py", line 191, in load_module
    return _load_module(self._temp.relpath(path))
  File "/home/user/anaconda2/envs/notebooks/lib/python3.6/site-packages/tvm-0.5.dev0-py3.6-linux-x86_64.egg/tvm/module.py", line 223, in load
    _cc.create_shared(path + ".so", path)
  File "/home/user/anaconda2/envs/notebooks/lib/python3.6/site-packages/tvm-0.5.dev0-py3.6-linux-x86_64.egg/tvm/contrib/cc.py", line 33, in create_shared
    _linux_shared(output, objects, options, cc)
  File "/home/user/anaconda2/envs/notebooks/lib/python3.6/site-packages/tvm-0.5.dev0-py3.6-linux-x86_64.egg/tvm/contrib/cc.py", line 58, in _linux_shared
    raise RuntimeError(msg)
RuntimeError: Compilation error:
/usr/bin/ld: /tmp/tmpdz_a3rw_/conv2d.o: relocation R_X86_64_32S against `.rodata.cst16' can not be used when making a shared object; recompile with -fPIC
/tmp/tmpdz_a3rw_/conv2d.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

**Comment by merrymercy** [comment]
It seems to be the llvm compatibility problem.

Solution here https://discuss.tvm.ai/t/solved-the-different-results-with-the-same-config/1238/2
