### ISSUE TITLE
[RELAY][PASS] AlterOpLayout handling for Tuple

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/tvm#2382]
```Traceback (most recent call last):
 File "./tests/python/frontend/tensorflow/test_forward.py", line 1060, in <module>
   test_forward_inception_v3()
 File "./tests/python/frontend/tensorflow/test_forward.py", line 701, in test_forward_inception_v3
   tvm_output = run_tvm_graph(graph_def, data, 'input')
 File "./tests/python/frontend/tensorflow/test_forward.py", line 60, in run_tvm_graph
   graph, lib, params = relay.build(sym, target, params=params)
 File "/home/srk/.local/lib/python3.6/site-packages/tvm-0.5.dev0-py3.6-linux-x86_64.egg/tvm/relay/build_module.py", line 227, in build
   func = ir_pass.infer_type(func)
 File "/home/srk/.local/lib/python3.6/site-packages/tvm-0.5.dev0-py3.6-linux-x86_64.egg/tvm/relay/ir_pass.py", line 44, in infer_type
   return _ir_pass.infer_type(expr, mod)
 File "/home/srk/.local/lib/python3.6/site-packages/tvm-0.5.dev0-py3.6-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 185, in __call__
   ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
 File "/home/srk/.local/lib/python3.6/site-packages/tvm-0.5.dev0-py3.6-linux-x86_64.egg/tvm/_ffi/base.py", line 72, in check_call
   raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [16:21:13] /home/srk/work/DMLC/tvm/src/relay/pass/type_infer.cc:317: the function is provided too many arguments (nullptr)
```

Tuple arguments not retained as Tuple after layout handling for operators like Concatenate.

**Comment by srkreddy1238** [comment]
#2383

**Comment by srkreddy1238** [comment]
#2536 fix this issue.
