### ISSUE TITLE
C/Python glue?

### ISSUE THREAD

**Issue by were** [dmlc/tvm#2409]
I am extending the schedule support to Hybrid Script.
I did something like `src/op/compute_op.{cc/h}`, which separates out some functions dedicated to hybrid schedule.
However, after doing that and recompiling the project.
````Python
import tvm
````
which may give me
````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weng/tvm-dev/tvm/python/tvm/__init__.py", line 5, in <module>
    from . import tensor
  File "/home/weng/tvm-dev/tvm/python/tvm/tensor.py", line 4, in <module>
    from ._ffi.node import NodeBase, NodeGeneric, register_node, convert_to_node
  File "~/tvm/python/tvm/_ffi/node.py", line 8, in <module>
    from .node_generic import NodeGeneric, convert_to_node, const
  File "~/tvm/python/tvm/_ffi/node_generic.py", line 7, in <module>
    from .base import string_types
  File "~/tvm/python/tvm/_ffi/base.py", line 49, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "~/tvm/python/tvm/_ffi/base.py", line 41, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError:~/tvm/build/libtvm.so: undefined symbol: _ZN3tvm2op14GatherLoopVarsEN8HalideIR8Internal4StmtE

````

**Comment by were** [comment]
@merrymercy @ZihengJiang @tqchen Any one can help me out?

**Comment by tqchen** [comment]
This usually was due to mismatch of signatures. I faced similar errors and eventually find it was because I declared the function as MyXYZ(Stmt xyz), but implemented it as MyXYZ(const Stmt& xyz);

Given that this is a general discussion and not in particularly actionable, I suggest we move it to discuss https://discuss.tvm.ai/
