### ISSUE TITLE
[Bug] tvm.exec.query_rpc_tracker timeout

### ISSUE THREAD

**Issue by tpoisonooo** [dmlc/tvm#2505]
[Problem]
I have checked [Android TVM Demo](https://github.com/tpoisonooo/tvm/tree/master/apps/android_rpc) and installed `tvmrpc-release.apk` on my Android device.

A process is listening `9190` on my macOS
```
➜  tmp python -m tvm.exec.rpc_tracker  --port 9190
INFO:root:If you are running ROCM/Metal, fork will cause compiler internal error. Try to launch with arg ```--no-fork```
INFO:RPCTracker:bind to 0.0.0.0:9190
```

But `tvm.exec.query_rpc_tracker` is always timeout.
```
➜  build git:(master) ✗ python -m tvm.exec.query_rpc_tracker --port 9190
WARNING:RPCServer:Cannot connect to tracker ('localhost', 9190), retry in 5 secs...
WARNING:RPCServer:Cannot connect to tracker ('localhost', 9190), retry in 5 secs...
WARNING:RPCServer:Cannot connect to tracker ('localhost', 9190), retry in 5 secs...
WARNING:RPCServer:Cannot connect to tracker ('localhost', 9190), retry in 5 secs...
WARNING:RPCServer:Cannot connect to tracker ('localhost', 9190), retry in 5 secs...
WARNING:RPCServer:Cannot connect to tracker ('localhost', 9190), retry in 5 secs...
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/huanjunkong/GitProjects/tvm/python/tvm/exec/query_rpc_tracker.py", line 32, in <module>
    main()
  File "/Users/huanjunkong/GitProjects/tvm/python/tvm/exec/query_rpc_tracker.py", line 26, in main
    conn = rpc.connect_tracker(args.host, args.port)
  File "/Users/huanjunkong/GitProjects/tvm/python/tvm/rpc/client.py", line 414, in connect_tracker
    return TrackerSession((url, port))
  File "/Users/huanjunkong/GitProjects/tvm/python/tvm/rpc/client.py", line 205, in __init__
    self._connect()
  File "/Users/huanjunkong/GitProjects/tvm/python/tvm/rpc/client.py", line 211, in _connect
    self._sock = base.connect_with_retry(self._addr)
  File "/Users/huanjunkong/GitProjects/tvm/python/tvm/rpc/base.py", line 159, in connect_with_retry
    "Failed to connect to server %s" % str(addr))
RuntimeError: Failed to connect to server ('localhost', 9190)
```

I have tried same command on Nvidia tx1, everything goes on well. It doesn't work on MacOS.

[Envrionment]
1. TVM version
```
git log
commit f397fead73bae20ca9abd2fc69df5723e065acde (HEAD -> master, origin/master, origin/HEAD)
```

2. network
```
AndroidPhone <---- WI-FI ----> Router <---- WIFI ----> tx1
                              |
                              |
                           WI-FI
                             |
                             |
                            macOS

AndroidPhone IP: 10.100.31.174
Nvidia tx1 IP        : 10.100.31.193
MacOS IP            : 10.100.31.156
```

**Comment by eqy** [comment]
I don't see a discuss board thread so I will respond here (if you want to continue this thread, please open a new thread there). I can reproduce the output you see, however I think it may be unrelated to tvm and just be an issue of how addresses are specified in macOS (maybe there is something weird with how `localhost` works or if there is some weird request filtering). I found that it works if I specify the local address of the machine (in your case `10.100.31.156`) explicitly. I hope this is a satisfying answer.
