### ISSUE TITLE
Incompatible attr in node elemwise_add0 at 1-th input: expected [1,256], got [256]

### ISSUE THREAD

**Issue by mnboos** [dmlc/tvm#2592]
The following problem occures when trying to load an ONNX model in a linux environment.

```
Traceback (most recent call last):
  File "compile_model.py", line 97, in <module>
    dtype=input_dtype_dict)
  File "/usr/tvm/nnvm/python/nnvm/compiler/build_module.py", line 270, in build
    ishape, _ = graph_util.infer_shape(graph, **shape)
  File "/usr/tvm/nnvm/python/nnvm/compiler/graph_util.py", line 31, in infer_shape
    graph = graph.apply("InferShape")
  File "/usr/tvm/nnvm/python/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/usr/tvm/nnvm/python/nnvm/_base.py", line 75, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: Error in operator elemwise_add0: [08:04:30] /usr/tvm/nnvm/src/top/nn/../elemwise_op_common.h:38: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node elemwise_add0 at 1-th input: expected [1,256], got [256]
```

**Comment by tqchen** [comment]
Thank you for bringing this up. Please open a new thread in https://discuss.tvm.ai/ and provide a bit more detail for reproduction of your problem.
