### ISSUE TITLE
AutoTVM x86 Tutorial is broken on MacOS

### ISSUE THREAD

**Issue by antinucleon** [dmlc/tvm#2617]
python tune_relay_x86.py
```
Extract tasks...
Tuning...
[Task  1/12]  Current/Best:    0.00/   0.00 GFLOPS | Progress: (0/400) | 0.00 sTraceback (most recent call last):
  File "tune_relay_x86.py", line 183, in <module>
    tune_and_evaluate(tuning_option)
  File "tune_relay_x86.py", line 157, in tune_and_evaluate
    tune_kernels(tasks, **tuning_opt)
  File "tune_relay_x86.py", line 142, in tune_kernels
    autotvm.callback.log_to_file(log_filename)])
  File "/Users/bingxu/tvm/python/tvm/autotvm/tuner/tuner.py", line 92, in tune
    measure_batch = create_measure_batch(self.task, measure_option)
  File "/Users/bingxu/tvm/python/tvm/autotvm/measure/measure.py", line 236, in create_measure_batch
    attach_objects = runner.set_task(task)
  File "/Users/bingxu/tvm/python/tvm/autotvm/measure/measure_methods.py", line 326, in set_task
    super(LocalRunner, self).set_task(task)
  File "/Users/bingxu/tvm/autotvm/measure/measure_methods.py", line 196, in set_task
    raise RuntimeError("Cannot get remote devices from the tracker. "
RuntimeError: Cannot get remote devices from the tracker. Please check the status of tracker by 'python -m tvm.exec.query_rpc_tracker --port [THE PORT YOU USE]' and make sure you have free devices on the queue status.
```

python -m tvm.exec.query_rpc_tracker --port 9000

```
Tracker address localhost:9000

Server List
----------------------------
server-address	key
----------------------------
::1:50954	server:$local$device$9000
----------------------------

Queue Status
------------------------------------------
key                  total  free  pending
------------------------------------------
$local$device$9000   1      0     1
------------------------------------------
```

**Comment by eqy** [comment]
I think we have seen this issue before, but I am not sure how we should fix it in the tutorial. Does the workaround of changing `localhost` to a real address such as `127.0.0.1` work for you? macOS seems to have many more network interfaces than other systems we have tried AutoTVM on, so maybe there is something strange when resolving `localhost`.
