### ISSUE TITLE
Cannot find global function tvm.relay._save_param_dict

### ISSUE THREAD

**Issue by sf-wind** [dmlc/tvm#2763]
Install TVM from source per https://docs.tvm.ai/install/from_source.html#build-the-shared-library. 

go into python prompt. It is fine to:

    import tvm

But I cannot do:

    from tvm import relay

(venv3.6) [ ~/speech_synthesis]# python
Python 3.6.8 (default, Mar  9 2019, 08:09:59)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tvm import relay
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/speech_synthesis/tvm/python/tvm/relay/__init__.py", line 16, in <module>
    from . import param_dict
  File "/root/speech_synthesis/tvm/python/tvm/relay/param_dict.py", line 5, in <module>
    _save_param_dict = tvm.get_global_func("tvm.relay._save_param_dict")
  File "/root/speech_synthesis/tvm/python/tvm/_ffi/function.py", line 213, in get_global_func
    raise ValueError("Cannot find global function %s" % name)
ValueError: Cannot find global function tvm.relay._save_param_dict
>>>

**Comment by sf-wind** [comment]
when listing all global functions using list_global_func_names(), it seems the function is registered as: '_save_param_dict'. It doesn't contain "tvm.relay. prefix"

**Comment by sf-wind** [comment]
It seems the problem is the tvm version. I had an older version of tvm. But I tried to install the python package using method 1 and 2. But both got the same error. 

However, if I ran the same import in tvm/build directory, I didn't get the error. It seemed that the correct tvm was used only in the build directory.

**Comment by sf-wind** [comment]
OK, the problem is that I need to run "make install" under the build directory, which is not specified in the instruction.
