### ISSUE TITLE
[TVM] Loop unroller tries to unroll a loop with a non-constant loop count and asserts

### ISSUE THREAD

**Issue by derisavi** [dmlc/tvm#2796]
Consider the following testcase:
```python
import tvm
n = tvm.var('n')
A = tvm.placeholder((n,), name='A')
B = tvm.compute((n,), lambda *i: A(*i), name='B')
s = tvm.create_schedule(B.op)

with tvm.build_config(auto_unroll_max_extent=1):
    tvm.lower(s, [A, B])
```
When we run this, we get the following error message:
```
Traceback (most recent call last):
  File "experiments/test4.py", line 8, in <module>
    tvm.lower(s, [A, B])
  File "/home/s00327669/work/tvm-fork/python/tvm/build_module.py", line 380, in lower
    cfg.unroll_explicit)
  File "tvm/_ffi/_cython/./function.pxi", line 286, in tvm._ffi._cy2.core.FunctionBase.__call__
  File "tvm/_ffi/_cython/./function.pxi", line 231, in tvm._ffi._cy2.core.FuncCall
  File "tvm/_ffi/_cython/./base.pxi", line 151, in tvm._ffi._cy2.core.CALL
tvm._ffi.base.TVMError: [15:43:53] /home/s00327669/work/tvm-fork/src/pass/unroll_loop.cc:131: Check failed: value != -1 (-1 vs. -1) loop doesn't have a constant integer extent

Stack trace returned 10 entries:
[bt] (0) /home/s00327669/work/tvm-fork/build/libtvm.so(+0x4265ec) [0x7febb0f1c5ec]
...
```

The problem is that unroller tries to unroll a loop without checking whether the loop count is constant.

**Comment by derisavi** [comment]
#2797 merged. Closing the issue.
