### ISSUE TITLE
can't deploy ssd with gluoncv

### ISSUE THREAD

**Issue by XiaotaoChen** [dmlc/tvm#2813]
I tried to deploy ssd with gluoncv according the [tvm docs](https://docs.tvm.ai/tutorials/frontend/deploy_ssd_gluoncv.html). I ran the source code file. The error infos as below.
```python
Traceback (most recent call last):
  File "deploy_ssd_gluoncv.py", line 105, in <module>
    graph, lib, params = compile(target)
  File "deploy_ssd_gluoncv.py", line 80, in compile
    net, params = relay.frontend.from_mxnet(block, {"data": dshape})
  File "/Users/cxt123/Reposities/tvm/python/tvm/relay/frontend/mxnet.py", line 612, in from_mxnet
    sym = _from_mxnet_impl(sym, shape, dtype)
  File "/Users/cxt123/Reposities/tvm/python/tvm/relay/frontend/mxnet.py", line 504, in _from_mxnet_impl
    jgraph = json.loads(symbol.tojson())
```
And here is the related code in `mxnet.py`:
```python
    if isinstance(symbol, mx.sym.Symbol):
        params = {}
        arg_params = arg_params if arg_params else {}
        aux_params = aux_params if aux_params else {}
        for k, v in arg_params.items():
            params[k] = _nd.array(v.asnumpy())
        for k, v in aux_params.items():
            params[k] = _nd.array(v.asnumpy())
        shape, dtype = _update_shape_dtype(shape, dtype, params)
        sym = _from_mxnet_impl(symbol, shape, dtype)
    elif isinstance(symbol, mx.gluon.HybridBlock):
        if arg_params is not None or aux_params is not None:
            raise ValueError("arg_params and aux_params ae not used when importing HybridBlock")
        params = {}
        for k, v in symbol.collect_params().items():
            params[k] = _nd.array(v.data().asnumpy())
        data = mx.sym.Variable("data")
        sym = symbol(data)
        shape, dtype = _update_shape_dtype(shape, dtype, params)
        sym = _from_mxnet_impl(sym, shape, dtype)

def _from_mxnet_impl(symbol, shape_dict, dtype_info):
    assert symbol is not None
    jgraph = json.loads(symbol.tojson())
    jnodes = jgraph["nodes"]
    node_map = {}

```
the root of this error is that `sym` is a tuple instead of symbol. It seems like there is a minor mistake when fetching symbol from hybrid block model. But i don't know how to fix it. 

my envs:
```shell
macOS: 10.14.3 
mxnet-mkl : 1.3
gluoncv: 0.3
tvm built from source commit id:  fd9fa4bf
```

**Comment by tqchen** [comment]
https://discuss.tvm.ai/t/cant-deploy-ssd-with-gluoncv/1916
