### ISSUE TITLE
[TVM][BUG] Conv2d_transpose error when running NNVM and Relay DCGAN benchmark

### ISSUE THREAD

**Issue by slyubomirsky** [dmlc/tvm#2826]
I have been trying to compile and run the DCGAN benchmark in `nnvm.testing` and `relay.testing` on my local CPU and GPU and have gotten error like those in the stack traces below when running it on random input in either NNVM or Relay on GPU. I do not know what the underlying issue is but it seems to be related to the schedule for `conv2d_transpose`. Note that I have compiled TVM with CUDA enabled and I have successfully been able to run other benchmarks that do not contain `conv2d_transponse` on both CPU and GPU.

Running DCGAN from `nnvm.testing` on opt level 1 on GPU (CUDA):
```
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:320: Return Everything in CombineInterval Mod
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:320: Return Everything in CombineInterval Mod
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:320: Return Everything in CombineInterval Mod
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:320: Return Everything in CombineInterval Mod
[12:34:01] /~/tvm/src/arithmetic/int_set.cc:320: Return Everything in CombineInterval Mod
Traceback (most recent call last):
  File "oopsla_benchmarks/nnvm/end2end_cnns_gpu.py", line 26, in <module>
    [networks, [device], batch_sizes, [num_batches], opt_levels])
  File "/~/relay-bench/oopsla_benchmarks/util/util.py", line 13, in run_experiments
    score = experiment(*args)
  File "/~/relay-bench/oopsla_benchmarks/nnvm/util/util.py", line 104, in score
    params=params, dtype='float32')
  File "/~/tvm/nnvm/python/nnvm/compiler/build_module.py", line 305, in build
    graph = graph.apply("GraphCompile")
  File "/~/tvm/nnvm/python/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/~/tvm/nnvm/python/nnvm/_base.py", line 75, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/~/tvm/nnvm/python/nnvm/compiler/build_module.py", line 107, in _lower
    f = tvm.lower(sch, inputs, name=func_name)
  File "/~/tvm/python/tvm/build_module.py", line 396, in lower
    return ir_pass.MakeAPI(stmt, name, arg_list, 0, cfg.restricted_func)
  File "/~/tvm/python/tvm/_ffi/_ctypes/function.py", line 185, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/~/tvm/python/tvm/_ffi/base.py", line 71, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [12:34:01] /~/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'blockIdx.y'  'blockIdx.x'  does not appeared in api_args

Stack trace returned 10 entries:
[bt] (0) /~/tvm/build/libtvm.so(+0x12e0cd) [0x7fe1db64f0cd]
[bt] (1) /~/tvm/build/libtvm.so(+0x12eaee) [0x7fe1db64faee]
[bt] (2) /~/tvm/build/libtvm.so(+0x337831) [0x7fe1db858831]
[bt] (3) /~/tvm/build/libtvm.so(+0x165a3a) [0x7fe1db686a3a]
[bt] (4) /~/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7fe1dbd843ae]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fe1de2d1dae]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7fe1de2d171f]
[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x4cd) [0x7fe1de511a4d]
[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x87b7) [0x7fe1de5087b7]
[bt] (9) python3(_PyObject_FastCallDict+0xa3) [0x45a0e3]



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/~/tvm/python/tvm/_ffi/_ctypes/function.py", line 55, in cfun
    rv = local_pyfunc(*pyargs)
  File "/~/tvm/nnvm/python/nnvm/compiler/build_module.py", line 115, in _lower
    raise RuntimeError(msg)
RuntimeError: Traceback (most recent call last):
  File "/~/tvm/nnvm/python/nnvm/compiler/build_module.py", line 107, in _lower
    f = tvm.lower(sch, inputs, name=func_name)
  File "/~/tvm/python/tvm/build_module.py", line 396, in lower
    return ir_pass.MakeAPI(stmt, name, arg_list, 0, cfg.restricted_func)
  File "/~/tvm/python/tvm/_ffi/_ctypes/function.py", line 185, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/~/tvm/python/tvm/_ffi/base.py", line 71, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [12:34:01] /~/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'blockIdx.y'  'blockIdx.x'  does not appeared in api_args

Stack trace returned 10 entries:
[bt] (0) /~/tvm/build/libtvm.so(+0x12e0cd) [0x7fe1db64f0cd]
[bt] (1) /~/tvm/build/libtvm.so(+0x12eaee) [0x7fe1db64faee]
[bt] (2) /~/tvm/build/libtvm.so(+0x337831) [0x7fe1db858831]
[bt] (3) /~/tvm/build/libtvm.so(+0x165a3a) [0x7fe1db686a3a]
[bt] (4) /~/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7fe1dbd843ae]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fe1de2d1dae]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7fe1de2d171f]
[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x4cd) [0x7fe1de511a4d]
[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x87b7) [0x7fe1de5087b7]
[bt] (9) python3(_PyObject_FastCallDict+0xa3) [0x45a0e3]


Error during compile graph
--------------------------
Graph(%input0,
      %input1,
      %input2,
      %input3,
      %input4) {
  %input0, shape=[1,1024,4,4]
  %input1, shape=[1024,512,4,4]
  %input2, shape=[512]
  %input3, shape=[512]
  %input4, shape=[512]
  %2 = conv2d_transpose(%input0, %input1, use_bias='False', padding='(1, 1)', kernel_size='(4, 4)', output_padding='(0, 0)', channels='512', strides='(2, 2)'), shape=[1,512,8,8]
  %4 = expand_dims(%input2, num_newaxis='2', axis='1'), shape=[512,1,1]
  %5 = broadcast_mul(%2, %4), shape=[1,512,8,8]
  %7 = negative(%input3), shape=[512]
  %8 = elemwise_mul(%7, %input2), shape=[512]
  %10 = elemwise_add(%8, %input4), shape=[512]
  %11 = expand_dims(%10, num_newaxis='2', axis='1'), shape=[512,1,1]
  %12 = broadcast_add(%5, %11), shape=[1,512,8,8]
  %13 = relu(%12), shape=[1,512,8,8]
  ret %13
}
graph_attr_keys = [dtype_num_unknown_nodes, dtype, shape, shape_num_unknown_nodes]
```

Running DCGAN from `relay.testing` on opt level 1 on GPU (CUDA):
```
WARNING:autotvm:Cannot find config for target=cuda, workload=('conv2d_transpose_nchw', (1, 128, 32, 32, 'float32'), (128, 3, 4, 4, 'float32'), (2, 2), (1, 1), 'float32'). A fallback configuration is used, which may bring great performance regression.
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:320: Return Everything in CombineInterval Mod
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:320: Return Everything in CombineInterval Mod
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:320: Return Everything in CombineInterval Mod
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:303: Return Everything in CombineInterval Div
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:320: Return Everything in CombineInterval Mod
[12:09:32] /~/tvm/src/arithmetic/int_set.cc:320: Return Everything in CombineInterval Mod
Traceback (most recent call last):
  File "/~/tvm/python/tvm/relay/backend/compile_engine.py", line 76, in lower
    return _backend._CompileEngineLower(self, key)
  File "/~/tvm/python/tvm/_ffi/_ctypes/function.py", line 185, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/~/tvm/python/tvm/_ffi/base.py", line 71, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/~/tvm/python/tvm/relay/backend/_backend.py", line 36, in lower
    f = _build.lower(sch, inputs, name=func_name)
  File "/~/tvm/python/tvm/build_module.py", line 396, in lower
    return ir_pass.MakeAPI(stmt, name, arg_list, 0, cfg.restricted_func)
  File "/~/tvm/python/tvm/_ffi/_ctypes/function.py", line 185, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/~/tvm/python/tvm/_ffi/base.py", line 71, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [12:09:32] /~/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'blockIdx.y'  'blockIdx.x'  does not appeared in api_args
Stack trace returned 10 entries:
[bt] (0) /~/tvm/build/libtvm.so(+0x12e0cd) [0x7fa8387510cd]
[bt] (1) /~/tvm/build/libtvm.so(+0x12eaee) [0x7fa838751aee]
[bt] (2) /~/tvm/build/libtvm.so(+0x337831) [0x7fa83895a831]
[bt] (3) /~/tvm/build/libtvm.so(+0x165a3a) [0x7fa838788a3a]
[bt] (4) /~/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7fa838e863ae]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fa83b3d3dae]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7fa83b3d371f]
[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x4cd) [0x7fa83b613a4d]
[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x87b7) [0x7fa83b60a7b7]
[bt] (9) python3(_PyObject_FastCallDict+0xa3) [0x45a0e3]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/~/tvm/python/tvm/_ffi/_ctypes/function.py", line 55, in cfun
    rv = local_pyfunc(*pyargs)
  File "/~/tvm/python/tvm/relay/backend/_backend.py", line 44, in lower
    raise RuntimeError(msg)
RuntimeError: Traceback (most recent call last):
  File "/~/tvm/python/tvm/relay/backend/_backend.py", line 36, in lower
    f = _build.lower(sch, inputs, name=func_name)
  File "/~/tvm/python/tvm/build_module.py", line 396, in lower
    return ir_pass.MakeAPI(stmt, name, arg_list, 0, cfg.restricted_func)
  File "/~/tvm/python/tvm/_ffi/_ctypes/function.py", line 185, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/~/tvm/python/tvm/_ffi/base.py", line 71, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [12:09:32] /~/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'blockIdx.y'  'blockIdx.x'  does not appeared in api_args
Stack trace returned 10 entries:
[bt] (0) /~/tvm/build/libtvm.so(+0x12e0cd) [0x7fa8387510cd]
[bt] (1) /~/tvm/build/libtvm.so(+0x12eaee) [0x7fa838751aee]
[bt] (2) /~/tvm/build/libtvm.so(+0x337831) [0x7fa83895a831]
[bt] (3) /~/tvm/build/libtvm.so(+0x165a3a) [0x7fa838788a3a]
[bt] (4) /~/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7fa838e863ae]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fa83b3d3dae]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7fa83b3d371f]
[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x4cd) [0x7fa83b613a4d]
[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x87b7) [0x7fa83b60a7b7]
[bt] (9) python3(_PyObject_FastCallDict+0xa3) [0x45a0e3]
Error during compile function
-----------------------------
fn (%p0: Tensor[(1, 128, 32, 32), float32],
    %p1: Tensor[(128, 3, 4, 4), float32])
    -> Tensor[(1, 3, 64, 64), float32] {
  %0 = nn.conv2d_transpose(%p0, %p1, channels=3, kernel_size=[4, 4], strides=[2, 2], padding=[1, 1]) # ty=Tensor[(1, 3, 64, 64), float32]
  %0
}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "oopsla_benchmarks/relay/end2end_cnns_gpu.py", line 26, in <module>
    [networks, [device], batch_sizes, [num_batches], opt_levels])
  File "/~/relay-bench/oopsla_benchmarks/util/util.py", line 13, in run_experiments
    score = experiment(*args)
  File "/~/relay-bench/oopsla_benchmarks/relay/util/util.py", line 101, in score
    graph, lib, params = relay.build(net, 'llvm' if dev == 'cpu' else 'cuda', params=params)
  File "/~/tvm/python/tvm/relay/build_module.py", line 276, in build
    graph_json, lowered_funcs, params = graph_gen.codegen(func)
  File "/~/tvm/python/tvm/relay/backend/graph_runtime_codegen.py", line 409, in codegen
    self.heads = self.visit(func.body)
  File "/~/tvm/python/tvm/relay/expr_functor.py", line 30, in visit
    res = self.visit_call(expr)
  File "/~/tvm/python/tvm/relay/backend/graph_runtime_codegen.py", line 270, in visit_call
    res = self.visit(arg)
  File "/~/tvm/python/tvm/relay/expr_functor.py", line 30, in visit
    res = self.visit_call(expr)
  File "/~/tvm/python/tvm/relay/backend/graph_runtime_codegen.py", line 260, in visit_call
    self.target[call_dev_type])
  File "/~/tvm/python/tvm/relay/backend/compile_engine.py", line 84, in lower
    raise RuntimeError(msg)
RuntimeError: Traceback (most recent call last):
  File "/~/tvm/python/tvm/relay/backend/compile_engine.py", line 76, in lower
    return _backend._CompileEngineLower(self, key)
  File "/~/tvm/python/tvm/_ffi/_ctypes/function.py", line 185, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/~/tvm/python/tvm/_ffi/base.py", line 71, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/~/tvm/python/tvm/relay/backend/_backend.py", line 36, in lower
    f = _build.lower(sch, inputs, name=func_name)
  File "/~/tvm/python/tvm/build_module.py", line 396, in lower
    return ir_pass.MakeAPI(stmt, name, arg_list, 0, cfg.restricted_func)
  File "/~/tvm/python/tvm/_ffi/_ctypes/function.py", line 185, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/~/tvm/python/tvm/_ffi/base.py", line 71, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [12:09:32] /~/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'blockIdx.y'  'blockIdx.x'  does not appeared in api_args
Stack trace returned 10 entries:
[bt] (0) /~/tvm/build/libtvm.so(+0x12e0cd) [0x7fa8387510cd]
[bt] (1) /~/tvm/build/libtvm.so(+0x12eaee) [0x7fa838751aee]
[bt] (2) /~/tvm/build/libtvm.so(+0x337831) [0x7fa83895a831]
[bt] (3) /~/tvm/build/libtvm.so(+0x165a3a) [0x7fa838788a3a]
[bt] (4) /~/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7fa838e863ae]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fa83b3d3dae]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7fa83b3d371f]
[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x4cd) [0x7fa83b613a4d]
[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x87b7) [0x7fa83b60a7b7]
[bt] (9) python3(_PyObject_FastCallDict+0xa3) [0x45a0e3]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/~/tvm/python/tvm/_ffi/_ctypes/function.py", line 55, in cfun
    rv = local_pyfunc(*pyargs)
  File "/~/tvm/python/tvm/relay/backend/_backend.py", line 44, in lower
    raise RuntimeError(msg)
RuntimeError: Traceback (most recent call last):
  File "/~/tvm/python/tvm/relay/backend/_backend.py", line 36, in lower
    f = _build.lower(sch, inputs, name=func_name)
  File "/~/tvm/python/tvm/build_module.py", line 396, in lower
    return ir_pass.MakeAPI(stmt, name, arg_list, 0, cfg.restricted_func)
  File "/~/tvm/python/tvm/_ffi/_ctypes/function.py", line 185, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/~/tvm/python/tvm/_ffi/base.py", line 71, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [12:09:32] /~/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'blockIdx.y'  'blockIdx.x'  does not appeared in api_args
Stack trace returned 10 entries:
[bt] (0) /~/tvm/build/libtvm.so(+0x12e0cd) [0x7fa8387510cd]
[bt] (1) /~/tvm/build/libtvm.so(+0x12eaee) [0x7fa838751aee]
[bt] (2) /~/tvm/build/libtvm.so(+0x337831) [0x7fa83895a831]
[bt] (3) /~/tvm/build/libtvm.so(+0x165a3a) [0x7fa838788a3a]
[bt] (4) /~/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7fa838e863ae]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fa83b3d3dae]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7fa83b3d371f]
[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x4cd) [0x7fa83b613a4d]
[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x87b7) [0x7fa83b60a7b7]
[bt] (9) python3(_PyObject_FastCallDict+0xa3) [0x45a0e3]
Error during compile function
-----------------------------
fn (%p0: Tensor[(1, 128, 32, 32), float32],
    %p1: Tensor[(128, 3, 4, 4), float32])
    -> Tensor[(1, 3, 64, 64), float32] {
  %0 = nn.conv2d_transpose(%p0, %p1, channels=3, kernel_size=[4, 4], strides=[2, 2], padding=[1, 1]) # ty=Tensor[(1, 3, 64, 64), float32]
  %0
}
Error during compile func
--------------------------
fn (%p0: Tensor[(1, 128, 32, 32), float32],
    %p1: Tensor[(128, 3, 4, 4), float32])
    -> Tensor[(1, 3, 64, 64), float32] {
  %0 = nn.conv2d_transpose(%p0, %p1, channels=3, kernel_size=[4, 4], strides=[2, 2], padding=[1, 1]) # ty=Tensor[(1, 3, 64, 64), float32]
  %0
}
--------------------------
```

**Comment by vinx13** [comment]
The fallback config is invalid in some cases. It should work after auto tuning.
