### ISSUE TITLE
[TEST][FLAKY][TOPI] test_topi_depthwise_conv2d.test_depthwise_conv2d

### ISSUE THREAD

**Issue by hlu1** [dmlc/tvm#2874]
```
======================================================================

ERROR: test_topi_depthwise_conv2d.test_depthwise_conv2d

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/workspace/topi/tests/python/test_topi_depthwise_conv2d.py", line 349, in test_depthwise_conv2d

    depthwise_conv2d_with_workload_NCHWc(1, 728, 32, 1, 3, 1, "SAME")

  File "/workspace/topi/tests/python/test_topi_depthwise_conv2d.py", line 316, in depthwise_conv2d_with_workload_NCHWc

    check_device(device)

  File "/workspace/topi/tests/python/test_topi_depthwise_conv2d.py", line 307, in check_device

    f1(input_tvm, filter_tvm, depthwise_conv2d_tvm)

  File "/workspace/python/tvm/_ffi/function.py", line 127, in __call__

    return f(*args)

  File "tvm/_ffi/_cython/./function.pxi", line 287, in tvm._ffi._cy2.core.FunctionBase.__call__

    FuncCall(self.chandle, args, &ret_val, &ret_tcode)

  File "tvm/_ffi/_cython/./function.pxi", line 222, in tvm._ffi._cy2.core.FuncCall

    FuncCall3(chandle, args, nargs, ret_val, ret_tcode)

  File "tvm/_ffi/_cython/./function.pxi", line 211, in tvm._ffi._cy2.core.FuncCall3

    CALL(TVMFuncCall(chandle, &values[0], &tcodes[0],

  File "tvm/_ffi/_cython/./base.pxi", line 151, in tvm._ffi._cy2.core.CALL

    raise get_last_ffi_error()

TVMError: Traceback (most recent call last):

  [bt] (1) /workspace/build/libtvm.so(TVMFuncCall+0x61) [0x7f4c50d000d1]

  [bt] (0) /workspace/build/libtvm.so(+0x8ec95c) [0x7f4c50d2695c]

  File "/workspace/src/runtime/module_util.cc", line 54

TVMError: Check failed: ret == 0 (-1 vs. 0) : Assert fail: (6 == tvm_struct_get(arg1, 0, 4)), arg1.ndim is expected to equal 6
```

http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-2873/1/pipeline

**Comment by tqchen** [comment]
This was due to caches of pickle of memoized files, has been fixed by cleaning up the cache in the CI
