### ISSUE TITLE
[Relay][ONNX] KeyError: 'W' when compiling from onnx

### ISSUE THREAD

**Issue by mnboos** [dmlc/tvm#2944]
The following error occurs when I try to compile an onnx model. From what I can tell using [Netron](https://lutzroeder.github.io/netron/), there is an input `W` but it's not another node but instead some (static) initialization data for the current node.

Unfortunately, I cannot attach the model because it's ca. 250MB.

```python
Traceback (most recent call last):
  File "/home/martin/Dev/Simpala/src/tvm/compile_model.py", line 141, in <module>
    compile_model(model_path=onnx_model_file, output_dir=target_directory)
  File "/home/martin/Dev/Simpala/src/tvm/compile_model.py", line 79, in compile_model
    relay_func, params = relay.frontend.from_onnx(onnx_model, shape=input_shape_dict)
  File "/home/martin/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/relay/frontend/onnx.py", line 1121, in from_onnx
    sym, params = g.from_onnx(graph, opset)
  File "/home/martin/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/relay/frontend/onnx.py", line 942, in from_onnx
    inputs = [self._nodes[self._renames.get(i, i)] for i in node.input]
  File "/home/martin/.local/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/relay/frontend/onnx.py", line 942, in <listcomp>
    inputs = [self._nodes[self._renames.get(i, i)] for i in node.input]
KeyError: 'W'
```

![2019-04-01 15_34_17-Window](https://user-images.githubusercontent.com/22575883/55331500-b24fa300-5493-11e9-9d0a-29317c4280db.png)

**Comment by tqchen** [comment]
Thanks for reporting this. Please dig a bit more into it and see if we can construct a minimum model that has this problem. In the meanwhile, feel free to start by opening a thread on https://discuss.tvm.ai/
