### ISSUE TITLE
[ONNX][OP] IndexError: list index out of range

### ISSUE THREAD

**Issue by Hkathuria** [dmlc/tvm#2970]
**nnvm.compiler.build** fails for onnx models with **Gemm Operation**. 

test script:

import nnvm
import tvm
import onnx
import numpy as np
import tensorflow as tf
onnx_model = onnx.load('gemm3.onnx')
sym, params = nnvm.frontend.from_onnx(onnx_model)
print("debug symbols:",sym.debug_str())
print("\n loading in nnvm done ")

Error Log :
Traceback (most recent call last):
  File "tvm_opencl_opt0gemm.py", line 13, in <module>
    sym, params = nnvm.frontend.from_onnx(onnx_model)
  File "/home/ubuntu/tvm_opencl/tvm/nnvm/python/nnvm/frontend/onnx.py", line 967, in from_onnx
    sym, params = g.from_onnx(graph, opset)
  File "/home/ubuntu/tvm_opencl/tvm/nnvm/python/nnvm/frontend/onnx.py", line 822, in from_onnx
    op = self._convert_operator(op_name, inputs, attr, opset)
  File "/home/ubuntu/tvm_opencl/tvm/nnvm/python/nnvm/frontend/onnx.py", line 923, in _convert_operator
    sym = convert_map[op_name](inputs, attrs, self._params)
  File "/home/ubuntu/tvm_opencl/tvm/nnvm/python/nnvm/frontend/onnx.py", line 183, in _impl_v1
    **channels = infer_channels(inputs[1], params, not transB)**
  File "/home/ubuntu/tvm_opencl/tvm/nnvm/python/nnvm/frontend/onnx_caffe2_utils.py", line 33, in infer_channels
    channels = out_shapes[0][0] if not transpose else out_shapes[0][1]
**IndexError: list index out of range**

**Comment by tqchen** [comment]
Thanks for reporting this, we encourage everyone to post in https://discuss.tvm.ai/ first and the community will follow up to do some collective diagnosis, once we confirm if there is something we need to act on, we can circle back to fix it
