### ISSUE TITLE
[BUG] Yolov3 GPU

### ISSUE THREAD

**Issue by jamessmith90** [dmlc/tvm#3023]
```
tvm._ffi.base.TVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/opt/github/tvm/python/tvm/_ffi/_ctypes/function.py", line 55, in cfun
    rv = local_pyfunc(*pyargs)
  File "/opt/github/tvm/python/tvm/autotvm/measure/measure_methods.py", line 557, in tvm_callback_cuda_compile
    ptx = nvcc.compile_cuda(code, target="ptx", arch=AutotvmGlobalScope.current.cuda_target_arch)
  File "/opt/github/tvm/python/tvm/contrib/nvcc.py", line 82, in compile_cuda
    raise RuntimeError(msg)
RuntimeError: Compilation error:
/tmp/tmpo0vygj4r/my_kernel.cu(758): error: identifier "inff" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00006c3b_00000000-6_my_kernel.cpp1.ii".

```

**Comment by ehsanmok** [comment]
Hi

Please first post in [discuss.tvm.ai](https://discuss.tvm.ai/) and provide more details of what you're doing. Currently it is not clear where the problem is.

**Comment by jamessmith90** [comment]
@ehsanmok 
I was trying to run the same model on yolov3-tiny and for that i had changed the 

```
elif MODEL_NAME == 'yolov3':
    for i in range(3):
```

to


```
elif MODEL_NAME == 'yolov3':
    for i in range(2):
```

This is running perfectly on cpu but not on gpu.

**Comment by cbalint13** [comment]
https://discuss.tvm.ai/t/opencl-mali-error-use-of-undeclared-identifier-inff/2270

**Comment by xiaoxifuhongse** [comment]
@jamessmith90 
I have the same problem , do you have work it out?
I try to convert darknet yolov3.weights to onnx then tvm to run　with CPU
