### ISSUE TITLE
NNVM suport for keras resnet50

### ISSUE THREAD

**Issue by zhangliwei06** [dmlc/tvm#3036]
keras_net = keras.applications.resnet50.ResNet50(include_top=True, weights=None,
                                                      input_shape=(224, 224, 3), classes=1000)
keras_net.load_weights('resnet50_weights.h5')
sym, params = nnvm.frontend.from_keras(keras_net)
sym = nnvm.graph.create(sym)
sym = vta.graph.clean_cast(sym)
sym = vta.graph.clean_conv_fuse(sym)

The error is reported:
Traceback (most recent call last):
  File "resnet.py", line 244, in <module>
    device)
  File "resnet.py", line 151, in generate_graph
    sym = vta.graph.clean_cast(sym)
  File "/home/nishome/lwzhang/tvm/vta/python/vta/graph.py", line 192, in clean_cast
    elif op_name == "conv2d" and attrs["out_dtype"] == "int32":
KeyError: 'out_dtype'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/home/nishome/lwzhang/tvm/python/tvm/_ffi/_ctypes/function.py", line 28, in _ctypes_free_resource
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/home/nishome/lwzhang/tvm/python/tvm/_ffi/_ctypes/function.py", line 28, in _ctypes_free_resource
TypeError: 'NoneType' object is not callable

 I print the sys.ir(), the conv2d node:
%4 = conv2d(%1, %_param_1, %_param_2, use_bias='True', dilation='[1, 1]', padding='[0, 0]', kernel_size='[7, 7]', channels='64', strides='[2, 2]')
It doesn's have the attribute "out_dtype".

How to fix this problem?
Thanks

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/
