### ISSUE TITLE
from onnx :SyntaxError: duplicate argument 'name' in function definition

### ISSUE THREAD

**Issue by petit-ami** [dmlc/tvm#3064]
Traceback (most recent call last):

  File "/export/userhome/liqiang/liqiang/Anaconda/ENTER/envs/tvm36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-3-a9420e0f6288>", line 4, in <module>
    import tvm.relay as relay

  File "/export/userhome/liqiang/liqiang/tvm/tvm/python/tvm/relay/__init__.py", line 28, in <module>
    from .build_module import build, build_config, create_executor, optimize

  File "/export/userhome/liqiang/liqiang/tvm/tvm/python/tvm/relay/build_module.py", line 30, in <module>
    from .backend import graph_runtime_codegen as _graph_gen

  File "/export/userhome/liqiang/liqiang/tvm/tvm/python/tvm/relay/backend/graph_runtime_codegen.py", line 72, in <module>
    class InputNode(Node):

  File "/export/userhome/liqiang/liqiang/Anaconda/ENTER/envs/tvm36/lib/python3.6/site-packages/attr/_make.py", line 200, in attributes
    return wrap(maybe_cl)

  File "/export/userhome/liqiang/liqiang/Anaconda/ENTER/envs/tvm36/lib/python3.6/site-packages/attr/_make.py", line 192, in wrap
    cl = _add_init(cl)

  File "/export/userhome/liqiang/liqiang/Anaconda/ENTER/envs/tvm36/lib/python3.6/site-packages/attr/_make.py", line 347, in _add_init
    bytecode = compile(script, unique_filename, "exec")

  File "<attrs generated init a3c753a2dac6f1d6b6946a70f000021113a58aa6>", line 1
SyntaxError: duplicate argument 'name' in function definition

it‘s from the tutorial ipynb, when I run it , the error come up
Has anyone came across this error before? please reply your suggestions for me?

@pluskid @ezyang @alexeyr @cnuernber @viirya @

**Comment by tqchen** [comment]
For this kind of community questions, please open a new thread on https://discuss.tvm.ai/
