### ISSUE TITLE
Win7 run error

### ISSUE THREAD

**Issue by luoqiuluoqiu** [dmlc/tvm#3080]
Environment: Win7 64
Python Version: Python 3.7
Code:
import tvm

n = 2
A = tvm.placeholder((n,), name='A')
B = tvm.placeholder((n,), name='B')
C = tvm.compute(A.shape, lambda *i: A(*i) + B(*i), name='C')
s = tvm.create_schedule(C.op)
f = tvm.lower(s, [A, B, C], name="test_add")
m = tvm.build(f, target="llvm")

error:
Traceback (most recent call last):
  File "D:/workplace/tcpython/TVM/tt.py", line 25, in <module>
    m = tvm.build(f, target="llvm")
  File "C:\Anaconda3\lib\site-packages\tvm-0.6.dev0-py3.6-win-amd64.egg\tvm\build_module.py", line 623, in build
    mhost = codegen.build_module(fhost_all, str(target_host))
  File "C:\Anaconda3\lib\site-packages\tvm-0.6.dev0-py3.6-win-amd64.egg\tvm\codegen.py", line 36, in build_module
    return _Build(lowered_func, target)
  File "C:\Anaconda3\lib\site-packages\tvm-0.6.dev0-py3.6-win-amd64.egg\tvm\_ffi\_ctypes\function.py", line 206, in __call__
    raise get_last_ffi_error()
  File "C:\Anaconda3\lib\site-packages\tvm-0.6.dev0-py3.6-win-amd64.egg\tvm\_ffi\base.py", line 297, in get_last_ffi_error
    if err_type.startswith("tvm.error."):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by tqchen** [comment]
Thanks for reporting this, usually we prefer to ask this kind of questions in https://discuss.tvm.ai/ please open a new thread there

**Comment by zjuwenge** [comment]
I have met the same error. Have you solved it?
