### ISSUE TITLE
TypeError when running the example to compile tensorflow models

### ISSUE THREAD

**Issue by unrahul** [dmlc/tvm#3122]
Downloaded and compiled TVM from master
Latest commit: ba6f194b54fbcd88372884acc6a2b722aed8343f
Tensorflow version: master
commit : 47ab68d265a96b6e7be06afd1b4b47e0114c0ee9

Ran the [compile tensorflow models example](https://docs.tvm.ai/_downloads/d910513238a8ce9e4a8592fbca16128d/from_tensorflow.py), after downloading the model and image file, I got an error: 

```bash
/workspace/tvm/python/tvm/relay/frontend/tensorflow.py:1720: UserWarning: Ignore the passed shape. Shape in graphdef will be used for operator DecodeJpeg/contents.
  "will be used for operator %s." % node.name)
/workspace/tvm/python/tvm/relay/frontend/tensorflow.py:448: UserWarning: DecodeJpeg: It's a pass through, please handle preprocessing before input
  warnings.warn("DecodeJpeg: It's a pass through, please handle preprocessing before input")
Traceback (most recent call last):
  File "from_tensorflow.py", line 128, in <module>
    sym, params = relay.frontend.from_tensorflow(graph_def, layout=layout, shape=shape_dict)
  File "/workspace/tvm/python/tvm/relay/frontend/tensorflow.py", line 2156, in from_tensorflow
    sym, params = g.from_tensorflow(graph, layout, shape, outputs)
  File "/workspace/tvm/python/tvm/relay/frontend/tensorflow.py", line 1804, in from_tensorflow
    op = self._convert_operator(node.op, inputs, attr, graph)
  File "/workspace/tvm/python/tvm/relay/frontend/tensorflow.py", line 2128, in _convert_operator
    sym = convert_map[op_name](inputs, attrs, self._params)
  File "/workspace/tvm/python/tvm/relay/frontend/tensorflow.py", line 474, in _impl
    extras={'method': "BILINEAR"})(inputs, attr)
  File "/workspace/tvm/python/tvm/relay/frontend/tensorflow.py", line 139, in __call__
    return _get_relay_op(op_name)(*inputs, **new_attrs)
TypeError: resize() got an unexpected keyword argument 'half_pixel_centers'

**Comment by tqchen** [comment]
It would be great if you can open a new thread in https://discuss.tvm.ai/, we encourage everyone to post on forum first :)
