### ISSUE TITLE
from ...cpp.image import bilinear_sample_nchw

### ISSUE THREAD

**Issue by jake221** [dmlc/tvm#3162]
Hi, 
I build tvm in CentOS 7 linux, with a llvm 6.0.1 prebuilt version( SUSE-12). And then everything goes fine in the python package installation. I also accelerate my face recognition model (insightface) from 320ms to 70ms in extracting face features for one face picture.

However, our manufacturing environment is SUSE-12 with out GPU. And there is no cmake in that linux. So I copy the built version from CentOS 7 system (i.e., the whole tvm folder and the llvm 6.0.1 prebulit version into SUSE-12. Everything still goes fine in the python package installation. However, when I import nnvm or topi, it report error as follows. Import tvm is successful.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/__init__.py", line 10, in <module>
    from . import frontend
  File "/usr/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/frontend/__init__.py", line 4, in <module>
    from .onnx import from_onnx
  File "/usr/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/frontend/onnx.py", line 24, in <module>
    from .onnx_caffe2_utils import dimension_picker, dimension_constraint, \
  File "/usr/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/frontend/onnx_caffe2_utils.py", line 20, in <module>
    from nnvm.compiler import graph_util
  File "/usr/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/__init__.py", line 19, in <module>
    from .. import top as _top
  File "/usr/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/top/__init__.py", line 6, in <module>
    from . import tensor
  File "/usr/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/top/tensor.py", line 22, in <module>
    import topi
  File "/home/wjk/tvm/topi/python/topi/__init__.py", line 25, in <module>
    from . import nn
  File "/home/wjk/tvm/topi/python/topi/nn/__init__.py", line 6, in <module>
    from .deformable_conv2d import *
  File "/home/wjk/tvm/topi/python/topi/nn/deformable_conv2d.py", line 23, in <module>
    from ..cpp.image import bilinear_sample_nchw
ImportError: cannot import name 'bilinear_sample_nchw'

**Comment by vinx13** [comment]
Can you try to figure out what's happening? FYI bilinear_sample_nchw is imported from C++ in https://github.com/dmlc/tvm/blob/95a323aaa148edb53f9308fd82d0d08638fdb0a4/topi/python/topi/cpp.py#L68

Please move discussion to  https://discuss.tvm.ai
