### ISSUE TITLE
After clean built 'tvm._ffi._ctypes.node.NodeBase' object has no attribute 'set_default'

### ISSUE THREAD

**Issue by sebap123** [dmlc/tvm#3170]
Once I've built TVM following guide from documentation I cannot run any example (tried so far tune_relay_x86.py and relay_quick_start.py).

I am getting all the time error
```
Traceback (most recent call last):
  File "tune_relay_x86.py", line 30, in <module>
    from tvm import relay
  File "/home/tvm_test/python/tvm/relay/__init__.py", line 24, in <module>
    from . import expr_functor
  File "/home/tvm_test/python/tvm/relay/expr_functor.py", line 24, in <module>
    from .op import Op
  File "/home/tvm_test/python/tvm/relay/op/__init__.py", line 20, in <module>
    from .op import get, register, register_schedule, register_compute, register_gradient, \
  File "/home/tvm_test/python/tvm/relay/op/op.py", line 19, in <module>
    import topi
  File "/home/tvm_test/topi/python/topi/__init__.py", line 25, in <module>
    from . import nn
  File "/home/tvm_test/topi/python/topi/nn/__init__.py", line 11, in <module>
    from .dense import *
  File "/home/tvm_test/topi/python/topi/nn/dense.py", line 65, in <module>
    def dense(data, weight, bias=None, out_dtype=None):
  File "/home/tvm_test/python/tvm/target.py", line 256, in fdecorate
    generic_func_node.set_default(fdefault, allow_override=True)
  File "/home/tvm_test/python/tvm/_ffi/_ctypes/node.py", line 75, in __getattr__
    "'%s' object has no attribute '%s'" % (str(type(self)), name))
AttributeError: '<class 'tvm._ffi._ctypes.node.NodeBase'>' object has no attribute 'set_default'
```
My believe is that environment variables are set correctly:
`export TVM_HOME=/home/tvm_test && export PYTHONPATH=$TVM_HOME/python:$TVM_HOME/topi/python:$TVM_HOME/nnvm/python:${PYTHONPATH}`
I'm running Python 3.6.7 if that helps.

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/ :)

**Comment by mshawcroft** [comment]
For the benefit of anyone tracking this down, this issue is discussed here:
https://discuss.tvm.ai/t/solved-after-clean-built-tvm-ffi-ctypes-node-nodebase-object-has-no-attribute-set-default/2521
