### ISSUE TITLE
[Relay] ImportError when running relay.fromtext()

### ISSUE THREAD

**Issue by alannnna** [dmlc/tvm#3265]
I'm getting an ImportError when I run relay.fromtext().

I installed TVM from source in an Ubuntu 16.04 Docker container. I'm running Python 3.5.2. I see the same problem with LLVM enabled and disabled. CUDA is not enabled.

Here is how to reproduce the problem, as well as the full error output:
```
In [1]: from tvm import relay

In [2]: relay.fromtext("test")
---------------------------------------------------------------------------
TVMError                                  Traceback (most recent call last)
<ipython-input-2-86c555b139f9> in <module>
----> 1 relay.fromtext("test")

/workspace/python/tvm/_ffi/_ctypes/function.py in __call__(self, *args)
    207                 self.handle, values, tcodes, ctypes.c_int(num_args),
    208                 ctypes.byref(ret_val), ctypes.byref(ret_tcode)) != 0:
--> 209             raise get_last_ffi_error()
    210         _ = temp_args
    211         _ = args

TVMError: Traceback (most recent call last):
  [bt] (1) /workspace/build/libtvm.so(TVMFuncCall+0x61) [0x7f32a8b7eb81]
  [bt] (0) /workspace/build/libtvm.so(+0x92ddfb) [0x7f32a8b79dfb]
  File "/workspace/python/tvm/_ffi/_ctypes/function.py", line 71, in cfun
    rv = local_pyfunc(*pyargs)
  File "/workspace/python/tvm/relay/parser.py", line 38, in fromtext
    from tvm.relay import _parser
  File "/workspace/python/tvm/relay/_parser.py", line 25, in <module>
    from typing import TypeVar, Deque, Tuple, Optional, Union, NamedTuple, List, Callable, Any, Dict
ImportError: cannot import name 'Deque'
```

**Comment by tqchen** [comment]
Thanks for reporting the problem, please open a new thread in  https://discuss.tvm.ai/ Likely this was due to python typing dependency. try to install python3.6

**Comment by alannnna** [comment]
Python 3.6 fixed it, so I won't open a new thread this time. Thanks.
