### ISSUE TITLE
[TEST][FLAKY]  test_topi_sort.test_topk

### ISSUE THREAD

**Issue by apivovarov** [dmlc/tvm#3358]
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3356/3/pipeline
```
======================================================================

FAIL: test_topi_sort.test_topk

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/workspace/topi/tests/python/test_topi_sort.py", line 103, in test_topk

    verify_topk(k, axis, ret_type, True, dtype)

  File "/workspace/topi/tests/python/test_topi_sort.py", line 96, in verify_topk

    check_device(device)

  File "/workspace/topi/tests/python/test_topi_sort.py", line 93, in check_device

    tvm.testing.assert_allclose(tvm_res[0].asnumpy(), np_indices)

  File "/workspace/python/tvm/testing.py", line 29, in assert_allclose

    np.testing.assert_allclose(actual, desired, rtol=rtol, atol=atol, verbose=True)

  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/nose_tools/utils.py", line 1398, in assert_allclose

    verbose=verbose, header=header, equal_nan=equal_nan)

  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/nose_tools/utils.py", line 781, in assert_array_compare

    raise AssertionError(msg)

AssertionError: 

Not equal to tolerance rtol=1e-07, atol=1e-07



(mismatch 0.09999999999999432%)

 x: array([[24., 20., 94., ..., 87., 34., 97.],

       [28., 99., 98., ...,  6., 21., 35.],

       [89., 43., 57., ..., 52., 14., 82.],...

 y: array([[24., 20., 94., ..., 87., 34., 97.],

       [28., 99., 98., ...,  6., 21., 35.],

       [89., 43., 57., ..., 52., 14., 82.],...

```

**Comment by tqchen** [comment]
cc @icemelon9

**Comment by icemelon9** [comment]
I'll fix it today.
