### ISSUE TITLE
[FLAKY] Vision : get_valid_counts

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/tvm#3396]
```
======================================================================

FAIL: test_topi_vision.test_get_valid_counts

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/workspace/topi/tests/python/test_topi_vision.py", line 77, in test_get_valid_counts

    verify_get_valid_counts((16, 500, 6), 0.95)

  File "/workspace/topi/tests/python/test_topi_vision.py", line 70, in verify_get_valid_counts

    check_device(device)

  File "/workspace/topi/tests/python/test_topi_vision.py", line 67, in check_device

    tvm.testing.assert_allclose(tvm_out2.asnumpy(), np_out2, rtol=1e-3)

  File "/workspace/python/tvm/testing.py", line 29, in assert_allclose

    np.testing.assert_allclose(actual, desired, rtol=rtol, atol=atol, verbose=True)

  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/nose_tools/utils.py", line 1398, in assert_allclose

    verbose=verbose, header=header, equal_nan=equal_nan)

  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/nose_tools/utils.py", line 781, in assert_array_compare

    raise AssertionError(msg)

AssertionError: 

Not equal to tolerance rtol=0.001, atol=1e-07



(mismatch 0.04999999999999716%)

 x: array([[[ 0.05017 ,  0.965635,  0.412649,  0.919446,  0.263663,

          0.197178],

        [ 0.695944,  0.988772,  0.165029,  0.670357,  0.475424,...

 y: array([[[ 0.05017 ,  0.965635,  0.412649,  0.919446,  0.263663,

          0.197178],

        [ 0.695944,  0.988772,  0.165029,  0.670357,  0.475424,...

-------------------- >> begin captured stdout << ---------------------
```

**Comment by tqchen** [comment]
Duplicate https://github.com/dmlc/tvm/issues/3142
