### ISSUE TITLE
ROCm apps/benchmark/gpu_imagenet.py failures loading kernel

### ISSUE THREAD

**Issue by mvermeulen** [dmlc/tvm#3486]
I have a configuration where TVM works for basic operations like the vector add case.  Will attach my dockerfile below.  However, running the benchmark script gives the following failure
```
prompt:/home/mev/source/tvm/apps/benchmark# python3 gpu_imagenet_bench.py --target=rocm --network=resnet-18 --model=gfx900
--------------------------------------------------
Network Name         Mean Inference Time (std dev)
--------------------------------------------------
...100%, 0.12 MB, 488 KB/s, 0 seconds passed
WARNING:autotvm:Cannot find config for target=rocm -model=gfx900, workload=('dense', (1, 512, 'float32'), (1000, 512, 'float32'), (1000, 'float32'), 0). A fallback configuration is used, which may bring great performance regression.
Traceback (most recent call last):
  File "gpu_imagenet_bench.py", line 86, in <module>
    benchmark(network, target)
  File "gpu_imagenet_bench.py", line 50, in benchmark
    prof_res = np.array(ftimer().results) * 1000  # multiply 1000 for converting to millisecond
  File "/usr/local/lib/python3.6/dist-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/module.py", line 194, in evaluator
    blob = feval(*args)
  File "/usr/local/lib/python3.6/dist-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 209, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (3) /usr/local/lib/python3.6/dist-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(TVMFuncCall+0x65) [0x7f33f93bc275]
  [bt] (2) /usr/local/lib/python3.6/dist-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::detail::PackFuncPackedArg_<4, tvm::runtime::ROCMWrappedFunc>(tvm::runtime::ROCMWrappedFunc, std::vector<tvm::runtime::detail::ArgConvertCode, std::allocator<tvm::runtime::detail::ArgConvertCode> > const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)+0x17) [0x7f33f9438a97]
  [bt] (1) /usr/local/lib/python3.6/dist-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::runtime::detail::PackFuncPackedArg_<4, tvm::runtime::ROCMWrappedFunc>(tvm::runtime::ROCMWrappedFunc, std::vector<tvm::runtime::detail::ArgConvertCode, std::allocator<tvm::runtime::detail::ArgConvertCode> > const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const+0x84f) [0x7f33f943888f]
  [bt] (0) /usr/local/lib/python3.6/dist-packages/tvm-0.6.dev0-py3.6-linux-x86_64.egg/tvm/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x43) [0x7f33f8b9f673]
  File "/src/tvm/src/runtime/rocm/rocm_module.cc", line 98
  File "/src/tvm/src/runtime/module_util.cc", line 73
ROCMError: Check failed: ret == 0 (-1 vs. 0) : hipModuleGetFunction fuse_broadcast_add_kernel0 failed with error: hipErrorNotFound
```

The error message suggests a kernel was never created and looking setting an environment variable HIP_TRACE_API=1 suggests that never getting to point of trying to load a module.  Not sure if this is a failed compilation or something more simple in the benchmark script.

Attached is the dockerfile.  Note that this builds LLVM from source and also fixes the code-object v2/v3 issues identified in issue #3058, and works for me on basic cases.
[rocm2.5-tvm.txt](https://github.com/dmlc/tvm/files/3355552/rocm2.5-tvm.txt)

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/
