### ISSUE TITLE
VTA MxNet tutorial broken

### ISSUE THREAD

**Issue by youn123** [dmlc/tvm#3539]
[VTA MxNet frontend compilation tutorial](https://docs.tvm.ai/vta/tutorials/frontend/deploy_resnet_on_vta.html#sphx-glr-vta-tutorials-frontend-deploy-resnet-on-vta-py) seems to be broken.

Produces this error:
`tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (8) /home/xilinx/packages/tvm/build/libtvm_runtime.so(+0x42b3e) [0xb59b7b3e]
  [bt] (7) /home/xilinx/packages/tvm/build/libtvm_runtime.so(+0x42960) [0xb59b7960]
  [bt] (6) /home/xilinx/packages/tvm/build/libtvm_runtime.so(+0x467d0) [0xb59bb7d0]
  [bt] (5) /home/xilinx/packages/tvm/build/libtvm_runtime.so(+0x462d2) [0xb59bb2d2]
  [bt] (4) /home/xilinx/packages/tvm/build/libtvm_runtime.so(+0x45604) [0xb59ba604]
  [bt] (3) /home/xilinx/packages/tvm/build/libtvm_runtime.so(+0x41290) [0xb59b6290]
  [bt] (2) /home/xilinx/packages/tvm/build/libtvm_runtime.so(+0x450cc) [0xb59ba0cc]
  [bt] (1) /home/xilinx/packages/tvm/build/libtvm_runtime.so(+0x41eb6) [0xb59b6eb6]
  [bt] (0) /home/xilinx/packages/tvm/build/libtvm_runtime.so(+0xaf2c) [0xb597ff2c]
  File "/home/xilinx/packages/tvm/python/tvm/_ffi/_ctypes/function.py", line 71, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/xilinx/packages/tvm/vta/python/vta/exec/rpc_server.py", line 60, in load_module
    return _load_module(file_name)
  File "/home/xilinx/packages/tvm/python/tvm/_ffi/_ctypes/function.py", line 206, in __call__
    raise get_last_ffi_error()
  [bt] (1) /home/xilinx/packages/tvm/build/libtvm_runtime.so(TVMFuncCall+0x37) [0xb5982334]
  [bt] (0) /home/xilinx/packages/tvm/build/libtvm_runtime.so(+0xaf2c) [0xb597ff2c]
  File "/home/xilinx/packages/tvm/python/tvm/_ffi/_ctypes/function.py", line 71, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/xilinx/packages/tvm/python/tvm/rpc/server.py", line 66, in load_module
    m = _load_module(path)
  File "/home/xilinx/packages/tvm/python/tvm/module.py", line 251, in load
    _cc.create_shared(path + ".so", path)
  File "/home/xilinx/packages/tvm/python/tvm/contrib/cc.py", line 49, in create_shared
    _linux_shared(output, objects, options, cc)
  File "/home/xilinx/packages/tvm/python/tvm/contrib/cc.py", line 106, in _linux_shared
    raise RuntimeError(msg)
TVMError: Except caught from RPC call: RuntimeError: Compilation error:
/tmp/tmpmvtr3gl8/graphlib.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status`

Expected: no error

**Comment by tqchen** [comment]
Please create a new thread on https://discuss.tvm.ai/
