### ISSUE TITLE
topi.mali.conv2d + autotvm issues

### ISSUE THREAD

**Issue by giuseros** [dmlc/tvm#3586]
Hi all,
I tried to use the forum, but I received no answers, so I thought to give a shot here.

I am going through the process of learning tvm, and what I want to do now is use a topi convolution (for Mali) and optimize it through the tuner.

This is the code that I am using:

```
@autotvm.template
def topi_conv(Wi, Hi, C, Ww, Hw, Nw):

    X = tvm.placeholder((1, Hi, Wi, C), name='X')
    W = tvm.placeholder((Hw, Ww, C, Nw), name='W')
    cfg = autotvm.get_config()
    print(cfg)
    out = topi.mali.conv2d(X, W, (1,1), 'SAME', (1,1), layout='NCHW')
    ts = topi.generic.schedule_conv2d_nchw(cfg, [out])

    return ts, [X, W, C]


task = autotvm.task.create(topi_conv, args=(N, M, C, n, m, num_filters), target=target, target_host=target_host)
```

But I am receiving the following error:
 ```
 return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/local/eclipse/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc/pydevd.py", line 1115, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/local/eclipse/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/giuros01/tvm_investigation/optimize_convolution_topi.py", line 34, in <module>
    task = autotvm.task.create(topi_conv, args=(N, M, C, n, m, num_filters), target=target, target_host=target_host)
  File "/home/giuros01/tvm/python/tvm/autotvm/task/task.py", line 191, in create
    sch, _ = func(*args)
  File "<decorator-gen-293>", line 2, in config_dispatcher
  File "/home/giuros01/tvm/python/tvm/autotvm/task/dispatcher.py", line 220, in dispatch_func
    return dispatch_dict[cfg.template_key](cfg, *args, **kwargs)
  File "/home/giuros01/tvm/python/tvm/autotvm/task/task.py", line 296, in template_call
    return func(*args, **kwargs)
  File "/home/giuros01/tvm_investigation/optimize_convolution_topi.py", line 28, in topi_conv
    out = topi.mali.conv2d(X, W, (1,1), 'SAME', (1,1), layout='NCHW')
  File "<decorator-gen-134>", line 2, in conv2d
  File "/home/giuros01/tvm/python/tvm/target.py", line 372, in dispatch_func
    return dispatch_dict[k](*args, **kwargs)
  File "<decorator-gen-281>", line 2, in config_dispatcher
  File "/home/giuros01/tvm/python/tvm/autotvm/task/dispatcher.py", line 220, in dispatch_func
    return dispatch_dict[cfg.template_key](cfg, *args, **kwargs)
KeyError: ''
```

Is there a problem in how the configuration gets built? 

Thanks for any help,
Giuseppe

**Comment by giuseros** [comment]
Some update on this: If I remove the @autotvm.template before the topi_conv function and pass a template_key='direct' when I create the task, it works. 

The problem is that now, when I build the function, I receive the message:

`Cannot find config for target=opencl -device=mali, workload=('conv2d', (1, 1024, 1024, 3, 'float32'), (3, 3, 3, 4, 'float32'), (1, 1), 'SAME', (1, 1), 'NCHW', 0). A fallback configuration is used, which may bring great performance regression.
`
Is this ok? I mean, is the topi operator inside topi_conv being tuned anyway?

Thanks,
Giuseppe

**Comment by vinx13** [comment]
You can use pre-registered tuning task in `topi_integration.py`:
```
env = topi_integration.TaskExtractEnv.get()
task.create('topi_nn_conv2d', ...)
```

**Comment by giuseros** [comment]
Hello @vinx13 ,
Thanks (a lot) for your reply. In this way, once it has been trained, how can I build the function?

Basically, in my previous example I used to do this:

```
    with tvm.target.create(target):
        s, arg_bufs = topi_conv(N, M, C, n, m, num_filters)
        func = tvm.build(s, arg_bufs, target=target, target_host=target_host)
        print(func)
```
What do I put instead of "s, args_buf = topi_conv"?

Thanks,
Giuseppe

**Comment by giuseros** [comment]
And I am also receiving an error:
```
Traceback (most recent call last):
  File "/home/giuros01/tvm_investigation/optimize_convolution_topi.py", line 46, in <module>
    autotvm.callback.log_to_file('convolution.log')])
  File "/home/giuros01/tvm/python/tvm/autotvm/tuner/xgboost_tuner.py", line 86, in tune
    super(XGBTuner, self).tune(*args, **kwargs)
  File "/home/giuros01/tvm/python/tvm/autotvm/tuner/tuner.py", line 152, in tune
    callback(self, inputs, results)
  File "/home/giuros01/tvm/python/tvm/autotvm/tuner/callback.py", line 50, in _callback
    f.write(record.encode(inp, result, protocol) + "\n")
  File "/home/giuros01/tvm/python/tvm/autotvm/record.py", line 103, in encode
    return json.dumps(json_dict)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Tensor(shape=[1, 1024, 1024, 3], op.name=X) is not JSON serializable
```
This is the code that I am running:
```
X = tvm.placeholder((1, N, M, C), name='X')
W = tvm.placeholder((n, m, C, num_filters), name='W')
args = [X, W, (1,1), 'SAME', (1,1), 'NCHW', 'float32']
env = autotvm.task.topi_integration.TaskExtractEnv.get()
task = autotvm.task.create('topi_nn_conv2d', args, target=target, target_host=target_host,template_key='direct')
# task = autotvm.task.create(topi_conv, args=(N, M, C, n, m, num_filters), target=target, target_host=target_host, template_key='direct')
# print(task)
measure_option = autotvm.measure_option(
    builder=autotvm.LocalBuilder(),
    runner=autotvm.RPCRunner(device_key, host=opencl_device_tracker, port=9190, number=5, timeout=5))
tuner = autotvm.tuner.XGBTuner(task)
# 
tuner.tune(n_trial=10,
           measure_option=measure_option,
           callbacks=[ autotvm.callback.progress_bar(10, prefix='convolution'),
                       autotvm.callback.log_to_file('convolution.log')])

```
Thanks again for any help,
Giuseppe

**Comment by giuseros** [comment]
Ok, the error has been sorted by calling autotvm.task.topi_integration.serialize_args, before passing the args to the task:
```

sargs = autotvm.task.topi_integration.serialize_args(args)
task = autotvm.task.create('topi_nn_conv2d', sargs, target=target, target_host=target_host,template_key='direct')
```

I am left with the question about how to build the function. 

Thanks again,
Giuseppe

**Comment by vinx13** [comment]
After you obtain tuning log, you can load your log with `apply_history_best` and build the func using your first snippet (invoke topi compute and schedule)

Let's move discussion to the forum.

**Comment by giuseros** [comment]
Sure, it is here: https://discuss.tvm.ai/t/topi-convolution/3405
