### ISSUE TITLE
how to solve "cannot match type handle64 vs int32"

### ISSUE THREAD

**Issue by melo19890618** [dmlc/tvm#3638]
I want to test roi-pooling,so i use the tvm/topi/python/topi/vision/rcnn/roi_pool.py like this:

import math
import te.lang.cce
from te import tvm
from topi import generic
from topi.cce import util
#from tvm.intrin import if_then_else
from topi.nn import pooling
import topi
from te.platform.cce_build import build_config
from topi.util import get_const_tuple
from topi.nn import softmax
import topi
#import topi.relay
#import topi.nn
#from tvm import relay
#from topi.relay import strided_slice
#from topi.relay import nn
#from tvm.intrin import if_then_elase
#from topi.vision.rcnn import roi_pool

@tvm.target.generic_func
def roi_pool_nchw(data,rois,pooled_size,spatial_scale):
    dtype=rois.dtype
    _,channel,height,width=get_const_tuple(data.shape)
    num_roi,_=get_const_tuple(rois.shape)
    if isinstance(pooled_size,int):
        pooled_size_h=pooled_size_w=pooled_size
    else:
        pooled_size_h,pooled_size_w=pooled_size
    def _pool(i,c,ph,pw):    
        roi=rois[i]
        batch_index=roi[0].astype('int32')
        roi_start_w, roi_start_h, roi_end_w, roi_end_h = roi[1], roi[2], roi[3], roi[4]
        
        roi_start_h = tvm.round(roi_start_h * spatial_scale).astype('int32')
        roi_start_w = tvm.round(roi_start_w * spatial_scale).astype('int32')
        roi_end_h = tvm.round(roi_end_h * spatial_scale).astype('int32')
        roi_end_w = tvm.round(roi_end_w * spatial_scale).astype('int32')
        
        roi_h = tvm.max(roi_end_h - roi_start_h + 1, tvm.const(1, 'int32'))
        roi_w = tvm.max(roi_end_w - roi_start_w + 1, tvm.const(1, 'int32'))

        bin_h = roi_h.astype(dtype) / pooled_size_h
        bin_w = roi_w.astype(dtype) / pooled_size_w
        
        epsilon = tvm.const(0.00001, dtype)
        hstart = tvm.floor(ph * bin_h + epsilon).astype('int32')
        wstart = tvm.floor(pw * bin_w + epsilon).astype('int32')
        hend = tvm.ceil((ph + 1) * bin_h - epsilon).astype('int32')
        wend = tvm.ceil((pw + 1) * bin_w - epsilon).astype('int32')
        hstart = tvm.min(tvm.max(hstart + roi_start_h, 0), height)
        wstart = tvm.min(tvm.max(wstart + roi_start_w, 0), width)
        hend = tvm.min(tvm.max(hend + roi_start_h, 0), height)
        wend = tvm.min(tvm.max(wend + roi_start_w, 0), width)
        non_empty=tvm.all(hstart<hend,wstart<wend)
        min_value=lambda dtype: tvm.expr.Select(non_empty,tvm.min_value(dtype),tvm.const(0.0,dtype))
        _max=tvm.comm_reducer(lambda x,y:tvm.make._OpMax(x,y),min_value,name='max')
        print(_max)
        #tvm.make._OpMax(x,y)
        rh=tvm.reduce_axis((0,hend-hstart),'rh')
        rw=tvm.reduce_axis((0,wend-wstart),'rw')
        return _max(data[batch_index,c,hstart+rh,wstart+rw],axis=[rh,rw])
    return tvm.compute((num_roi,channel,pooled_size_h,pooled_size_w),_pool,tag="pool,roi_pool")

def EasyTRROIpooling(shape1, shape2, dtype, kernel_name = "EasyTRROIpooling", need_build = True, need_print = False):
    util.check_kernel_name(kernel_name)
    util.check_shape_rule(shape1)
    util.check_shape_rule(shape2)
    check_list=["float16","float32"]
    if not (dtype.lower() in check_list):
        raise RuntimeError(
            "EasyTRROIpooling only support %s while dtype is %s" % (",".join(check_list), dtype))
    inp_dtype = dtype.lower()
    data_input = tvm.placeholder(shape1, name="data_input", dtype=inp_dtype)
    rois=tvm.placeholder(shape2,name="rois",dtype=inp_dtype)
    pooled_size_w=2
    pooled_size_h=2
    pooled_size=2
    spatial=1
    out=roi_pool_nchw(data_input,rois,2,1)
    s = tvm.create_schedule(out.op)
    with build_config:
        print tvm.lower(s, [data_input, rois, out], simple_mode=True)
        tvm.build(s, [data_input,rois, out], "cce", name=kernel_name)  
if __name__ == "__main__":
    EasyTRROIpooling((1,1,5,5), (1,5) ,"float16",kernel_name="EasyTRROIpooling")

when i run this code,the error like this:

Traceback (most recent call last):
  File "./operator/EasyTRROIpooling.py", line 112, in <module>
    EasyTRROIpooling((1,1,5,5), (1,5) ,"float16",kernel_name="EasyTRROIpooling")
  File "./operator/EasyTRROIpooling.py", line 109, in EasyTRROIpooling
    print tvm.lower(s, [data_input, rois, out], simple_mode=True)
  File "/home/HwHiAiUser/tools/che/ddk/ddk/site-packages/te-0.4.0-linux-x86_64.egg/te/tvm/build_module.py", line 268, in lower
    bounds = schedule.InferBound(sch)
  File "/home/HwHiAiUser/tools/che/ddk/ddk/site-packages/te-0.4.0-linux-x86_64.egg/te/tvm/_ffi/_ctypes/function.py", line 185, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/HwHiAiUser/tools/che/ddk/ddk/site-packages/te-0.4.0-linux-x86_64.egg/te/tvm/_ffi/base.py", line 68, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [16:10:58] src/lang/ir_operator.cc:70: Cannot match type handle64 vs int32

**Comment by cchung100m** [comment]
Hi @melo19890618 

Please open a new thread on https://discuss.tvm.ai/ The community uses the forum for general developer discussions.
