### ISSUE TITLE
ValueError: Donot know how to handle type object

### ISSUE THREAD

**Issue by ysh329** [dmlc/tvm#378]
Cross-compilation using remote device and local machine, server of remote device runs normally using `python -m tvm.exec.rpc_server --host 0.0.0.0 --port=9090`. 

After referring docs about [tvm.build](http://docs.tvmlang.org/api/python/build.html?highlight=tvm%20build#tvm.build), I'm still **not clear about second input args (args (list of Buffer or Tensor or Var, optional) – The argument lists to the function.) of `tvm.build` function**, which tensor should be as `args` (second arg of `tvm.build`) in GEMM example, all of them (A, B, C) or A and B ? 

## Error
When executing `cross_compilation_and_rpc.py` (edited as CPU GEMM example),  error message as below: 
```shell
yuens@Spark:~/Documents/charm/TVM_TRY$ python cross_compilation_and_rpc.py 
[19:46:46] src/codegen/llvm/codegen_llvm.cc:75: set native vector to be 32 for target aarch64
Traceback (most recent call last):
  File "cross_compilation_and_rpc.py", line 43, in <module>
    a = tvm.nd.array(a, ctx)
  File "/home/yuens/Software/tvm/python/tvm/ndarray.py", line 129, in array
    return empty(arr.shape, arr.dtype, ctx).copyfrom(arr)
  File "/home/yuens/Software/tvm/python/tvm/_ffi/ndarray.py", line 102, in empty
    dtype = TVMType(dtype)
  File "/home/yuens/Software/tvm/python/tvm/_ffi/runtime_ctypes.py", line 67, in __init__
    raise ValueError("Donot know how to handle type %s" % type_str)
ValueError: Donot know how to handle type object
```

## Code

```python
from __future__ import absolute_import, print_function
import tvm
import numpy as np
import numpy
from tvm.contrib import rpc, util

server = rpc.Server(host='0.0.0.0', port=9090)

# The size of the square matrix
N = 1024
# The default tensor type in tvm
dtype = "float32"
# Random generated tensor for testing
a = tvm.nd.array(numpy.random.rand(N, N).astype(dtype), tvm.cpu(0))
b = tvm.nd.array(numpy.random.rand(N, N).astype(dtype), tvm.cpu(0))
# The expected answer
answer = numpy.dot(a.asnumpy(), b.asnumpy())

# Algorithm
k = tvm.reduce_axis((0, N), 'k')
A = tvm.placeholder((N, N), name = 'A')
B = tvm.placeholder((N, N), name = 'B')
C = tvm.compute(
           A.shape,
           lambda x, y: tvm.sum(A[x, k] * B[k, y], axis = k),
           name = 'C')
# Default schedule
s = tvm.create_schedule(C.op)
func = tvm.build(s, [A, B, C], target='llvm -target=aarch64-linux-gnu -mcpu=cortex-a72 -mattr=+neon', name='myadd')
# save the lib at local temp folder
temp = util.tempdir()
path = temp.relpath('mylib.o')
func.save(path)

host = '192.168.1.56'
port = 9090
remote = rpc.connect(host, port)
remote.upload(path)
f = remote.load_module('mylib.o')

# create array on the remote device
ctx = remote.cpu(0)
a = tvm.nd.array(a, ctx)
b = tvm.nd.array(b, ctx)
c = tvm.nd.array(a, ctx)
# the function will run on the remote device
f(a, b, c)

# terminate the server after experiment
server.terminate()

```

**Comment by ysh329** [comment]
There's a problem about using `tvm.ndarray`. After modified as below, it's fixed.
```python
a = tvm.nd.array(a.asnumpy().astype(dtype), ctx)
b = tvm.nd.array(b.asnumpy().astype(dtype), ctx)
c = tvm.nd.array(c.asnumpy().astype(dtype), ctx)
```
