### ISSUE TITLE
[RELAY][TOPI] TVMError: Attribute FTVMCompute of operator nn.upsampling is already registered with same plevel=10

### ISSUE THREAD

**Issue by cchung100m** [dmlc/tvm#3820]
Hi @jwfromm @masahi @tqchen @vinx13 @FrozenGene 

I run the `tflite/test_forward.py` from the latest tvm master branch and get the following error message, I guess it might be associated with PR #3788, I would appreciate if you could help to take a look, thanks. 

```
Traceback (most recent call last):

  File "/Users/root/Downloads/tvm/tests/python/frontend/tflite/test_forward.py", line 27, in <module>
    from tvm import relay

  File "/Users/root/Downloads/tvm/python/tvm/relay/__init__.py", line 24, in <module>
    from . import expr_functor

  File "/Users/root/Downloads/tvm/python/tvm/relay/expr_functor.py", line 24, in <module>
    from .op import Op

  File "/Users/root/Downloads/tvm/python/tvm/relay/op/__init__.py", line 29, in <module>
    from . import nn

  File "/Users/root/Downloads/tvm/python/tvm/relay/op/nn/__init__.py", line 21, in <module>
    from . import _nn

  File "/Users/root/Downloads/tvm/python/tvm/relay/op/nn/_nn.py", line 379, in <module>
    @reg.register_compute("nn.upsampling")

  File "/Users/root/Downloads/tvm/python/tvm/relay/op/op.py", line 93, in _register
    _Register(op_name, attr_key, v, level)

  File "/Users/root/Downloads/tvm/python/tvm/_ffi/_ctypes/function.py", line 210, in __call__
    raise get_last_ffi_error()

tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (6) 7   ???                                 0x00007fff5ec29d40 0x0 + 140734783200576
  [bt] (5) 6   _ctypes.cpython-35m-darwin.so       0x000000010b9ee7af ffi_call_unix64 + 79
  [bt] (4) 5   libtvm.dylib                        0x000000010df838d8 TVMFuncCall + 72
  [bt] (3) 4   libtvm.dylib                        0x000000010db8980c std::__1::__function::__func<tvm::relay::$_2, std::__1::allocator<tvm::relay::$_2>, void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::operator()(tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) + 1452
  [bt] (2) 3   libtvm.dylib                        0x000000010db89b4a tvm::relay::OpRegistry& tvm::relay::OpRegistry::set_attr<tvm::runtime::PackedFunc>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tvm::runtime::PackedFunc const&, int) + 474
  [bt] (1) 2   libtvm.dylib                        0x000000010db863d8 tvm::relay::OpRegistry::UpdateAttr(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tvm::runtime::TVMRetValue, int) + 1000
  [bt] (0) 1   libtvm.dylib                        0x000000010d655279 dmlc::LogMessageFatal::~LogMessageFatal() + 57
  File "/Users/root/Downloads/tvm/src/relay/ir/op.cc", line 102
TVMError: Check failed: p.second != plevel: Attribute FTVMCompute of operator nn.upsampling is already registered with same plevel=10


Process finished with exit code 1
```

**Comment by masahi** [comment]
You need to rebuild tvm dll. Try make clean and rebuild.

**Comment by cchung100m** [comment]
Hi @masahi 

Thank you for the prompt reply! I solve it by rebuilding the tvm. :)
