### ISSUE TITLE
precision problem about GEMM example

### ISSUE THREAD

**Issue by ysh329** [dmlc/tvm#383]
Following tutorial CPU GEMM, I ran this demo using cross-compilation on Cortex-A72 and my local machine. But it seems have a precision problem about decimal part as below:

```shell
yuens@Spark:~/Documents/charm/TVM_TRY$ python cross_compilation_and_rpc.py
[11:02:53] src/codegen/llvm/codegen_llvm.cc:75: set native vector to be 32 for target aarch64
Traceback (most recent call last):
  File "cross_compilation_and_rpc.py", line 49, in <module>
    np.testing.assert_equal(c.asnumpy(), answer)
  File "/usr/local/lib/anaconda2/lib/python2.7/site-packages/numpy/testing/utils.py", line 322, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/usr/local/lib/anaconda2/lib/python2.7/site-packages/numpy/testing/utils.py", line 813, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/anaconda2/lib/python2.7/site-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 92.1112060547%)
 x: array([[ 247.566803,  256.043182,  244.30249 , ...,  252.350616,
         254.953583,  243.431519],
       [ 250.601807,  253.233948,  239.882767, ...,  246.857391,...
 y: array([[ 247.566772,  256.042938,  244.302505, ...,  252.350739,
         254.953506,  243.431747],
       [ 250.601807,  253.233917,  239.882919, ...,  246.857468,...

```
## Code

I defined `dtype=“float32”` for `a`, `b` and `c`.

```python
from __future__ import absolute_import, print_function
import tvm
import numpy as np
import numpy
from tvm.contrib import rpc, util

server = rpc.Server(host='0.0.0.0', port=9090)

# The size of the square matrix
N = 1024
# The default tensor type in tvm
dtype = "float32"
# Random generated tensor for testing
a = tvm.nd.array(numpy.random.rand(N, N).astype(dtype), tvm.cpu(0))
b = tvm.nd.array(numpy.random.rand(N, N).astype(dtype), tvm.cpu(0))
c = tvm.nd.array(numpy.zeros(shape=[N,N], dtype=dtype), tvm.cpu(0))
# The expected answer
answer = numpy.dot(a.asnumpy(), b.asnumpy())

# Algorithm
k = tvm.reduce_axis((0, N), 'k')
A = tvm.placeholder((N, N), name = 'A')
B = tvm.placeholder((N, N), name = 'B')
C = tvm.compute(
           A.shape,
           lambda x, y: tvm.sum(A[x, k] * B[k, y], axis = k),
           name = 'C')
# Default schedule
s = tvm.create_schedule(C.op)
func = tvm.build(s, [A, B, C], target='llvm -target=aarch64-linux-gnu -mcpu=cortex-a72 -mattr=+neon', name='mmult')
# save the lib at local temp folder
temp = util.tempdir()
path = temp.relpath('mylib.o')
func.save(path)

host = '192.168.1.56'
port = 9090
remote = rpc.connect(host, port)
remote.upload(path)
f = remote.load_module('mylib.o')

# create array on the remote device
ctx = remote.cpu(0)
a = tvm.nd.array(a.asnumpy().astype(dtype), ctx)
b = tvm.nd.array(b.asnumpy().astype(dtype), ctx)
c = tvm.nd.array(c.asnumpy().astype(dtype), ctx)
# the function will run on the remote device
f(a, b, c)
#np.testing.assert_equal(c.asnumpy(), answer)

time_f = f.time_evaluator(f.entry_name, ctx, number=1)
cost = time_f(a, b).mean
print('%g secs/op' % cost)

# terminate the server after experiment
server.terminate()
```

**Comment by tqchen** [comment]
the default rtol of numpy is quite high, consider use a bigger rtol to, use assert_allcose with rtol

**Comment by were** [comment]
@tqchen I faced the similiar problem. For the default schedule, the test passed, but after applying several optimizations, I have to release the eps to pass `numpy.testing.assert_allclose`.

**Comment by tqchen** [comment]
It is possible, because the summation order becomes different so the exact number may not match exactly

**Comment by were** [comment]
Yeah, I know. It is caused by the mechanism of float point add.

**Comment by tqchen** [comment]
I think it is a non-ssue, should use numpy.testing.assert_allclose with released rtol
