### ISSUE TITLE
Jenkins git issue - corrupt repository

### ISSUE THREAD

**Issue by apivovarov** [dmlc/tvm#3847]
I submitted new PR but got the following error from Jenkins
http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-3846/1/pipeline

```
> git rev-parse --is-inside-work-tree # timeout=10

ERROR: Workspace has a .git repository, but it appears to be corrupt.

hudson.plugins.git.GitException: Command "git rev-parse --is-inside-work-tree" returned status code 128:

stdout: 

stderr: fatal: Not a git repository (or any parent up to mount point /scratch)

Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).



	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2016)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1984)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1980)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1612)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1624)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.hasGitRepo(CliGitAPIImpl.java:282)

	at hudson.plugins.git.GitAPI.hasGitRepo(GitAPI.java:232)

	at sun.reflect.GeneratedMethodAccessor619.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:929)

	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:903)

	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:855)

	at hudson.remoting.UserRequest.perform(UserRequest.java:212)

	at hudson.remoting.UserRequest.perform(UserRequest.java:54)

	at hudson.remoting.Request$2.run(Request.java:369)

	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)

	at java.lang.Thread.run(Thread.java:748)

Cloning the remote Git repository

Cloning with configured refspecs honoured and without tags

Cloning repository https://github.com/dmlc/tvm.git

 > git init /scratch/jenkins-tvm/cpu/workspace/tvm/sanity # timeout=10

ERROR: Timeout after 10 minutes

ERROR: Error cloning remote repo 'origin'

hudson.plugins.git.GitException: Could not init /scratch/jenkins-tvm/cpu/workspace/tvm/sanity

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:787)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:579)

	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)

	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)

	at hudson.remoting.UserRequest.perform(UserRequest.java:212)

	at hudson.remoting.UserRequest.perform(UserRequest.java:54)

	at hudson.remoting.Request$2.run(Request.java:369)

	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)

	at java.lang.Thread.run(Thread.java:748)

	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from sampa-lab.cs.washington.edu/128.208.6.198:51014

		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)

		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)

		at hudson.remoting.Channel.call(Channel.java:955)

		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)

		at sun.reflect.GeneratedMethodAccessor9958.invoke(Unknown Source)

		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

		at java.lang.reflect.Method.invoke(Method.java:498)

		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)

		at com.sun.proxy.$Proxy101.execute(Unknown Source)

		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)

		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)

		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)

		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)

		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)

		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)

		at hudson.security.ACL.impersonate(ACL.java:290)

		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)

		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

		at java.util.concurrent.FutureTask.run(FutureTask.java:266)

		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

		... 1 more

Caused by: hudson.plugins.git.GitException: Command "git init /scratch/jenkins-tvm/cpu/workspace/tvm/sanity" returned status code 143:

stdout: 

stderr: 

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2016)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1984)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1980)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1612)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:785)

	... 12 more

Error cloning remote repo 'origin'
```

**Comment by tqchen** [comment]
Fixed
