### ISSUE TITLE
TVM fails on the following conv2d with given template

### ISSUE THREAD

**Issue by zhiics** [dmlc/tvm#3998]
given fail.log:
{"i": ["cuda -model=unknown", "topi_nn_conv2d", [["TENSOR", [1, 128, 64, 64], "float32"], ["TENSOR", [128, 128, 3, 3], "float32"], [1, 1], [1, 1], [1, 1], "NCHW", "float32"], {}, ["conv2d", [1, 128, 64, 64, "float32"], [128, 128, 3, 3, "float32"], [1, 1], [1, 1], [1, 1], "NCHW", "float32"], {"i": 64299, "t": "winograd", "c": null, "e": [["tile_b", "sp", [36, 1, 1, 1]], ["tile_y", "sp", [1, 1, 16, 8]], ["tile_x", "sp", [2, 2, 64, 1]], ["tile_rc", "sp", [16, 8]], ["auto_unroll_max_step", "ot", 0], ["unroll_explicit", "ot", 0]]}], "r": [[6.145241264250032e-05], 0, 7.176635265350342, 1558889275.24545], "v": 0.1}

The following script fails:

```python
import tvm
from tvm import relay

d = relay.var('d', shape=(1, 128, 64, 64), dtype="float32")
w = relay.var('w', shape=(128, 128, 3, 3), dtype="float32")

conv = relay.nn.conv2d(d, w, padding=[1, 1], channels=128, kernel_size=[3, 3])
mod = relay.Module.from_expr(conv)

params = {}

with tvm.autotvm.apply_history_best("/home/ubuntu/log/fail.log"):
    with relay.build_config(opt_level=3):
        graph, lib, params = relay.build(mod, "cuda", params=params)
```
with the following error:

```
[06:47:13] /home/ubuntu/tvm/src/pass/loop_partition.cc:545: Cannot prove: ((((((((((((blockIdx.x*128) + threadIdx.x) % 256)/16)*16) + (threadIdx.x % 16)) + 1) - (((blockIdx.x*128) + threadIdx.x) % 256)) - 1) - 1) + 1) >= 0), when generating the post doubt loop
[06:47:14] /home/ubuntu/tvm/src/relay/ir/doc.h:51: text node: '{
  "root": 1,
  "nodes": [
   {
    "type_key": ""
   },
   {
    "type_key": "StrMap",
    "keys": [
     "relay.attrs.Conv2DWinogradAttrs"
    ],
    "data": [2]
   },
   {
    "type_key": "Array",
    "data": [3]
   },
   {
    "type_key": "relay.attrs.Conv2DWinogradAttrs",
    "attrs": {
     "channels": "13",
     "data_layout": "NCHW",
     "dilation": "10",
     "groups": "1",
     "kernel_layout": "OIHW",
     "kernel_size": "14",
     "out_dtype": "",
     "out_layout": "",
     "padding": "7",
     "strides": "4",
     "tile_size": "4"
    }
   },
   {
    "type_key": "Array",
    "data": [5, 6]
   },
   {
    "type_key": "IntImm",
    "attrs": {
     "dtype": "int32",
     "value": "1"
    }
   },
   {
    "type_key": "IntImm",
    "attrs": {
     "dtype": "int32",
     "value": "1"
    }
   },
   {
    "type_key": "Array",
    "data": [8, 9]
   },
   {
    "type_key": "IntImm",
    "attrs": {
     "dtype": "int32",
     "value": "1"
    }
   },
   {
    "type_key": "IntImm",
    "attrs": {
     "dtype": "int32",
     "value": "1"
    }
   },
   {
    "type_key": "Array",
    "data": [11, 12]
   },
   {
    "type_key": "IntImm",
    "attrs": {
     "dtype": "int32",
     "value": "1"
    }
   },
   {
    "type_key": "IntImm",
    "attrs": {
     "dtype": "int32",
     "value": "1"
    }
   },
   {
    "type_key": "IntImm",
    "attrs": {
     "dtype": "int32",
     "value": "128"
    }
   },
   {
    "type_key": "Array",
    "data": [15, 16]
   },
   {
    "type_key": "IntImm",
    "attrs": {
     "dtype": "int32",
     "value": "3"
    }
   },
   {
    "type_key": "IntImm",
    "attrs": {
     "dtype": "int32",
     "value": "3"
    }
   }
  ],
  "b64ndarrays": [],
  "attrs": {"tvm_version": "0.6.dev"}
}' should not has tab or newline.

Traceback (most recent call last):

  File "/home/ubuntu/log/repo.py", line 16, in <module>
   graph, lib, params = relay.build(mod, "cuda", params=params)

  File "/home/ubuntu/tvm/python/tvm/relay/build_module.py", line 207, in build
   graph_json, mod, params = bld_mod.build(func, target, target_host, params)

  File "/home/ubuntu/tvm/python/tvm/relay/build_module.py", line 108, in build
   self._build(func, target, target_host)

  File "/home/ubuntu/tvm/python/tvm/_ffi/_ctypes/function.py", line 210, in __call__
   raise get_last_ffi_error()

tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (8) /home/ubuntu/tvm/build/libtvm.so(tvm::relay::backend::RelayBuildModule::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<tvm::runtime::ModuleNode> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#3}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const+0x254) [0x7feeed17fb74]
  [bt] (7) /home/ubuntu/tvm/build/libtvm.so(tvm::relay::backend::RelayBuildModule::BuildRelay(tvm::relay::Function, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::NDArray, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, tvm::runtime::NDArray> > > const&)+0x73a) [0x7feeed17f04a]
  [bt] (6) /home/ubuntu/tvm/build/libtvm.so(std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::relay::backend::GraphRuntimeCodegenModule::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<tvm::runtime::ModuleNode> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)+0x8b) [0x7feeed1b1fdb]
  [bt] (5) /home/ubuntu/tvm/build/libtvm.so(tvm::relay::backend::GraphRuntimeCodegen::Codegen(tvm::relay::Function)+0x68d) [0x7feeed1b123d]
  [bt] (4) /home/ubuntu/tvm/build/libtvm.so(tvm::relay::backend::GraphRuntimeCodegen::VisitExpr(tvm::relay::Expr const&)+0x566) [0x7feeed1a6586]
  [bt] (3) /home/ubuntu/tvm/build/libtvm.so(tvm::relay::backend::GraphRuntimeCodegen::VisitExpr_(tvm::relay::CallNode const*)+0x6a9) [0x7feeed1acbe9]
  [bt] (2) /home/ubuntu/tvm/build/libtvm.so(+0x104126c) [0x7feeed18126c]
  [bt] (1) /home/ubuntu/tvm/build/libtvm.so(tvm::relay::CompileEngineImpl::LowerInternal(tvm::relay::CCacheKey const&)+0x872) [0x7feeed18c222]
  [bt] (0) /home/ubuntu/tvm/build/libtvm.so(+0x11e674b) [0x7feeed32674b]
  File "/home/ubuntu/tvm/python/tvm/relay/backend/_backend.py", line 51, in lower
   f = _build.lower(sch, inputs, name=func_name)
  File "/home/ubuntu/tvm/python/tvm/build_module.py", line 417, in lower
   return ir_pass.MakeAPI(stmt, name, arg_list, 0, cfg.restricted_func)
  File "/home/ubuntu/tvm/python/tvm/_ffi/_ctypes/function.py", line 210, in __call__
   raise get_last_ffi_error()
  [bt] (3) /home/ubuntu/tvm/build/libtvm.so(TVMFuncCall+0x61) [0x7feeed32b251]
  [bt] (2) /home/ubuntu/tvm/build/libtvm.so(std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::TypedPackedFunc<tvm::LoweredFunc (tvm::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)>::AssignTypedLambda<tvm::LoweredFunc (*)(tvm::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)>(tvm::LoweredFunc (*)(tvm::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool))::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)+0x120) [0x7feeecbad640]
  [bt] (1) /home/ubuntu/tvm/build/libtvm.so(tvm::ir::MakeAPI(tvm::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x3cd5) [0x7feeece468f5]
  [bt] (0) /home/ubuntu/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x32) [0x7feeecb6bcf2]
  File "/home/ubuntu/tvm/src/pass/make_api.cc", line 205
  File "/home/ubuntu/tvm/python/tvm/_ffi/_ctypes/function.py", line 72, in cfun
   rv = local_pyfunc(*pyargs)
  File "/home/ubuntu/tvm/python/tvm/relay/backend/_backend.py", line 59, in lower
   raise RuntimeError(msg)
  File "/home/ubuntu/tvm/python/tvm/relay/backend/_backend.py", line 51, in lower
   f = _build.lower(sch, inputs, name=func_name)
  File "/home/ubuntu/tvm/python/tvm/build_module.py", line 417, in lower
   return ir_pass.MakeAPI(stmt, name, arg_list, 0, cfg.restricted_func)
  File "/home/ubuntu/tvm/python/tvm/_ffi/_ctypes/function.py", line 210, in __call__
   raise get_last_ffi_error()
  [bt] (3) /home/ubuntu/tvm/build/libtvm.so(TVMFuncCall+0x61) [0x7feeed32b251]
  [bt] (2) /home/ubuntu/tvm/build/libtvm.so(std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::TypedPackedFunc<tvm::LoweredFunc (tvm::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)>::AssignTypedLambda<tvm::LoweredFunc (*)(tvm::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)>(tvm::LoweredFunc (*)(tvm::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool))::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)+0x120) [0x7feeecbad640]
  [bt] (1) /home/ubuntu/tvm/build/libtvm.so(tvm::ir::MakeAPI(tvm::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x3cd5) [0x7feeece468f5]
  [bt] (0) /home/ubuntu/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x32) [0x7feeecb6bcf2]
  File "/home/ubuntu/tvm/src/pass/make_api.cc", line 205
TVMError: Not all Vars are passed in api_args:  'threadIdx.x'  does not appear in api_args
During handling of the above exception, another exception occurred:
TVMError: Not all Vars are passed in api_args:  'threadIdx.x'  does not appear in api_args
Error during compile function
```

Is it related to simplifier or autotvm?
This affects MxNet SSD with ResNet-50.

CC @tqchen @merrymercy @yzhliu @kevinthesun @cbalint13

**Comment by tqchen** [comment]
Thanks for reporting the problem. Please open a new troubleshooting thread on https://discuss.tvm.ai/ would be great if you can dig a bit further into what is happening in the low-level codegen.

**Comment by tqchen** [comment]
as a side, note i think it could due to a problem in the template or low level codegen instead of the autotvm or the simplifier side. Would be great to check what is really happening in here.
