### ISSUE TITLE
[Documentation] example code piece in comment of tvm.build_module.build() not working

### ISSUE THREAD

**Issue by optima2005** [dmlc/tvm#4190]
The comment under tvm.build_module.build() gives the following example code piece:
```python
        n = 2
        A = tvm.placeholder((n,), name='A')
        B = tvm.placeholder((n,), name='B')
        C = tvm.compute(A.shape, lambda *i: A(*i) + B(*i), name='C')
        s1 = tvm.create_schedule(C.op)
        s2 = topi.cpp.cuda.schedule_injective("cuda", [C])
        f1 = tvm.lower(s1, [A, B, C], name="test_add1")
        f2 = tvm.lower(s2, [A, B, C], name="test_add2")
        m = tvm.build({"llvm": [f1], "cuda": [f2]}, target_host="llvm")
```
But it reports the below error when running them,
```
Traceback (most recent call last):

  File "test1.py", line 55, in <module>
    s2 = topi.cpp.cuda.schedule_injective("cuda",[C])

  File "~/conda/envs/py36/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-ppc64le.egg/tvm/_ffi/_ctypes/function.py", line 211, in __call__
    raise get_last_ffi_error()

tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (3) ~/conda/envs/py36/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-ppc64le.egg/tvm/libtvm.so(TVMFuncCall+0x90) [0x7ffe9f8f3ef0]
  [bt] (2) ~/conda/envs/py36/lib/python3.6/site-packages/topi-0.6.dev0-py3.6.egg/topi/libtvm_topi.so(+0x642d0) [0x7ffe97d942d0]
  [bt] (1) ~/conda/envs/py36/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-ppc64le.egg/tvm/libtvm.so(tvm::Target tvm::runtime::TVMArgValue::AsNodeRef<tvm::Target>() const+0x160) [0x7ffe9efe69d0]
  [bt] (0) ~/conda/envs/py36/lib/python3.6/site-packages/tvm-0.6.dev0-py3.6-linux-ppc64le.egg/tvm/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x60) [0x7ffe9ee4de70]
  File "~/tvm/include/tvm/packed_func_ext.h", line 141
TVMError: Check failed: type_code_ == kNodeHandle (11 vs. 8) : expected NodeHandle but get str
```
It seems they should be modified as following to work:
```python
n = 2
A = tvm.placeholder((n,), name='A')
B = tvm.placeholder((n,), name='B')
C = tvm.compute(A.shape, lambda *i: A(*i) + B(*i), name='C')
s1 = tvm.create_schedule(C.op)
with tvm.target.cuda() as cuda_tgt:
    s2 = topi.cpp.cuda.schedule_injective(cuda_tgt,[C])
    f1 = tvm.lower(s1, [A, B, C], name="test_add1")
    f2 = tvm.lower(s2, [A, B, C], name="test_add2")
    m = tvm.build({"llvm": [f1], "cuda": [f2]}, target_host="llvm")
```

**Comment by tqchen** [comment]
good catch, can you send a PR to fix the problem?

**Comment by optima2005** [comment]
ok

**Comment by suhasgs007** [comment]
It must be the miss-match of the Cuda used while compiling the TVM. For example, while compiling the TVM used different version and now your using different version of CUDA.
