### ISSUE TITLE
OpenCL segmentation fault when execute tvm.cl or tvm.build OpenCL program using Intel Device

### ISSUE THREAD

**Issue by ysh329** [dmlc/tvm#429]
## Env.
- My laptop, Ubuntu 16.04 64bit
- I set `USE_OPENCL=1` in `config.mk` Note: my opencl device is `Intel(R) HD Graphics IvyBridge M GT2`
- Target: x86_64-linux-gnu
- clinfo cmd is okay as below and my laptop can make OpenCL program successfully using `gcc abc.cc -o abc -lOpenCL` cmd:
```shell
Number of platforms                               1
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 1.2 beignet 1.1.1
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_spir cl_khr_icd
  Platform Extensions function suffix             Intel

  Platform Name                                   Intel Gen OCL Driver
Number of devices                                 1
  Device Name                                     Intel(R) HD Graphics IvyBridge M GT2
  Device Vendor                                   Intel
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 1.2 beignet 1.1.1
  Driver Version                                  1.1.1
  Device OpenCL C Version                         OpenCL C 1.2 beignet 1.1.1
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               16
  Max clock frequency                             1000MHz
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None, None, None
  Max work item dimensions                        3
  Max work item sizes                             512x512x512
  Max work group size                             512
  Preferred work group size multiple              16
  Preferred / native vector sizes                 
    char                                                16 / 8       
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 0 / 8        (n/a)
    float                                                4 / 4       
    double                                               0 / 2        (n/a)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              2147483648 (2GiB)
  Error Correction support                        No
  Max memory allocation                           1073741824 (1024MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        8192
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             8192x8192 pixels
    Max 3D image size                             8192x8192x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Global
  Local memory size                               65536 (64KiB)
  Max constant buffer size                        134217728 (128MiB)
  Max number of constant args                     8
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      80ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    SPIR versions                                 <printDeviceInfo:138: get   SPIR versions size : error -30>
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                __cl_copy_region_align4;__cl_copy_region_align16;__cl_cpy_region_unalign_same_offset;__cl_copy_region_unalign_dst_offset;__cl_copy_region_unalign_src_offset;__cl_copy_buffer_rect;__cl_copy_image_1d_to_1d;__cl_copy_image_2d_to_2d;__cl_copy_image_3d_to_2d;__cl_copy_image
_2d_to_3d;__cl_copy_image_3d_to_3d;__cl_copy_image_2d_to_buffer;__cl_copy_image_3d_to_buffer;__cl_copy_buffer_to_image_2d;__cl_copy_buffer_to_image_3d;__cl_fill_region_unalign;__cl_fill_region_align2;__cl_fill_region_align4;__cl_fill_region_align8_2;__cl_fill_region_align8_4;__cl_fill_region_align8_8;__cl_fill_region_
align8_16;__cl_fill_region_align128;__cl_fill_image_1d;__cl_fill_image_1d_array;__cl_fill_image_2d;__cl_fill_image_2d_array;__cl_fill_image_3d;
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_spir cl_khr_icd

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel Gen OCL Driver
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [Intel]
  clCreateContext(NULL, ...) [default]            Success [Intel]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics IvyBridge M GT2
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics IvyBridge M GT2

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.8
  ICD loader Profile                              OpenCL 1.2
        NOTE:   your OpenCL library declares to support OpenCL 1.2,
                but it seems to support up to OpenCL 2.1 too.
```

## Code
```python
import tvm 
import numpy as np

debug = True
target = "llvm -target=x86_64-linux-gnu"

def test_add(n=1024):
    n = tvm.var("n")
    A = tvm.placeholder((n,), name="A")
    B = tvm.placeholder((n,), name="B")
    C = tvm.compute(A.shape, lambda i: A[i]+B[i], name="C")
    print(type(C))
    s = tvm.create_schedule(C.op)

    if debug:
        print(tvm.lower(s, [A, B, C], simple_mode=True))

    bx, tx = s[C].split(C.op.axis[0], factor=32)
    s[C].bind(bx, tvm.thread_axis("blockIdx.x"))
    s[C].bind(tx, tvm.thread_axis((0, n), "threadIdx.x"))
    print("bind success")

    if debug:
        print(tvm.lower(s, [A, B, C], simple_mode=True))

    add_func = tvm.build(s, [A, B, C], "opencl", name="myadd")
    print("build success")

    ctx = tvm.cl(0)
    a = tvm.nd.array(np.random.uniform(size=n).astype(A.dtype), ctx)
    b = tvm.nd.array(np.random.uniform(size=n).astype(B.dtype), ctx)
    c = tvm.nd.array(np.zeros(n, dtype=C.dtye), ctx)

    add_func(a, b, c)
    print("run success")
    np.testing.assert_allclose(c.asnumpy(), a.asnumpy() + b.asnumpy())
    print("check success")
    dev_module = add_func.imported_module[0]
    print("----- opencl code ------")
    print(dev_module.get_source())


test_add()
```

## Error Log

```shell
$ python vecadd_opencl_local.py 
<class 'tvm.tensor.Tensor'>
produce C {
  for (i, 0, n) {
    C[i] = (A[i] + B[i])
  }
}

bind success
produce C {
  // attr [iter_var(blockIdx.x, , blockIdx.x)] thread_extent = ((n + 31)/32)
  // attr [iter_var(threadIdx.x, Range(min=0, extent=n), threadIdx.x)] thread_extent = 32
  if (likely(((blockIdx.x*32) < (n - threadIdx.x)))) {
    C[((blockIdx.x*32) + threadIdx.x)] = (A[((blockIdx.x*32) + threadIdx.x)] + B[((blockIdx.x*32) + threadIdx.x)])
  }
}

Segmentation fault (core dumped)
```

Some friends said it's strange to use `Intel(R) HD Graphics IvyBridge M GT2` as OpenCL device. So I changed `ctx = tvm.cl(0)` to `ctx = tvm.cpu(0)` and `ctx = tvm.gpu(0)`. However, these situation got same errors as above.

**Comment by tqchen** [comment]
please do more debugs, for example, use gdb to get back trace on where does the failure happens, also you can try print out the code of ocl and see if you can directly compile and run it on the local machine.

**Comment by tqchen** [comment]
One quick thing to confirm is to check tvm.cl(0).exist

**Comment by ysh329** [comment]
I found OpenCL of Intel(R) HD Graphics on my laptop is strange (not supported) :rofl: , OpenCL of Mali GPU on board is okay.

# Strange Intel(R) HD Graphics

local run:

```shell
In [1]: import tvm

In [2]: cpu = tvm.cpu(0)

In [3]: cpu.exist
Out[3]: True

In [4]: gpu = tvm.gpu(0)

In [5]: gpu.exist
Out[5]: False

In [6]: cl = tvm.cl(0)

In [7]: cl.exist
Segmentation fault (core dumped)
yuens@Spark:~/Software/tvm/python$ 
```

# Mali GPU is okay

Connection using RPC.

```shell
In [1]: import tvm

In [2]: from tvm.contrib import rpc, util

In [3]: server = rpc.Server(host='0.0.0.0', port=9090)

In [4]: remote = rpc.connect("192.168.1.56", 9090)

In [5]: cl = remote.cl(0)

In [6]: cl.device_id
Out[6]: 0

In [7]: cl.device_type
Out[7]: 132

In [8]: cl.warp_size
Out[8]: 1

In [9]: cl.max_threads_per_block
Out[9]: 256

In [10]: cl.exist
Out[10]: True

```

**Comment by ysh329** [comment]
I installed on another `x86_64-linux-gnu` desktop machine (named `cross-compile machine`) occurs same error as my laptop (Ubuntu 16.04 64bit) : **segmentation fault** when executing `f = tvm.build(s, [A, B, C], target="opencl", target_host='llvm', name="myadd")`.

I installed OpenCL on my laptop with commands below from [here](https://askubuntu.com/questions/850281/opencl-on-ubuntu-16-04-intel-sandy-bridge-cpu):
```shell
# Basic installation 
sudo apt install ocl-icd-libopencl1
sudo apt install opencl-headers
sudo apt install clinfo

# Needed to link and compile 
sudo apt install ocl-icd-opencl-dev

# For Intel GT core
sudo apt install beignet
```

Using above commands, I failed to intsalled OpenCL on `cross-compile machine` but successfully installed (use `clinfo` cmd. shows a lot of message) OpenCL by installation of [Intel OpenCL SDK](https://software.intel.com/en-us/articles/opencl-drivers#latest_linux_SDK_release).

But I found some notes in [OpenCL™ Drivers and Runtimes for Intel® Architecture](https://software.intel.com/en-us/articles/opencl-drivers#latest_linux_SDK_release) as below:

```
Installation has two parts:

- Intel® SDK for OpenCL™ Applications Package
- Driver and library(runtime) packages
```

I only installed first one (Intel® SDK for OpenCL™ Applications Package) on `cross-compile machine`, because I found that the second one (Driver and library(runtime) packages) doesn't support for Ubuntu 16.04 (ONLY support Ubuntu12.04 and 14.04, My laptop and `cross-compile machine` are both 16.04). Thus, I'm not sure whether the issue is about lacking of `Driver and library(runtime) packages` or not fully support intel device or others?

Below is `clinfo` output on `cross-compile machine`: 
```shell
Number of platforms                               2
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 1.2 beignet 1.1.1
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_spir cl_khr_icd
  Platform Extensions function suffix             Intel
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)

  Platform Name                                   Experimental OpenCL 2.1 CPU Only Platform
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 2.1 LINUX
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_kh
r_fp64 cl_khr_image2d_from_buffer 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             INTEL

  Platform Name                                   Intel Gen OCL Driver
Number of devices                                 0

  Platform Name                                   Experimental OpenCL 2.1 CPU Only Platform
Number of devices                                 1
  Device Name                                     Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.1 (Build 10)
  Driver Version                                  1.2.0.10
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     CPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               4
  Max clock frequency                             3200MHz
  Device Partition                                (core)
    Max number of sub-devices                     4
    Supported partition types                     by counts, equally, by names (Intel)
  Max work item dimensions                        3
  Max work item sizes                             8192x8192x8192
  Max work group size                             8192
  Preferred work group size multiple              128
  Max sub-groups per work group                   1
  Preferred / native vector sizes                 
    char                                                 1 / 32      
    short                                                1 / 16      
    int                                                  1 / 8       
    long                                                 1 / 4       
    half                                                 0 / 0        (n/a)
    float                                                1 / 8       
    double                                               1 / 4        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              4048326656 (3.77GiB)
  Error Correction support                        No
  Max memory allocation                           1012081664 (965.2MiB)
  Unified memory for Host and Device              Yes
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   Yes
    Fine-grained system sharing                   Yes
    Atomics                                       Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Preferred alignment for atomics                 
    SVM                                           64 bytes
    Global                                        64 bytes
    Local                                         0 bytes
  Max size for global variable                    65536 (64KiB)
  Preferred total size of global vars             65536 (64KiB)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        262144
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             480
    Max size for 1D images from buffer            63255104 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   64 bytes
    Pitch alignment for 2D image buffers          64 bytes
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 480
    Max number of write image args                480
    Max number of read/write image args           480
  Max number of pipe args                         16
  Max active pipe reservations                    65535
  Max pipe packet size                            1024
  Local memory type                               Global
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        131072 (128KiB)
  Max number of constant args                     480
  Max size of kernel argument                     3840 (3.75KiB)
  Queue properties (on host)                      
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Local thread execution (Intel)                Yes
  Queue properties (on device)                    
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Preferred size                                4294967295 (4GiB)
    Max size                                      4294967295 (4GiB)
  Max queues on device                            4294967295
  Max events on device                            4294967295
  Prefer user sync for interop                    No
  Profiling timer resolution                      1ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    Sub-group independent forward progress        No
    IL version                                    SPIR-V_1.0
    SPIR versions                                 1.2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_kh
r_fp64 cl_khr_image2d_from_buffer 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [INTEL]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform
        NOTE:   your OpenCL library only supports OpenCL 2.0,
                but some installed platforms support OpenCL 2.1.
                Programs using 2.1 features may crash
                or behave unexepectedly
```

**Comment by ysh329** [comment]
## Code on Local Machine
```python
import tvm 
import numpy as np
from tvm.contrib import rpc, util
 
debug = True
#target = "llvm -target=x86_64-linux-gnu"
#target = "llvm -target=aarch64-linux-gnu -mcpu=cortex-a72 -mattr=+neon"
target = "llvm"
 
def test_add(n=256):                                                                                                                                                                                                                                                                                                           
    n = tvm.convert(n)
    A = tvm.placeholder((n,), name="A")
    B = tvm.placeholder((n,), name="B")
    C = tvm.compute(A.shape, lambda i: A[i]+B[i], name="C")
    print(type(C))
    s = tvm.create_schedule(C.op)
    print("create success")
 
    print(tvm.lower(s, [A, B, C], simple_mode=True))
 
    print("prepare to bind")
    bx, tx = s[C].split(C.op.axis[0], factor=64)
    s[C].bind(bx, tvm.thread_axis("blockIdx.x"))
    s[C].bind(tx, tvm.thread_axis("threadIdx.x"))
    print("bind success")
 
    if debug:
        print(tvm.lower(s, [A, B, C], simple_mode=True))
    # build
    print("prepare to build")
    f = tvm.build(s, [A, B, C], target="opencl", target_host=target, name="myadd")
    print("build success")
 
    ctx = remote.cl(0)
    print("ctx.device_id:" + str(ctx.device_id))
    print("ctx.device_type:" + str(ctx.device_type))
    print("ctx.max_threads_per_block:" + str(ctx.max_threads_per_block))
    print("ctx.exist:" + str(ctx.exist))
 
    dev_module = f.imported_modules[0]
    print("----- opencl code ------")
    print(dev_module.get_source())
 
    lib_name = "mylib.o"
    temp = util.tempdir()
    path = temp.relpath(lib_name)
    print("local saving...")
    f.save(path)
    print("remote uploading...")
    remote.upload(path)
    print("remote loading...")
    f = remote.load_module(lib_name)
    print("load module success on remote")
    a = tvm.nd.array(np.random.uniform(size=n).astype(A.dtype), ctx)
    b = tvm.nd.array(np.random.uniform(size=n).astype(B.dtype), ctx)
    c = tvm.nd.array(np.zeros(n, dtype=C.dtye), ctx)
 
    # remote
    time_f = f.time_evaluator("peak", ctx, number=20)
    cost = time_f(a, b, c)
 
    print("run success")
    np.testing.assert_allclose(c.asnumpy(), a.asnumpy() + b.asnumpy())
    print("check success")
    print("----- opencl code ------")
    print(dev_module.get_source())
 

remote = rpc.connect("192.168.1.56", 9090)
test_add()

```


## Logs
```shell
yuanshuai@cross-compile:~/code/tvm-mobile-opencl/bandwidth$ gdb python vecadd_opencl_remote.py                                                                                                                                                                                                                          [31/66]
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...(no debugging symbols found)...done.
"/home/yuanshuai/code/tvm-mobile-opencl/bandwidth/vecadd_opencl_remote.py" is not a core dump: File format not recognized
(gdb) run vecadd_opencl_remote.py 
Starting program: /usr/bin/python vecadd_opencl_remote.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3a2b700 (LWP 28707)]
[New Thread 0x7ffff122a700 (LWP 28708)]
[New Thread 0x7fffeea29700 (LWP 28709)]
<class 'tvm.tensor.Tensor'>
create success
produce C {
  for (i, 0, 256) {
    C[i] = (A[i] + B[i])
  }
}

prepare to bind
bind success
produce C {
  // attr [iter_var(blockIdx.x, , blockIdx.x)] thread_extent = 4
  // attr [iter_var(threadIdx.x, , threadIdx.x)] thread_extent = 64
  C[((blockIdx.x*64) + threadIdx.x)] = (A[((blockIdx.x*64) + threadIdx.x)] + B[((blockIdx.x*64) + threadIdx.x)])
}

prepare to build

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffe999fab1 in llvm::cl::AddLiteralOption(llvm::cl::Option&, llvm::StringRef) ()
   from /home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so
(gdb) bt
#0  0x00007fffe999fab1 in llvm::cl::AddLiteralOption(llvm::cl::Option&, llvm::StringRef) ()
   from /home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so
#1  0x00007fffe918beb1 in llvm::RegisterPassParser<llvm::MachineSchedRegistry>::NotifyAdd(llvm::StringRef, void* (*)(), llvm::StringRef) ()
   from /home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so
#2  0x00007fffe2335889 in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-3.6.so.1
#3  0x00007ffff7de76ba in call_init (l=<optimized out>, argc=argc@entry=2, argv=argv@entry=0x7fffffffe228, env=env@entry=0xa351e0) at dl-init.c:72
#4  0x00007ffff7de77cb in call_init (env=0xa351e0, argv=0x7fffffffe228, argc=2, l=<optimized out>) at dl-init.c:30
#5  _dl_init (main_map=main_map@entry=0xf61000, argc=2, argv=0x7fffffffe228, env=0xa351e0) at dl-init.c:120
#6  0x00007ffff7dec8e2 in dl_open_worker (a=a@entry=0x7fffffff9cd0) at dl-open.c:575
#7  0x00007ffff7de7564 in _dl_catch_error (objname=objname@entry=0x7fffffff9cc0, errstring=errstring@entry=0x7fffffff9cc8, 
    mallocedp=mallocedp@entry=0x7fffffff9cbf, operate=operate@entry=0x7ffff7dec4d0 <dl_open_worker>, args=args@entry=0x7fffffff9cd0) at dl-error.c:187
#8  0x00007ffff7debda9 in _dl_open (file=0x7fffe6581188 "/usr/lib/x86_64-linux-gnu/beignet//libgbe.so", mode=-2147483647, caller_dlopen=0x7fffe6558d4f, 
    nsid=-2, argc=<optimized out>, argv=<optimized out>, env=0xa351e0) at dl-open.c:660
#9  0x00007ffff75ecf09 in dlopen_doit (a=a@entry=0x7fffffff9f00) at dlopen.c:66
#10 0x00007ffff7de7564 in _dl_catch_error (objname=0x9a6e80, errstring=0x9a6e88, mallocedp=0x9a6e78, operate=0x7ffff75eceb0 <dlopen_doit>, 
    args=0x7fffffff9f00) at dl-error.c:187
#11 0x00007ffff75ed571 in _dlerror_run (operate=operate@entry=0x7ffff75eceb0 <dlopen_doit>, args=args@entry=0x7fffffff9f00) at dlerror.c:163
#12 0x00007ffff75ecfa1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#13 0x00007fffe6558d4f in ?? () from /usr/lib/x86_64-linux-gnu/beignet//libcl.so
#14 0x00007ffff7de76ba in call_init (l=<optimized out>, argc=argc@entry=2, argv=argv@entry=0x7fffffffe228, env=env@entry=0xa351e0) at dl-init.c:72
#15 0x00007ffff7de77cb in call_init (env=0xa351e0, argv=0x7fffffffe228, argc=2, l=<optimized out>) at dl-init.c:30
#16 _dl_init (main_map=main_map@entry=0xf605c0, argc=2, argv=0x7fffffffe228, env=0xa351e0) at dl-init.c:120
#17 0x00007ffff7dec8e2 in dl_open_worker (a=a@entry=0x7fffffffa250) at dl-open.c:575
#18 0x00007ffff7de7564 in _dl_catch_error (objname=objname@entry=0x7fffffffa240, errstring=errstring@entry=0x7fffffffa248, 
    mallocedp=mallocedp@entry=0x7fffffffa23f, operate=operate@entry=0x7ffff7dec4d0 <dl_open_worker>, args=args@entry=0x7fffffffa250) at dl-error.c:187
#19 0x00007ffff7debda9 in _dl_open (file=0xf39bd0 "/usr/lib/x86_64-linux-gnu/beignet//libcl.so", mode=-2147483646, caller_dlopen=0x7fffe7750a27, nsid=-2, 
    argc=<optimized out>, argv=<optimized out>, env=0xa351e0) at dl-open.c:660
#20 0x00007ffff75ecf09 in dlopen_doit (a=a@entry=0x7fffffffa480) at dlopen.c:66
#21 0x00007ffff7de7564 in _dl_catch_error (objname=0x9a6e80, errstring=0x9a6e88, mallocedp=0x9a6e78, operate=0x7ffff75eceb0 <dlopen_doit>, 
    args=0x7fffffffa480) at dl-error.c:187
#22 0x00007ffff75ed571 in _dlerror_run (operate=operate@entry=0x7ffff75eceb0 <dlopen_doit>, args=args@entry=0x7fffffffa480) at dlerror.c:163
#23 0x00007ffff75ecfa1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#24 0x00007fffe7750a27 in ?? () from /usr/lib/x86_64-linux-gnu/libOpenCL.so.1
#25 0x00007fffe7750db1 in ?? () from /usr/lib/x86_64-linux-gnu/libOpenCL.so.1
#26 0x00007fffe7750230 in clGetPlatformIDs () from /usr/lib/x86_64-linux-gnu/libOpenCL.so.1
#27 0x00007fffe86280fa in tvm::runtime::cl::GetPlatformIDs() ()
   from /home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so
#28 0x00007fffe862937c in tvm::runtime::cl::OpenCLWorkspace::Init() ()
   from /home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so
#29 0x00007fffe863d901 in tvm::runtime::OpenCLModuleNode::Init() ()
   from /home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so
---Type <return> to continue, or q <return> to quit---bt
_string<char, std::char_traits<char>, std::allocator<char> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::FunctionInfo, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, tvm::runtime::FunctionInfo> > >) () from /home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so
#31 0x00007fffe8415f99 in tvm::codegen::BuildOpenCL(tvm::Array<tvm::LoweredFunc, void>) () from /home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so
#32 0x00007fffe84162ca in std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::codegen::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}>::_M_invoke () from /home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so
#33 0x00007fffe8423fa3 in tvm::codegen::Build(tvm::Array<tvm::LoweredFunc, void> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so
#34 0x00007fffe83ded79 in std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::codegen::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) ()
   from /home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so
#35 0x00007fffe860909e in TVMFuncCall () from /home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so
#36 0x00007ffff6617e40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#37 0x00007ffff66178ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#38 0x00007ffff68273df in _ctypes_callproc () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#39 0x00007ffff682bd82 in ?? () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#40 0x00000000004b0cb3 in PyObject_Call ()
#41 0x00000000004c9faf in PyEval_EvalFrameEx ()
#42 0x00000000004c2765 in PyEval_EvalCodeEx ()
#43 0x00000000004de6fe in ?? ()
#44 0x00000000004b0cb3 in PyObject_Call ()
#45 0x00000000004f492e in ?? ()
#46 0x00000000004b0cb3 in PyObject_Call ()
#47 0x0000000000553187 in ?? ()
#48 0x00000000004b0cb3 in PyObject_Call ()
#49 0x00000000004c6ad1 in PyEval_EvalFrameEx ()
#50 0x00000000004c2765 in PyEval_EvalCodeEx ()
#51 0x00000000004ca8d1 in PyEval_EvalFrameEx ()
#52 0x00000000004c9d8f in PyEval_EvalFrameEx ()
#53 0x00000000004c2765 in PyEval_EvalCodeEx ()
#54 0x00000000004ca099 in PyEval_EvalFrameEx ()
#55 0x00000000004c2765 in PyEval_EvalCodeEx ()
#56 0x00000000004ca099 in PyEval_EvalFrameEx ()
#57 0x00000000004c2765 in PyEval_EvalCodeEx ()
#58 0x00000000004c2509 in PyEval_EvalCode ()
#59 0x00000000004f1def in ?? ()
#60 0x00000000004ec652 in PyRun_FileExFlags ()
#61 0x00000000004eae31 in PyRun_SimpleFileExFlags ()
#62 0x000000000049e14a in Py_Main ()
#63 0x00007ffff7810830 in __libc_start_main (main=0x49dab0 <main>, argc=2, argv=0x7fffffffe228, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe218) at ../csu/libc-start.c:291
#64 0x000000000049d9d9 in _start ()
```
