### ISSUE TITLE
import tvm: libtvm.so: undefined symbol

### ISSUE THREAD

**Issue by ysh329** [dmlc/tvm#448]
## Env.

- Ubuntu16.04 64bit
- x86_64-linux-gnu
- LLVM 4.0.1

## config.mk
```shell
DEBUG = 1
USE_RPC = 1
LLVM_CONFIG = llvm-config
USE_BLAS = openblas
```

After `config.mk` set, I ran `make -j4`, `python setup.py install --user` and set enviroments.

## Error

```shell
yuanshuai@cross-compile:~/code/tvm$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/__init__.py", line 5, in <module>
    from . import tensor
  File "/home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/tensor.py", line 4, in <module>
    from ._ffi.node import NodeBase, NodeGeneric, register_node, convert_to_node
  File "/home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/node.py", line 8, in <module>
    from .node_generic import NodeGeneric, convert_to_node, const
  File "/home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/node_generic.py", line 7, in <module>
    from .base import string_types
  File "/home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/base.py", line 43, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/yuanshuai/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so: undefined symbol: _ZN4llvm14TargetRegistry12lookupTargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS6_
>>>
```

## ~/.bashrc
```shell
# PYTHON
export PYTHONPATH=/usr/bin/python2
 
# LLVM
export LLVM_HOME=/opt/clang+llvm-4.0.1-x86_64-linux-gnu-debian8
export PATH=$LLVM_HOME/bin:$PATH
 
# TVM
export TVM_HOME=~/code/tvm
export PATH=$TVM_HOME/lib:$PATH
export PYTHONPATH=$PYTHONPATH:$TVM_HOME/python
```

**Comment by austingg** [comment]
@ysh329  try 
```shell
git pull && git submodule update --recursive
make clean
make -j4 
python setup.py install --user
```

**Comment by ysh329** [comment]
@austingg Thanks, I tried but problem still exists:rofl:

**Comment by ysh329** [comment]
I found it's okay `import tvm` if build without `LLVM-CONFIG` in `config.mk`.

**Comment by ysh329** [comment]
Fixed. Replace `clang+llvm-4.0.1-x86_64-linux-gnu-debian8.tar.xz` with `clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz`.
