### ISSUE TITLE
Module[source] does not support SaveToBinary

### ISSUE THREAD

**Issue by ysh329** [dmlc/tvm#464]
## Env.
- Ubuntu16.04 64bit, x86_64-linux-gnu
- running in Docker, image(Ubuntu16.04 64bit, x86_64-linux-gnu)
- installed opencl (but `clinfo` output `Number of platform: 0`), llvm4.0.0 for ubuntu16.04 previously in container

I tried to run OpenCL kernel but failed using cross-compilation.

## config.mk
```shell
DEBUG = 1
USE_OPENCL = 1
USE_RPC = 1
LLVM_CONFIG = llvm-config
USE_BLAS = openblas
```

## Error logs
```shell
root@988bb6addc0d:/home/yuens/Documents/CLionProjects/tvm-mobile-opencl/bandwidth# python vecadd_opencl_remote.py 
<class 'tvm.tensor.Tensor'>
create success
produce C {
  for (i, 0, 64) {
    C[i] = (A[i] + B[i])
  }
}

prepare to bind
bind success
prepare to build
[12:56:07] src/codegen/build_opencl.cc:29: OpenCL runtime not enabled, return a source module...
build success
ctx.device_id:0
ctx.device_type:132
ctx.max_threads_per_block:256
ctx.exist:True
----- opencl code ------
__kernel void myadd__kernel0(__global float* restrict C, __global float* restrict A, __global float* restrict B) {
  C[((((int)get_group_id(0)) * 32) + ((int)get_local_id(0)))] = (A[((((int)get_group_id(0)) * 32) + ((int)get_local_id(0)))] + B[((((int)get_group_id(0)) * 32) + ((int)get_local_id(0)))]);
}


[12:56:07] /root/tvm/dmlc-core/include/dmlc/./logging.h:308: [12:56:07] src/runtime/module.cc:81: Module[source] does not support SaveToBinary

Stack trace returned 10 entries:
[bt] (0) /root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(_ZN3tvm7runtime10ModuleNode12SaveToBinaryEPN4dmlc6StreamE+0x30c) [0x7fd49aed42bc]
[bt] (1) /root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(_ZN3tvm7codegen14PackImportsToCB5cxx11ERKNS_7runtime6ModuleEb+0xd01) [0x7fd49ad0be61]
[bt] (2) /root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(+0x86104c) [0x7fd49acb704c]
[bt] (3) /root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(TVMFuncCall+0x5e) [0x7fd49aee124e]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fd4b37cbe40]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fd4b37cb8ab]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7fd4b39db3df]
[bt] (7) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7fd4b39dfd82]
[bt] (8) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (9) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]

Traceback (most recent call last):
  File "vecadd_opencl_remote.py", line 70, in <module>
    test_add()
  File "vecadd_opencl_remote.py", line 48, in test_add
    f.export_library(tar_path)
  File "/root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/module.py", line 101, in export_library
    f.write(_PackImportsToC(self, is_system_lib))
  File "/root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/function.py", line 255, in my_api_func
    return flocal(*args)
  File "/root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [12:56:07] src/runtime/module.cc:81: Module[source] does not support SaveToBinary

Stack trace returned 10 entries:
[bt] (0) /root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(_ZN3tvm7runtime10ModuleNode12SaveToBinaryEPN4dmlc6StreamE+0x30c) [0x7fd49aed42bc]
[bt] (1) /root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(_ZN3tvm7codegen14PackImportsToCB5cxx11ERKNS_7runtime6ModuleEb+0xd01) [0x7fd49ad0be61]
[bt] (2) /root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(+0x86104c) [0x7fd49acb704c]
[bt] (3) /root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so(TVMFuncCall+0x5e) [0x7fd49aee124e]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fd4b37cbe40]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fd4b37cb8ab]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7fd4b39db3df]
[bt] (7) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7fd4b39dfd82]
[bt] (8) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (9) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
```

## Local Code
```Python
import tvm
import numpy as np
from tvm.contrib import rpc, util

debug = True
#target = "llvm -target=x86_64-linux-gnu"
#target = "llvm -target=aarch64-linux-gnu -mcpu=cortex-a72 -mattr=+neon"
target = "llvm"

def test_add(n=64):
    n = tvm.convert(n)
    A = tvm.placeholder((n,), name="A")
    B = tvm.placeholder((n,), name="B")
    C = tvm.compute(A.shape, lambda i: A[i]+B[i], name="C")
    print(type(C))
    s = tvm.create_schedule(C.op)
    print("create success")

    print(tvm.lower(s, [A, B, C], simple_mode=True))

    print("prepare to bind")
    bx, tx = s[C].split(C.op.axis[0], factor=32)
    s[C].bind(bx, tvm.thread_axis("blockIdx.x"))
    s[C].bind(tx, tvm.thread_axis("threadIdx.x"))
    print("bind success")

    print("prepare to build")
    f = tvm.build(s, [A, B, C], target="opencl", target_host=target, name="myadd")
    #f = tvm.build(s, [A, B, C], target="opencl", name="myadd")
    print("build success")

    ctx = remote.cl(0)
    print("ctx.device_id:" + str(ctx.device_id))
    print("ctx.device_type:" + str(ctx.device_type))
    print("ctx.max_threads_per_block:" + str(ctx.max_threads_per_block))
    print("ctx.exist:" + str(ctx.exist))

    dev_module = f.imported_modules[0]
    print("----- opencl code ------")
    print(dev_module.get_source())

    lib_name = "mylib.tar"
    temp = util.tempdir()
    tar_path = temp.relpath(lib_name)
    f.export_library(tar_path)
    remote.upload(tar_path)
    f = remote.load_module(lib_name)
    print("load module success on remote")


    a = tvm.nd.array(np.random.uniform(size=n).astype(A.dtype), ctx)
    b = tvm.nd.array(np.random.uniform(size=n).astype(B.dtype), ctx)
    c = tvm.nd.array(np.zeros(n, dtype=C.dtye), ctx)

    # remote
    time_f = f.time_evaluator("peak", ctx, number=20)
    cost = time_f(a, b, c)
    print("run success")
    np.testing.assert_allclose(c.asnumpy(), a.asnumpy() + b.asnumpy())
    print("check success")
    print("----- opencl code ------")
    print(dev_module.get_source())

remote = rpc.connect("192.168.1.56", 9090)
test_add()
```

**Comment by tqchen** [comment]
Build with opencl enabled in your host

**Comment by tqchen** [comment]
You might need to make clean and redo make again as the host message shows opencl is not enabled

**Comment by ysh329** [comment]
Okay, I'll try again!
