### ISSUE TITLE
Conda Environment libgcc blocks execution 

### ISSUE THREAD

**Issue by dendisuhubdy** [dmlc/tvm#488]
```
(dev) suhubdyd@leto52:~$ python -c "import tvm"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/u/suhubdyd/.conda/envs/dev/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/__init__.py", line 5, in <module>
    from . import tensor
  File "/u/suhubdyd/.conda/envs/dev/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/tensor.py", line 4, in <module>
    from ._ffi.node import NodeBase, NodeGeneric, register_node, convert_to_node
  File "/u/suhubdyd/.conda/envs/dev/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/node.py", line 8, in <module>
    from .node_generic import NodeGeneric, convert_to_node, const
  File "/u/suhubdyd/.conda/envs/dev/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/node_generic.py", line 7, in <module>
    from .base import string_types
  File "/u/suhubdyd/.conda/envs/dev/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/base.py", line 43, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/u/suhubdyd/.conda/envs/dev/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/u/suhubdyd/.conda/envs/dev/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /u/suhubdyd/.conda/envs/dev/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /u/suhubdyd/.conda/envs/dev/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so)
(dev) suhubdyd@leto52:~$ conda uninstall libgcc
Fetching package metadata .........
Solving package specifications: .

Package plan for package removal in environment /u/suhubdyd/.conda/envs/dev:

The following packages will be REMOVED:

    libgcc: 5.2.0-0

Proceed ([y]/n)? y

(dev) suhubdyd@leto52:~$ python -c "import tvm"
TVM: Initializing cython mode...
(dev) suhubdyd@leto52:~$ cd research/code/tvm/
(dev) suhubdyd@leto52:~/research/code/tvm$ python tvm1.py
TVM: Initializing cython mode...
<class 'tvm.tensor.Tensor'>
(dev) suhubdyd@leto52:~/research/code/tvm$
```

**Comment by tqchen** [comment]
@ezyang do you know what is the problem in here?

**Comment by tqchen** [comment]
seems to be a libc compatibility issue instead of something that can be fixed by tvm, close this for now
