### ISSUE TITLE
cannot run tutorial files well.

### ISSUE THREAD

**Issue by Arthur-Shi** [dmlc/tvm#495]
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

runfile('C:/Users/admin/tvm/tutorials/get_started.py', wdir='C:/Users/admin/tvm/tutorials')
<class 'tvm.tensor.Tensor'>
Traceback (most recent call last):

  File "<ipython-input-1-fcb362216d4c>", line 1, in <module>
    runfile('C:/Users/admin/tvm/tutorials/get_started.py', wdir='C:/Users/admin/tvm/tutorials')

  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/admin/tvm/tutorials/get_started.py", line 111, in <module>
    fadd_cuda = tvm.build(s, [A, B, C], "cuda", target_host="llvm", name="myadd")

  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tvm-0.1.0-py3.6-win-amd64.egg\tvm\build_module.py", line 368, in build
    mhost = codegen.build_module(fhost, target_host)

  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tvm-0.1.0-py3.6-win-amd64.egg\tvm\codegen.py", line 20, in build_module
    return _Build(lowered_func, target)

  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tvm-0.1.0-py3.6-win-amd64.egg\tvm\_ffi\function.py", line 255, in my_api_func
    return flocal(*args)

  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tvm-0.1.0-py3.6-win-amd64.egg\tvm\_ffi\_ctypes\function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))

  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tvm-0.1.0-py3.6-win-amd64.egg\tvm\_ffi\base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))

TVMError: [14:08:51] C:\Users\admin\tvm\src\codegen\codegen.cc:27: Check failed: bf != nullptr Target llvm is not enabled

I tried other softwares, but it gave the same output.

What should I do to make the file work?

**Comment by Arthur-Shi** [comment]
Is it not a file to run? Just for introduction of some important functions？

**Comment by Arthur-Shi** [comment]
sometimes It can output right, but it will go wrong after running again.

**Comment by tqchen** [comment]
as the error indicates, you will need to build with llvm enabled

**Comment by Arthur-Shi** [comment]
yeah, I found the llvm folder and which file should be bulit by VS?

And where can I find the files you wrote for this test? 
http://tvmlang.org/2017/08/22/Optimize-Deep-Learning-GPU-Operators-with-TVM-A-Depthwise-Convolution-Example.html

Thank you so much.

**Comment by tqchen** [comment]
@sxjscience do you have some instruction for building with LLVM on windows?

**Comment by Arthur-Shi** [comment]
And how to install the topi package? there is no setup.py in the topi folder. I tried to find the package.
sys.path.append('\Users\admin\tvm\topi\python\topi')
 But it is useless.

It is shown in the console.
  File "C:/Users/admin/tvm/topi/recipe/conv/depthwise_conv2d_test.py", line 7, in <module>
    import topi

ModuleNotFoundError: No module named 'topi

**Comment by sxjscience** [comment]
@Arthur-Shi Try to use `sys.path.append('C:\\Users\\admin\\tvm\\topi\\python')`.

Also, you can manually update the `easy-install.pth` file by adding `C:\\Users\\admin\\tvm\\topi\\python`. For example, I'm using Anaconda3 and my `easy-install.pth` file is located in `C:\\Anaconda3\\Lib\\site-packages\\easy-install.pth`.

For the llvm, I haven't installed it in Windows. However, I feel that it is not so hard by following the document https://llvm.org/docs/GettingStartedVS.html .

**Comment by Arthur-Shi** [comment]
I am trying to run tvm on Linux, but I still don't know how to build the library?

I tried this method, but I don't know how to programming in the terminal. 
http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html#AEN115

Could you show me the code tips? 

is it installing llvm necessary for linux?

**Comment by Arthur-Shi** [comment]
@sxjscience  I tried two methods you said, but still cannot import topi

**Comment by sxjscience** [comment]
@Arthur-Shi Could you run this?

'''python
import sys
sys.append('C:\\Users\\admin\\tvm\\topi\\python')
import tvm
'''
If not, what's the error message?

**Comment by Arthur-Shi** [comment]
@sxjscience It works.

I didnot run import sys

sorry.

Do you know what can i do? 
Skip because cuda is not enabled.

I have installed CUDA

**Comment by sxjscience** [comment]
Try the command here https://github.com/sxjscience/tvm/blob/master/windows_cmake_command.txt

**Comment by Arthur-Shi** [comment]
It is the output I run this command.

CMake Error: The source directory "C:/Users/admin" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by sxjscience** [comment]
Please read the doc https://github.com/dmlc/tvm/blob/master/docs/how_to/install.md

**Comment by Arthur-Shi** [comment]
sorry @sxjscience 

Ｉ　ｄｉｄｎｏｔ　ｒｕｎ　ｔｈｉｓ　ｃｏｍｍａｎｄ　ｉｎ　ｔｈｅ　ｂｕｉｌｄ　ｆｏｌｄｅｒ．

C:\Users\admin\tvm\build>cmake -G "Visual Studio 15 2017 Win64" ^
More? -DUSE_CUDA="ON" ^
More? -DCMAKE_BUILD_TYPE=Release ^
More? -DCMAKE_CONFIGURATION_TYPES="Release" ^
More? -DUSE_RPC="ON" ^
More? ..
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0 (found version "8.0")
-- Build with CUDA support
-- Build with RPC support...
-- Build with Graph runtime support...
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/admin/tvm/build

C:\Users\admin\tvm\build>

Ｂｕｔ　
runfile('C:/Users/admin/tvm/topi/recipe/conv/depthwise_conv2d_test.py', wdir='C:/Users/admin/tvm/topi/recipe/conv')
Skip because cuda is not enabled
Skip because cuda is not enabled

**Comment by sxjscience** [comment]
Please read the doc more carefully. The doc has stated that "This will generate the VS project using the MSVC 14 64 bit generator. Open the .sln file in the build directory and build with Visual Studio.". You will see a .sln file in the "build" directory. You need to open it with visual studio and build the solution file.

**Comment by Arthur-Shi** [comment]
ye，I built it by MSVC 15.

I dont know why? Some times My output is 
runfile('C:/Users/admin/tvm/topi/recipe/conv/depthwise_conv2d_test.py', wdir='C:/Users/admin/tvm/topi/recipe/conv')
Skip because cuda is not enabled
Skip because cuda is not enabled

sometimes my output is 

Traceback (most recent call last):
  File "C:\Users\admin\tvm\tutorials\get_started.py", line 111, in <module>
    fadd_cuda = tvm.build(s, [A, B, C], "cuda", target_host="llvm", name="myadd")
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tvm-0.1.0-py3.6-win-amd64.egg\tvm\build_module.py", line 368, in build
    mhost = codegen.build_module(fhost, target_host)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tvm-0.1.0-py3.6-win-amd64.egg\tvm\codegen.py", line 20, in build_module
    return _Build(lowered_func, target)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tvm-0.1.0-py3.6-win-amd64.egg\tvm\_ffi\function.py", line 255, in my_api_func
    return flocal(*args)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tvm-0.1.0-py3.6-win-amd64.egg\tvm\_ffi\_ctypes\function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tvm-0.1.0-py3.6-win-amd64.egg\tvm\_ffi\base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [16:28:15] C:\Users\admin\tvm\src\codegen\codegen.cc:27: Check failed: bf != nullptr Target llvm is not enabled

Acturally I built the tvm.sln and built the llvm-5.0.0.src. and run ur command.

**Comment by gengtsh** [comment]
i have a problem to run tutorial too. i run it on my Ubuntu16 VM. I installed cuda, llvm, python based on the doc. In the config.mk file, I set USE_CUDA flag to 1, and add my CUDA path and then, when i run make, it works. but when i run the get_start.py in tutorial,  i have an error in "fadd_cuda = tvm.build(s, [A, B, C], "cuda", target_host="llvm", name="myadd")". it said that cuda is not enable. could you please help me out. 
BTW, I installed cuda-compiler and didn't install cuda-driver, because i run it on my VM which can't access my nvidia graphic card.

**Comment by Arthur-Shi** [comment]
Because I did not switch cuda on in the config.mk.  And the I can run on the Ubtuntu.
Thank you so much.

**Comment by Arthur-Shi** [comment]
#754 continue trying to deal with this problem.

**Comment by jsjs0827** [comment]
@Arthur-Shi    I encoutner the same issue in WINDOWS10;I make the tvm with pre-build llvm(clang already can be used) successfully,can you give me some advice,thanks for any reply.
