### ISSUE TITLE
A problem in installation,need help

### ISSUE THREAD

**Issue by snack11** [dmlc/tvm#521]
OS:ubuntu 16.04
llvm4.0(pre-built version)

```
>>> import tvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/snack/workspace/tvm/tvm/python/tvm/__init__.py", line 5, in <module>
    from . import tensor
  File "/home/snack/workspace/tvm/tvm/python/tvm/tensor.py", line 4, in <module>
    from ._ffi.node import NodeBase, NodeGeneric, register_node, convert_to_node
  File "/home/snack/workspace/tvm/tvm/python/tvm/_ffi/node.py", line 8, in <module>
    from .node_generic import NodeGeneric, convert_to_node, const
  File "/home/snack/workspace/tvm/tvm/python/tvm/_ffi/node_generic.py", line 7, in <module>
    from .base import string_types
  File "/home/snack/workspace/tvm/tvm/python/tvm/_ffi/base.py", line 43, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/home/snack/workspace/tvm/tvm/python/tvm/_ffi/base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/snack/workspace/tvm/tvm/lib/libtvm.so: undefined symbol: _ZN4llvm3sys22getDefaultTargetTripleEv

```

**Comment by tqchen** [comment]
Try to use prebuild version here http://apt.llvm.org/

**Comment by snack11** [comment]
still the same question.

**Comment by tqchen** [comment]
make sure you set the LLVM_CONFIG to correct value, for example, if you get llvm5 from http://apt.llvm.org/ set it to be llvm-config-5.0

**Comment by snack11** [comment]
i'm sure the LLVM_CONFIG setted properly
`LLVM_CONFIG = llvm-config-4.0`

**Comment by tqchen** [comment]
If you search this error message a bit. you might find that there are related issues https://github.com/llvm-hs/llvm-hs/issues/84 which is caused by using some version of gcc.

**Comment by tqchen** [comment]
On Ubuntu 16.04 the LLVM pre-build are built with gcc5, which have a different ABI of std::string as gcc4x, this could be the cause of your problem: build the project with gcc5

**Comment by snack11** [comment]
thanks a lot，tried gcc5,still failed，but using gcc6，no this problem again.

**Comment by tqchen** [comment]
glad that this is resolved
