### ISSUE TITLE
`tvm.bind` not found

### ISSUE THREAD

**Issue by liangfu** [dmlc/tvm#532]
As shown in TVM Release Announcement:
![](http://www.tvmlang.org/images/release/code_highlevel.png)
but, I found no `tvm.bind` function implemented in the `tvm` package.

**Comment by masahi** [comment]
That functionality exists in the recent nnvm. See [here](http://nnvm.tvmlang.org/tutorials/from_mxnet.html#sphx-glr-tutorials-from-mxnet-py)

**Comment by liangfu** [comment]
Thanks @masahi, however, current implementation is only limited to `cuda` and `llvm` backend, and if target and device is changed to `opencl`, it raises AssertionError:
```
assert target.startswith("llvm")
```
at https://github.com/dmlc/nnvm/blob/master/python/nnvm/top/tensor.py#L15

I'm wondering how can I use `opencl` backend to predict the `tabby cat` image. Thanks in advance!

**Comment by masahi** [comment]
See the discussion [here](https://github.com/dmlc/tvm/issues/530)

**Comment by liangfu** [comment]
Thanks @masahi , since all changes you made are just add
```
target = "opencl"
ctx = tvm.cl(0)
```
in the following files:
```
python/nnvm/top/nn.py
python/nnvm/top/reduction.py
python/nnvm/top/tensor.py
```
but why not submit a PR to make `opencl` work in the `master` branch ? is there any concern or consequence ?

**Comment by liangfu** [comment]
It's okay to use either `cuda` or `llvm` to run with `nnvm` for the image classification demo of the tabby cat image.
However, after changing `target` to `opencl` and set `ctx` to `tvm.cl(0)`, I fail to execute the `m.run()` as highlighted in the following
```
# set inputs
m.set_input('data', tvm.nd.array(x.astype(dtype)))
m.set_input(**params)
# execute
m.run()                    # <<-------------------- HERE
# get outputs
tvm_output = m.get_output(0, tvm.nd.empty((1000,), dtype))
top1 = np.argmax(tvm_output.asnumpy())
```
after tracing back the call stack, I got the following lines:
```
#0  tvm::runtime::WorkspacePool::FreeWorkspace (this=0x5555571844e8, ctx=..., ptr=0x555559862880)
    at /home/liangfu/workspace/tvm/src/runtime/workspace_pool.cc:140
#1  0x00007fff981ea5b6 in TVMBackendFreeWorkspace (device_type=4, device_id=0, ptr=0x555559862880)
    at /home/liangfu/workspace/tvm/src/runtime/c_runtime_api.cc:234
#2  0x00007fff8ed0e8dc in fuse_conv2d_broadcast_mul_broadcast_add_relu ()
#3  0x00007fff981e63e9 in tvm::codegen::LLVMModuleNode::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<tvm::runtime::ModuleNode> const&)::{lambda(tvm::runtime::TVMArgs\
, tvm::runtime::TVMRetValue*)#2}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const (
    __closure=<optimized out>, args=..., rv=<optimized out>)
    at /home/liangfu/workspace/tvm/src/codegen/llvm/llvm_module.cc:58
#4  0x00007fff981e6697 in std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::codegen::LLVMModuleNode::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&,\
 std::shared_ptr<tvm::runtime::ModuleNode> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) (__functor=...,
    __args#0=<optimized out>, __args#1=<optimized out>) at /usr/include/c++/5/functional:1871
#5  0x00007fff9826fbc7 in std::function<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const (__args#1=0x7fffffffd4d0, __args#0=..., this=<optimized out>)
    at /usr/include/c++/5/functional:2267
#6  tvm::runtime::PackedFunc::CallPacked (rv=0x7fffffffd4d0, args=..., this=<optimized out>)
    at /home/liangfu/workspace/tvm/include/tvm/runtime/packed_func.h:684
#7  tvm::runtime::GraphRuntime::<lambda()>::operator() (__closure=<optimized out>)
    at /home/liangfu/workspace/tvm/src/runtime/graph/graph_runtime.cc:536
#8  std::_Function_handler<void(), tvm::runtime::GraphRuntime::CreateTVMOp(const tvm::runtime::TVMOpParam&, const std::vector<DLTensor>&, size_t)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/5/functional:1871
#9  0x00007fff9826e447 in std::function<void ()>::operator()() const (this=<optimized out>)
    at /usr/include/c++/5/functional:2267
#10 tvm::runtime::GraphRuntime::Run (this=0x555557f2d320)
    at /home/liangfu/workspace/tvm/src/runtime/graph/graph_runtime.cc:55
#11 tvm::runtime::GraphRuntime::<lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::operator() (
    __closure=<optimized out>, rv=<optimized out>, args=...)
    at /home/liangfu/workspace/tvm/src/runtime/graph/graph_runtime.cc:559
#12 std::_Function_handler<void(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::GraphRuntime::GetFunction(const string&, const std::shared_ptr<tvm::runtime::ModuleNode>&)::<lambda(tvm::runtime::TVMArgs, tvm::runtime::T\
VMRetValue*)> >::_M_invoke(const std::_Any_data &, <unknown type in /usr/local/lib/python2.7/dist-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so, CU 0x3bf7fe3, DIE 0x3c3fc8f>, <unknown type in /usr/local/lib/python2.7/dist-pack\
ages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so, CU 0x3bf7fe3, DIE 0x3c3fc94>) (__functor=...,
    __args#0=<optimized out>, __args#1=<optimized out>) at /usr/include/c++/5/functional:1871
#13 0x00007fff981ee758 in std::function<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const (__args#1=0x7fffffffd550, __args#0=..., this=0x7fffffffd628)
    at /usr/include/c++/5/functional:2267
#14 tvm::runtime::PackedFunc::CallPacked (rv=0x7fffffffd550, args=..., this=0x7fffffffd628)
    at /home/liangfu/workspace/tvm/include/tvm/runtime/packed_func.h:684
#15 TVMFuncCall (func=func@entry=0x55555852ba40, args=args@entry=0x7fffffffd640,
    arg_type_codes=arg_type_codes@entry=0x7fffffffd634, num_args=num_args@entry=0,
    ret_val=ret_val@entry=0x7fffffffd628, ret_type_code=ret_type_code@entry=0x7fffffffd61c)
    at /home/liangfu/workspace/tvm/src/runtime/c_runtime_api.cc:264
#16 0x00007fff96a1b28a in __pyx_f_4core_FuncCall3 (__pyx_v_nargs=0, __pyx_v_args=0x7ffff7f7f050,
    __pyx_v_chandle=0x55555852ba40) at tvm/_ffi/_cython/core.cpp:6083
#17 __pyx_f_4core_FuncCall (__pyx_v_args=0x7ffff7f7f050, __pyx_v_chandle=0x55555852ba40)
    at tvm/_ffi/_cython/core.cpp:6180
#18 __pyx_pf_4core_12FunctionBase_4__call__ (__pyx_v_self=<optimized out>, __pyx_v_args=0x7ffff7f7f050)
    at tvm/_ffi/_cython/core.cpp:6958
#19 __pyx_pw_4core_12FunctionBase_5__call__ (__pyx_v_self=<optimized out>, __pyx_args=0x7ffff7f7f050,
    __pyx_kwds=<optimized out>) at tvm/_ffi/_cython/core.cpp:6936
#20 0x000055555563b673 in PyObject_Call ()
#21 0x0000555555654e2f in PyEval_EvalFrameEx ()
#22 0x000055555564d535 in PyEval_EvalCodeEx ()
#23 0x0000555555655698 in PyEval_EvalFrameEx ()
#24 0x000055555564d535 in PyEval_EvalCodeEx ()
#25 0x000055555564d2d9 in PyEval_EvalCode ()
#26 0x000055555567ce3f in ?? ()
#27 0x0000555555677d52 in PyRun_FileExFlags ()
#28 0x000055555567789e in PyRun_SimpleFileExFlags ()
#29 0x0000555555628af1 in Py_Main ()
#30 0x00007ffff6f1a2b1 in __libc_start_main (main=0x555555628420 <main>, argc=2, argv=0x7fffffffdde8,
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffddd8)
    at ../csu/libc-start.c:291
#31 0x000055555562831a in _start ()
```
Please help why `opencl` backend doesn't work well for the image classification task.
