### ISSUE TITLE
Random Error: AttributeError: 'NoneType' object has no attribute 'TVMFuncFree'

### ISSUE THREAD

**Issue by edmBernard** [dmlc/tvm#563]
After graph execution on tvm with this code : 
```python
    # Compile model
    # target can be "opencl", "llvm", "metal" or any target supported by tvm
    target = "llvm"
    shape_dict = {'data': resized_img.shape}
    graph, lib, params = nnvm.compiler.build(nnvm_sym, target, shape_dict, params=nnvm_params)

    # Run on TVM
    ctx = tvm.cpu(0)
    dtype = 'float32'
    m = graph_runtime.create(graph, lib, ctx)
    # set inputs
    m.set_input('data', tvm.nd.array(resized_img.astype(dtype)))
    m.set_input(**params)
    # execute
    m.run()
    # get outputs
    tvm_output = m.get_output(0, tvm.nd.empty((2,), dtype))
    print(tvm_output.asnumpy())
    top1 = np.argmax(tvm_output.asnumpy())
    print('TVM prediction top-1:', top1)
```

I got sometimes the following error but not always
```bash
[  1.21967696e-05   9.99987841e-01]
TVM prediction top-1: 1
Exception ignored in: <bound method FunctionBase.__del__ of <tvm._ffi.function.Function object at 0x7f896b323c18>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.1.0-py3.5-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 169, in __del__
AttributeError: 'NoneType' object has no attribute 'TVMFuncFree'
Exception ignored in: <bound method FunctionBase.__del__ of <tvm._ffi.function.Function object at 0x7f896b323c60>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.1.0-py3.5-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 169, in __del__
AttributeError: 'NoneType' object has no attribute 'TVMFuncFree'
Exception ignored in: <bound method FunctionBase.__del__ of <tvm._ffi.function.Function object at 0x7f896b323bd0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.1.0-py3.5-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 169, in __del__
AttributeError: 'NoneType' object has no attribute 'TVMFuncFree'
Exception ignored in: <bound method FunctionBase.__del__ of <tvm._ffi.function.Function object at 0x7f8972decd80>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.1.0-py3.5-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 169, in __del__
AttributeError: 'NoneType' object has no attribute 'TVMFuncFree'
Exception ignored in: <bound method FunctionBase.__del__ of <tvm._ffi.function.Function object at 0x7f8972decc18>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.1.0-py3.5-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 169, in __del__
AttributeError: 'NoneType' object has no attribute 'TVMFuncFree'
Exception ignored in: <bound method FunctionBase.__del__ of <tvm._ffi.function.Function object at 0x7f8972decbd0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.1.0-py3.5-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 169, in __del__
AttributeError: 'NoneType' object has no attribute 'TVMFuncFree'
```

The line generating this error : https://github.com/dmlc/tvm/blob/60510a47cf5380a6af8bb7cd638082ad31929ed7/python/tvm/_ffi/_ctypes/function.py#L169

**Comment by tqchen** [comment]
the warnings can be safely ignored. Mainly due to destructing order issues. If you encapsulate them in python function, it won't happen

**Comment by tqchen** [comment]
see if https://github.com/dmlc/tvm/pull/583 fixes the problem

**Comment by edmBernard** [comment]
thx for your work
