### ISSUE TITLE
How to add some function in topi/nn/?

### ISSUE THREAD

**Issue by Arthur-Shi** [dmlc/tvm#568]
I am trying add some function in topi.nn, But after I add one my function, i cannot run the test files. 

python '/home/aries/tvm/topi/recipe/conv/copydepth.py' 
Traceback (most recent call last):
  File "/home/aries/tvm/topi/recipe/conv/copydepth.py", line 197, in <module>
    test_depthwise_conv2d_nchw()
  File "/home/aries/tvm/topi/recipe/conv/copydepth.py", line 38, in test_depthwise_conv2d_nchw
    DepthwiseConv2d = topi.nn.gaidepthwise_conv2d_nchw(Input, Filter, Stride, padding)
AttributeError: 'module' object has no attribute 'gaidepthwise_conv2d_nchw'

So I tried to install the tvm and topi again. But not make them.
But now I cannot run any test files.

TVM: Initializing cython mode...
Traceback (most recent call last):
  File "/home/aries/tvm/topi/recipe/conv/depthwise_conv2d_test.py", line 2, in <module>
    import tvm
  File "/home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/__init__.py", line 5, in <module>
    from . import tensor
  File "/home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/tensor.py", line 6, in <module>
    from . import make as _make
  File "/home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/make.py", line 130, in <module>
    _init_api("tvm.make")
  File "/home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/function.py", line 268, in _init_api
    for name in list_global_func_names():
  File "/home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/function.py", line 229, in list_global_func_names
    check_call(_LIB.depthwise_conv2d_nchwTVMFuncListGlobalNames(ctypes.byref(size),
  File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/aries/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/libtvm.so: undefined symbol: depthwise_conv2d_nchwTVMFuncListGlobalNames

What can I do now? And how to add some function in the topi/nn module

**Comment by Arthur-Shi** [comment]
I deleted all files I added， and it works again.

But I would like to add some functions in tvm/python/tvm and tvm/topi/python/topi,
What should I do after added them into folders?

Thank you in advance for ur help.

**Comment by tqchen** [comment]
Depend on how you do your development. If you do insource development (setup PYTHONPATH), then it would be totally fine

**Comment by Arthur-Shi** [comment]
I just copy the tvm/topi/python/topi/nn/depthwise_conv2d.py and rename its function names, But It cannot be used.

I have installed again and setup pythonpath in bashrc file ( export PYTHONPATH=...)

What should I do? @tqchen 

Traceback (most recent call last):
  File "/home/aries/testtvm/tvm/topi/recipe/conv/depthwise_conv2d_test.py", line 212, in <module>
    test_depthwise_conv2d_nchw()
  File "/home/aries/testtvm/tvm/topi/recipe/conv/depthwise_conv2d_test.py", line 55, in test_depthwise_conv2d_nchw
    DepthwiseConv2d = topi.nn.depthcope_conv2d_nchw(Input, Filter, Stride, padding)
AttributeError: 'module' object has no attribute 'depthcope_conv2d_nchw'

**Comment by tqchen** [comment]
you will need to import the function you defined in topi/nn/__init__.py

**Comment by Arthur-Shi** [comment]
It works.
