### ISSUE TITLE
failed to call a env compiler(gcc) to create a shared library.

### ISSUE THREAD

**Issue by Arthur-Shi** [dmlc/tvm#602]
I followed the get_tutorial file to save and load f3, but cannot to calls a env compiler(gcc) to create a shared library.

    f3 = tvm.build(s3, [Input, Filter, Scale, Shift, Relu], "cuda", target_host="llvm")
        dev_module = f3.imported_modules[0]

    base_path="/home/aries/tvm/apps/howto_deploy/lib"
    dylib_path = os.path.join(base_path, "test_depth.so")
    f3.export_library(dylib_path)
    dylib_path3 = os.path.join (base_path, "test_depthcuda.o")
    f3.save (dylib_path3)

    dylib_path2 = os.path.join(base_path, "test_depthcuda.ptx")
    dev_module.save(dylib_path2)

    cc.create_shared("/home/aries/tvm/apps/howto_deploy/lib/test_depthcuda.o", ["/home/aries/tvm/apps/howto_deploy/lib/test_depthcuda.ptx"])

    fadd1 = tvm.module.load("/home/aries/tvm/apps/howto_deploy/lib/test_depth.so")
    fadd1_dev = tvm.module.load("/home/aries/tvm/apps/howto_deploy/lib/test_depthcuda.ptx")
    fadd1.import_module(fadd1_dev)
    fadd1(input_tvm, filter_tvm, scale_tvm, shift_tvm, relu_tvm)
    print(relu_tvm.asnumpy())
    print(np.testing.assert_allclose(relu_tvm.asnumpy(), relu_scipy, rtol=1e-5))

The out put is:

Traceback (most recent call last):
  File "/home/aries/tvm/topi/tests/python/testfordepthos.py", line 143, in <module>
    test_depthwise_conv2d()
  File "/home/aries/tvm/topi/tests/python/testfordepthos.py", line 124, in test_depthwise_conv2d
    depthwise_conv2d_with_workload_nchw(1, 728, 64, 1, 3, 1, "SAME")
  File "/home/aries/tvm/topi/tests/python/testfordepthos.py", line 108, in depthwise_conv2d_with_workload_nchw
    cc.create_shared("/home/aries/tvm/apps/howto_deploy/lib/test_depthcuda.o", ["/home/aries/tvm/apps/howto_deploy/lib/test_depthcuda.ptx"])
  File "/home/aries/tvm/python/tvm/contrib/cc.py", line 32, in create_shared
    _linux_shared(output, objects, options, cc)
  File "/home/aries/tvm/python/tvm/contrib/cc.py", line 57, in _linux_shared
    raise RuntimeError(msg)
RuntimeError: Compilation error:
/usr/bin/ld:/home/aries/tvm/apps/howto_deploy/lib/test_depthcuda.ptx: file format not recognized; treating as linker script
/usr/bin/ld:/home/aries/tvm/apps/howto_deploy/lib/test_depthcuda.ptx:2: syntax error
collect2: error: ld returned 1 exit status

But the tvm build setting in tutorial is exactly same as the f3, why?

And also, if I deleted the content which is relative to   fadd1_dev,  it can works well.

**Comment by Arthur-Shi** [comment]
Is saving the device module very important, Because I can save the module in .so file and load it.

**Comment by Arthur-Shi** [comment]
cc.create_shared("/home/aries/tvm/apps/howto_deploy/lib/test_depthcuda.so", ["/home/aries/tvm/apps/howto_deploy/lib/test_depthcuda.o"])

I made the mistake, sorry.
