### ISSUE TITLE
Python installation issue

### ISSUE THREAD

**Issue by ncybmh99** [dmlc/tvm#630]
Following the instructions:

1. copy config.mk into the root directory and "make"
2. export PYTHONPATH=/path/to/tvm/python:/path/to/tvm/topi/python:${PYTHONPATH}
3. cd python; python setup.py install --user; cd ..
4. cd topi/python; python setup.py install --user; cd ../..

Now I try to get started:

>>> import tvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/__init__.py", line 16, in <module>
    from . import ir_builder
  File "~/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/ir_builder.py", line 4, in <module>
    from . import api as _api
  File "~/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/api.py", line 20, in <module>
    from . import tag as _tag
  File "~/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/tag.py", line 8, in <module>
    raise err_msg
ImportError: cannot import name decorate

But "decorate" is already installed. If I just import

>>> import decoreate
>>>

and then try tvm again:

>>> import tvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/__init__.py", line 5, in <module>
    from . import tensor
ImportError: cannot import name tensor

What is missed? System is Ubuntu 14.04.

Thanks.

**Comment by edmBernard** [comment]
Can you try to change your installation process ?

1. copy config.mk into the root directory + `make` and `make install` ***don't forget `make install`***
2. ~export PYTHONPATH=/path/to/tvm/python:/path/to/tvm/topi/python:${PYTHONPATH}~  it can conflict with `setup.py install`
4. `cd /path/to/tvm/topi/python; python2 setup.py install --user # install topi first`
3. `cd /path/to/tvm/python; python2 setup.py install --user`

**Comment by tqchen** [comment]
Close due to inactive issue, feel free to reopen if there is further questions

**Comment by ricann** [comment]
I encounter the same question, how can I solve it? thank you~~

```
ImportError: cannot import name tensor
```
