### ISSUE TITLE
freeze when using set_input

### ISSUE THREAD

**Issue by edmBernard** [dmlc/tvm#729]
I try to use tvm to load a compiled network and use it on images.
My code freeze and crash with this error : 
```bash
Traceback (most recent call last):
  File "crash_tvm_minimal.py", line 91, in <module>
    main()
  File "crash_tvm_minimal.py", line 83, in main
    set_input('data', tvm.nd.array(resized_img.astype('float32')))  # blocked here
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.1.0-py3.5-linux-x86_64.egg/tvm/ndarray.py", line 166, in array
    return empty(arr.shape, arr.dtype, ctx).copyfrom(arr)
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.1.0-py3.5-linux-x86_64.egg/tvm/_ffi/ndarray.py", line 104, in empty
    dtype = TVMType(dtype)
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.1.0-py3.5-linux-x86_64.egg/tvm/_ffi/runtime_ctypes.py", line 68, in __init__
    raise ValueError("Donot know how to handle type %s" % type_str)
ValueError: Donot know how to handle type object
```

That surely a silly mistake but I don't find where. The minimal code to reproduce this error is here:
https://gist.github.com/edmBernard/3fb545ab3d1c98e73add549e0f8c38e6

**Comment by tqchen** [comment]
The error message seems to suggest ```resized_img.astype('float32')``` becomes "object" for some reason

**Comment by edmBernard** [comment]
Got it, that's `tvm.nd.array` it only accept numpy array and don't know nd.array
minimal example:
```python
>>> import numpy as np
>>> from mxnet import nd
>>> import tvm
>>> a = np.zeros((10,10))
>>> b = nd.zeros((10,10))
>>> tvm.nd.array(a)
<tvm.NDArray shape=(10, 10), cpu(0)>
array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])
>>> tvm.nd.array(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.1.0-py3.5-linux-x86_64.egg/tvm/ndarray.py", line 166, in array
    return empty(arr.shape, arr.dtype, ctx).copyfrom(arr)
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.1.0-py3.5-linux-x86_64.egg/tvm/_ffi/ndarray.py", line 104, in empty
    dtype = TVMType(dtype)
  File "/usr/local/lib/python3.5/dist-packages/tvm-0.1.0-py3.5-linux-x86_64.egg/tvm/_ffi/runtime_ctypes.py", line 68, in __init__
    raise ValueError("Donot know how to handle type %s" % type_str)
ValueError: Donot know how to handle type object
```
