### ISSUE TITLE
Getting a SocketTimeoutException on connecting to proxy server

### ISSUE THREAD

**Issue by nightfox8** [dmlc/tvm#740]
getting this connecting to a proxy server on '192.168.0.23',

12-29 18:24:01.972 24962-24962/ml.dmlc.tvm.tvmrpc W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
12-29 18:24:14.727 24962-24989/ml.dmlc.tvm.tvmrpc W/System.err: java.net.SocketTimeoutException: failed to connect to /192.168.0.23 (port 9090) after 6000ms
12-29 18:24:14.727 24962-24989/ml.dmlc.tvm.tvmrpc W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
12-29 18:24:14.727 24962-24989/ml.dmlc.tvm.tvmrpc W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
12-29 18:24:14.727 24962-24989/ml.dmlc.tvm.tvmrpc W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
12-29 18:24:14.727 24962-24989/ml.dmlc.tvm.tvmrpc W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
12-29 18:24:14.727 24962-24989/ml.dmlc.tvm.tvmrpc W/System.err:     at java.net.Socket.connect(Socket.java:884)
12-29 18:24:14.727 24962-24989/ml.dmlc.tvm.tvmrpc W/System.err:     at ml.dmlc.tvm.rpc.ConnectProxyServerProcessor.run(ConnectProxyServerProcessor.java:62)
12-29 18:24:14.727 24962-24989/ml.dmlc.tvm.tvmrpc W/System.err:     at ml.dmlc.tvm.tvmrpc.RPCProcessor.run(RPCProcessor.java:67)
12-29 18:24:14.730 24962-24962/ml.dmlc.tvm.tvmrpc W/System.err: Disconnected.

**Comment by tqchen** [comment]
you will need to open the rpc_proxy locally and make sure the RPC proxy is ready to open, currently this issue is not informative enough

**Comment by nightfox8** [comment]
How can I do that? can you give me steps or quick guide for that?

**Comment by tqchen** [comment]
as explained in http://tvmlang.org/2017/11/08/android-rpc-introduction.html

```python
python -m tvm.exec.rpc_proxy

```

**Comment by nightfox8** [comment]
I tried to run with RPC proxy but getting this errors,
```
INFO:root:RPCProxy: client port bind to 0.0.0.0:9091
Process Process-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/hardik.chauhan/Library/Python/2.7/lib/python/site-packages/tvm-0.1.0-py2.7-macosx-10.12-intel.egg/tvm/contrib/rpc_proxy.py", line 353, in _proxy_server
    resource_files)
  File "/Users/hardik.chauhan/Library/Python/2.7/lib/python/site-packages/tvm-0.1.0-py2.7-macosx-10.12-intel.egg/tvm/contrib/rpc_proxy.py", line 278, in __init__
    self.app.listen(web_port)
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 1943, in listen
    server.listen(port, address)
  File "/Library/Python/2.7/site-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/Library/Python/2.7/site-packages/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 48] Address already in use
INFO:root:Terminating Proxy Server...
SA-MAC-002:tests hardik.chauhan$ python android_rpc_test.py 
Traceback (most recent call last):
  File "android_rpc_test.py", line 13, in <module>
    proxy_host = os.environ["TVM_ANDROID_RPC_PROXY_HOST"]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'TVM_ANDROID_RPC_PROXY_HOST'
```

**Comment by amitsrivastava78** [comment]
Hi Hardick,
           Seems like it is giving the error as the local port is already in use, please run the netstat command and try to see the status of 9091 port. Try to use a different port number if it already in use.
Regards
Amit
