### ISSUE TITLE
Crash when building unet-style network

### ISSUE THREAD

**Issue by thefiddler** [dmlc/tvm#787]
Cross-referencing from https://github.com/dmlc/nnvm/pull/311 and https://github.com/dmlc/nnvm/issues/312

When trying to build this network, I am receiving a crash in TVM [(complete log here)](http://mode-gpu.cs.washington.edu:8080/blue/organizations/jenkins/dmlc%2Fnnvm/detail/PR-311/3/pipeline/#step-89-log-633).

```bash
ERROR: test_forward.test_forward_unet
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/workspace/tests/python/frontend/keras/test_forward.py", line 235, in test_forward_unet
    verify_keras_frontend(keras_model)
  File "/workspace/tests/python/frontend/keras/test_forward.py", line 41, in verify_keras_frontend
    tvm_out = get_tvm_output(x.transpose([0,3,1,2]), target, ctx)
  File "/workspace/tests/python/frontend/keras/test_forward.py", line 30, in get_tvm_output
    graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)
  File "/workspace/python/nnvm/compiler/build_module.py", line 251, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/workspace/python/nnvm/graph.py", line 235, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/workspace/python/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/workspace/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/workspace/python/nnvm/compiler/build_module.py", line 119, in _build
    return tvm.build(funcs, target=target, target_host=target_host)
  File "/workspace/tvm/python/tvm/build_module.py", line 361, in build
    mhost = codegen.build_module(fhost, str(target_host))
  File "/workspace/tvm/python/tvm/codegen.py", line 20, in build_module
    return _Build(lowered_func, target)
  File "/workspace/tvm/python/tvm/_ffi/function.py", line 255, in my_api_func
    return flocal(*args)
  File "/workspace/tvm/python/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/workspace/tvm/python/tvm/_ffi/base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
TVMError: [13:59:14] src/codegen/llvm/codegen_cpu.cc:417: Check failed: par_env.parallel_loop_count != 0 (0 vs. 0) Cannot find parallel loop within parallel launch

Stack trace returned 10 entries:
[bt] (0) /workspace/tvm/lib/libtvm.so(_ZN4dmlc10StackTraceB5cxx11Ev+0x5a) [0x7f5bc8c9186a]
[bt] (1) /workspace/tvm/lib/libtvm.so(_ZN4dmlc15LogMessageFatalD1Ev+0x28) [0x7f5bc8c922f8]
[bt] (2) /workspace/tvm/lib/libtvm.so(_ZN3tvm7codegen10CodeGenCPU20CreateParallelLaunchERKN8HalideIR8Internal4StmtEi+0x72b) [0x7f5bc8f1a3fb]
[bt] (3) /workspace/tvm/lib/libtvm.so(_ZN3tvm7codegen10CodeGenCPU10VisitStmt_EPKN8HalideIR8Internal8AttrStmtE+0x2ee) [0x7f5bc8f1c7de]
[bt] (4) /workspace/tvm/lib/libtvm.so(_ZNK3tvm9IRFunctorIFvRKNS_7NodeRefEPNS_2ir11StmtFunctorIFvRKN8HalideIR8Internal4StmtEEEEEEclES3_SD_+0x11d) [0x7f5bc8e4bcbd]
[bt] (5) /workspace/tvm/lib/libtvm.so(_ZNK3tvm9IRFunctorIFvRKNS_7NodeRefEPNS_2ir11StmtFunctorIFvRKN8HalideIR8Internal4StmtEEEEEEclES3_SD_+0x11d) [0x7f5bc8e4bcbd]
[bt] (6) /workspace/tvm/lib/libtvm.so(_ZN3tvm7codegen11CodeGenLLVM10VisitStmt_EPKN8HalideIR8Internal5BlockE+0x1c) [0x7f5bc8efd84c]
[bt] (7) /workspace/tvm/lib/libtvm.so(_ZNK3tvm9IRFunctorIFvRKNS_7NodeRefEPNS_2ir11StmtFunctorIFvRKN8HalideIR8Internal4StmtEEEEEEclES3_SD_+0x11d) [0x7f5bc8e4bcbd]
[bt] (8) /workspace/tvm/lib/libtvm.so(_ZNK3tvm9IRFunctorIFvRKNS_7NodeRefEPNS_2ir11StmtFunctorIFvRKN8HalideIR8Internal4StmtEEEEEEclES3_SD_+0x11d) [0x7f5bc8e4bcbd]
[bt] (9) /workspace/tvm/lib/libtvm.so(_ZNK3tvm9IRFunctorIFvRKNS_7NodeRefEPNS_2ir11StmtFunctorIFvRKN8HalideIR8Internal4StmtEEEEEEclES3_SD_+0x11d) [0x7f5bc8e4bcbd]
```

Any help would be appreciated!

**Comment by tqchen** [comment]
cross ref  a possible solution in https://github.com/dmlc/nnvm/issues/312

**Comment by tqchen** [comment]
Please see if the current master resolved the issue after https://github.com/dmlc/tvm/pull/775 get merged

**Comment by thefiddler** [comment]
@masahi the NNVM keras frontend expects NHWC and transforms that automatically to NCHW for TVM. The shape on that line is the same on every other successful test in that file, so I don't think that's the issue.

@tqchen let me check.

**Comment by thefiddler** [comment]
PR #775 makes this work. Closing the issue!
