### ISSUE TITLE
RPC test failed with  cross_compilation_and_rpc.py

### ISSUE THREAD

**Issue by betsyweilin** [dmlc/tvm#790]
I follow the Tutorials to run cross_compilation_and_rpc.py . Locally, it runs well, but when I set host to remote device, it runs fail, with error as below:

1)local device , 
run: python -m tvm.exec.rpc_proxy 
run: python  cross_compilation_and_rpc.py

2)remote device ip is "192.168.1.102",
run:  python -m tvm.exec.rpc_server --host 0.0.0.0 --port=9090
get the output as
`INFO:root:RPCServer: connection from ('192.168.1.101', 49212)
INFO:root:Connection from ('192.168.1.101', 49212)
[13:02:02] src/runtime/rpc/rpc_server_env.cc:23: Upload /tmp/tmpf5puXs/mylib.o... nbytes=4288
INFO:root:Create shared library based on /tmp/tmpf5puXs/mylib.o
[13:02:02] src/runtime/rpc/rpc_session.cc:751: Shutdown...
INFO:root:Finish serving ('192.168.1.101', 49212)`

local device get output as:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/exec/rpc_server.py", line 43, in <module>
    main()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/exec/rpc_server.py", line 38, in main
    server = rpc.Server(args.host, args.port, args.port_end)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/contrib/rpc.py", line 200, in __init__
    raise sock_err
socket.error: [Errno 99] Cannot assign requested address
Exception AttributeError: "'Server' object has no attribute 'proc'" in <bound method Server.__del__ of <tvm.contrib.rpc.Server object at 0x7f4522e74850>> ignored
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['python', '-m', 'tvm.exec.rpc_server', '--host=192.168.1.102', '--port=9090']' returned non-zero exit status 1
Traceback (most recent call last):
  File "cross_ori.py", line 186, in <module>
    f = remote.load_module('mylib.o')
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/contrib/rpc.py", line 353, in load_module
    return _LoadRemoteModule(self._sess, path)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/function.py", line 255, in my_api_func
    return flocal(*args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-x86_64.egg/tvm/_ffi/base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: Except caught from RPC call: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/home/remote/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-aarch64.egg/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/remote/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-aarch64.egg/tvm/contrib/rpc.py", line 44, in load_module
    cc.create_shared(path + ".so", path)
  File "/home/remote/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-aarch64.egg/tvm/contrib/cc.py", line 32, in create_shared
    _linux_shared(output, objects, options, cc)
  File "/home/remote/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-aarch64.egg/tvm/contrib/cc.py", line 57, in _linux_shared
    raise RuntimeError(msg)
RuntimeError: Compilation error:
/usr/bin/ld: /tmp/tmpCAA5A7/mylib.o: Relocations in generic ELF (EM: 62)
/usr/bin/ld: /tmp/tmpCAA5A7/mylib.o: Relocations in generic ELF (EM: 62)
/tmp/tmpCAA5A7/mylib.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status`

Any help about this issue?
Thanks

**Comment by tqchen** [comment]
the error message in remote reads
```
```

**Comment by tqchen** [comment]
It is likely due to the fact that you did not set the correct target triple. The default tripe for remote works for raspbery-pi, but not on aarch64 device.

**Comment by tqchen** [comment]
see http://docs.tvmlang.org/tutorials/deployment/cross_compilation_and_rpc.html#run-opencl-kernel-remotely-by-rpc which might gives you an example target triple for aarch64 board
