### ISSUE TITLE
[ndarray : uint8] Does TVM support ?

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/tvm#859]
I am trying to implement image operations through extern interface (in cpp).
I would require Tensor args with dtype=uint8 for filenames / byte stream ..etc.

Does TVM support now ?

Build is good with uint8 but I have below error on run.

```
Traceback (most recent call last):
  File "tutorials/language/extern_op_jpeg.py", line 78, in <module>
    f(decode_in, decode_out)
  File "/home/srk/.local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/_ffi/function.py", line 128, in __call__
    return f(*args)
  File "/home/srk/.local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/srk/.local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/_ffi/base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [21:26:44] src/codegen/llvm/llvm_module.cc:59: Check failed: ret == 0 (-1 vs. 0) Assert fail: (((tvm_struct_get(arg0, 0, 5) == (uint8)2) && (tvm_struct_get(arg0, 0, 6) == (uint8)32)) && (tvm_struct_get(arg0, 0, 7) == (uint16)1)), arg0.dtype is expected to be float32

Stack trace returned 10 entries:
[bt] (0) /home/srk/.local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/libtvm.so(_ZN4dmlc10StackTraceB5cxx11Ev+0x53) [0x7f55a1e730b3]
[bt] (1) /home/srk/.local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/libtvm.so(_ZZN3tvm7codegen14LLVMModuleNode11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_7runtime10ModuleNodeEEENKUlNSB_7TVMArgsEPNSB_11TVMRetValueEE0_clESG_SI_+0x78f) [0x7f55a20da3ef]
[bt] (2) /home/srk/.local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/libtvm.so(_ZNSt17_Function_handlerIFvN3tvm7runtime7TVMArgsEPNS1_11TVMRetValueEEZNS0_7codegen14LLVMModuleNode11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS1_10ModuleNodeEEEUlS2_S4_E0_E9_M_invokeERKSt9_Any_dataOS2_OS4_+0x17) [0x7f55a20da707]
[bt] (3) /home/srk/.local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/libtvm.so(TVMFuncCall+0x5e) [0x7f55a2232a5e]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f55aa022e18]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x32a) [0x7f55aa02287a]
[bt] (6) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x4cd) [0x7f55aa23696d]
[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x8727) [0x7f55aa22d727]
[bt] (8) python3(_PyObject_FastCallDict+0xa3) [0x459893]
[bt] (9) python3() [0x54f117]

```
Appreciate any help here.

Regards,
Siva

**Comment by tqchen** [comment]
pass in dtype of http://docs.tvmlang.org/api/python/tvm.html#tvm.extern
