### ISSUE TITLE
TVM deallocation error

### ISSUE THREAD

**Issue by amitsrivastava78** [dmlc/tvm#903]
Hi All,
       I am getting the TVM  de-allocation error while running my front-end, can anyone help to solve this problem.

 File "/home/amit/.local/lib/python3.5/site-packages/tvm-0.2.0-py3.5-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 169, in __del__
AttributeError: 'NoneType' object has no attribute 'TVMFuncFree'
Exception ignored in: <bound method FunctionBase.__del__ of <tvm._ffi.function.Function object at 0x7f374208ad38>>
Traceback (most recent call last):
  File "/home/amit/.local/lib/python3.5/site-packages/tvm-0.2.0-py3.5-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 169, in __del__
AttributeError: 'NoneType' object has no attribute 'TVMFuncFree'
Exception ignored in: <bound method FunctionBase.__del__ of <tvm._ffi.function.Function object at 0x7f374208aca8>>
Traceback (most recent call last):
  File "/home/amit/.local/lib/python3.5/site-packages/tvm-0.2.0-py3.5-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 169, in __del__
AttributeError: 'NoneType' object has no attribute 'TVMFuncFree'
Exception ignored in: <bound method FunctionBase.__del__ of <tvm._ffi.function.Function object at 0x7f374b7d7fc0>>
Traceback (most recent call last):
  File "/home/amit/.local/lib/python3.5/site-packages/tvm-0.2.0-py3.5-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 169, in __del__
AttributeError: 'NoneType' object has no attribute 'TVMFuncFree'
Exception ignored in: <bound method FunctionBase.__del__ of <tvm._ffi.function.Function object at 0x7f374b7d7f78>>
Traceback (most recent call last):
  File "/home/amit/.local/lib/python3.5/site-packages/tvm-0.2.0-py3.5-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 169, in __del__
AttributeError: 'NoneType' object has no attribute 'TVMFuncFree'
Exception ignored in: <bound method FunctionBase.__del__ of <tvm._ffi.function.Function object at 0x7f374b7e5240>>
Traceback (most recent call last):
  File "/home/amit/.local/lib/python3.5/site-packages/tvm-0.2.0-py3.5-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 169, in __del__
AttributeError: 'NoneType' object has no attribute 'TVMFuncFree'

Regards
Amit

**Comment by tqchen** [comment]
Please see if #985 resolves the problem
