### ISSUE TITLE
Question about Android RPC

### ISSUE THREAD

**Issue by doldre** [dmlc/tvm#948]
I compiled and installed android_rpc apk to my android phone according https://github.com/dmlc/tvm/tree/master/apps/android_rpc.

And I started a proxy server in my macbook(10.151.0.250:9090) , and set up the (address=10.151.0.250, port=9090, key=android) in the app. I ran [android_rpc_test.py](https://github.com/dmlc/tvm/blob/master/apps/android_rpc/tests/android_rpc_test.py) in a server. But I encountered this.
```
% python android_rpc_test.py
[20:22:36] src/runtime/opencl/opencl_device_api.cc:197: Initialize OpenCL platform 'NVIDIA CUDA'
[20:22:37] src/runtime/opencl/opencl_device_api.cc:222: opencl(0)='GeForce GTX 1080 Ti' cl_device_id=0x55e126c5f030
Run GPU test ...
Traceback (most recent call last):
  File "android_rpc_test.py", line 75, in <module>
    test_rpc_module()
  File "android_rpc_test.py", line 53, in test_rpc_module
    f1 = remote.load_module("dev_lib.so")
  File "/home/luoxinchen/workspace/tvm-mali/nnvm/tvm/python/tvm/contrib/rpc.py", line 352, in load_module
    return _LoadRemoteModule(self._sess, path)
  File "/home/luoxinchen/workspace/tvm-mali/nnvm/tvm/python/tvm/_ffi/function.py", line 280, in my_api_func
    return flocal(*args)
  File "/home/luoxinchen/workspace/tvm-mali/nnvm/tvm/python/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/luoxinchen/workspace/tvm-mali/nnvm/tvm/python/tvm/_ffi/base.py", line 66, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: Except caught from RPC call: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/Users/mathon/workspace/tvm-mali/nnvm/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/Users/mathon/workspace/tvm-mali/nnvm/tvm/python/tvm/contrib/rpc.py", line 52, in load_module
    m = _load_module(path)
  File "/Users/mathon/workspace/tvm-mali/nnvm/tvm/python/tvm/module.py", line 199, in load
    return _LoadFromFile(path, fmt)
  File "/Users/mathon/workspace/tvm-mali/nnvm/tvm/python/tvm/_ffi/function.py", line 280, in my_api_func
    return flocal(*args)
  File "/Users/mathon/workspace/tvm-mali/nnvm/tvm/python/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/Users/mathon/workspace/tvm-mali/nnvm/tvm/python/tvm/_ffi/base.py", line 66, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
TVMError: [20:22:52] src/runtime/dso_module.cc:93: Check failed: lib_handle_ != nullptr Failed to load dynamic shared library /var/folders/bd/lhvp2gtn7_j9mg35x_yhqbp00000gn/T/tmpreDbzf/dev_lib.so dlopen(/var/folders/bd/lhvp2gtn7_j9mg35x_yhqbp00000gn/T/tmpreDbzf/dev_lib.so, 5): no suitable image found.  Did find:
        /var/folders/bd/lhvp2gtn7_j9mg35x_yhqbp00000gn/T/tmpreDbzf/dev_lib.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
        /private/var/folders/bd/lhvp2gtn7_j9mg35x_yhqbp00000gn/T/tmpreDbzf/dev_lib.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

Stack trace returned 9 entries:
[bt] (0) 0   libtvm_runtime.dylib                0x00000001097bf30b dmlc::StackTrace() + 299
[bt] (1) 1   libtvm_runtime.dylib                0x00000001097bf09f dmlc::LogMessageFatal::~LogMessageFatal() + 47
[bt] (2) 2   libtvm_runtime.dylib                0x00000001097c8e0e tvm::runtime::DSOModuleNode::Load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 270
[bt] (3) 3   libtvm_runtime.dylib                0x00000001097c8715 std::__1::__function::__func<tvm::runtime::$_0, std::__1::allocator<tvm::runtime::$_0>, void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::operator()(tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) + 261
[bt] (4) 4   libtvm_runtime.dylib                0x00000001097d3af6 tvm::runtime::Module::LoadFromFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 902
[bt] (5) 5   libtvm_runtime.dylib                0x00000001097d7410 std::__1::__function::__func<tvm::runtime::$_5, std::__1::allocator<tvm::runtime::$_5>, void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::operator()(tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) + 192
[bt] (6) 6   libtvm_runtime.dylib                0x00000001097c0e48 TVMFuncCall + 72
[bt] (7) 7   libffi.dylib                        0x00007fff74d08f64 ffi_call_unix64 + 76
[bt] (8) 8   ???                                 0x00007ffee6eb8670 0x0 + 140732772615792
```

```
# 10.151.0.201 is the android phone
# 10.201.106.8 is the server
➜  tvm git:(30eaf46) ✗ python -m tvm.exec.rpc_server --host 0.0.0.0 --port=9090
INFO:root:RPCServer: bind to 0.0.0.0:9090
INFO:root:RPCServer: connection from ('10.151.0.201', 48241)
INFO:root:Connection from ('10.151.0.201', 48241)
INFO:root:RPCServer: connection from ('10.201.106.8', 53936)
INFO:root:Connection from ('10.201.106.8', 53936)
[20:16:51] src/runtime/rpc/rpc_server_env.cc:23: Upload /var/folders/bd/lhvp2gtn7_j9mg35x_yhqbp00000gn/T/tmpPgqKQY/dev_lib.so... nbytes=11616
[20:16:51] src/runtime/rpc/rpc_session.cc:751: Shutdown...
INFO:root:Finish serving ('10.201.106.8', 53936)
INFO:root:RPCServer: connection from ('10.201.106.8', 37738)
INFO:root:Connection from ('10.201.106.8', 37738)
[20:22:52] src/runtime/rpc/rpc_server_env.cc:23: Upload /var/folders/bd/lhvp2gtn7_j9mg35x_yhqbp00000gn/T/tmpreDbzf/dev_lib.so... nbytes=11616
[20:22:52] src/runtime/rpc/rpc_session.cc:751: Shutdown...
INFO:root:Finish serving ('10.201.106.8', 37738)
```

It seems like the shared library did not run in my phone but in my macbook. What's wrong here ?

**Comment by doldre** [comment]
Sorry, I found my mistake. I should use tvm.exec.rpc_proxy
