### ISSUE TITLE
RPC deploying failed

### ISSUE THREAD

**Issue by joyalbin** [dmlc/tvm#996]
When trying to deploy my library on android device gpu using RPC, following error is showing:
DEPLOY: Shared Library Uploading...
Traceback (most recent call last):
  File "tests/python/compiler/test_top_dense.py", line 111, in <module>
    verify_dense_()
  File "tests/python/compiler/test_top_dense.py", line 93, in verify_dense_
    rmodule = graph_runtime.create(graph, rlib, ctx)
  File "/home/albin/.local/lib/python2.7/site-packages/tvm-0.2.0-py2.7-linux-x86_64.egg/tvm/contrib/graph_runtime.py", line 42, in create
    return GraphModule(fcreate(graph_json_str, hmod, device_type, device_id), ctx)
  File "/home/albin/.local/lib/python2.7/site-packages/tvm-0.2.0-py2.7-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/albin/.local/lib/python2.7/site-packages/tvm-0.2.0-py2.7-linux-x86_64.egg/tvm/_ffi/base.py", line 66, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: Except caught from RPC call: [06:19:16] /media/DataDisk/work/working_copy/tvm/apps/android_rpc/app/src/main/jni/../../../../../../include/../src/runtime/graph/graph_runtime.cc:515: Check failed: ret == 0 (-1 vs. 0) [06:19:16] /media/DataDisk/work/working_copy/tvm/apps/android_rpc/app/src/main/jni/../../../../../../include/../src/runtime/opencl/opencl_device_api.cc:60: Check failed: err_code == CL_SUCCESS OpenCL Error, code=-61: CL_INVALID_BUFFER_SIZE

Please help me to resolve it

**Comment by yarneer** [comment]
I  think this a same problem like  #995 
you'd better to upgrade tvm and rebuild apk

**Comment by joyalbin** [comment]
@yarneer, I will try it and let you know. Thank you so much
